### ISSUE TITLE
Note de révision: erreur dans le libellé du nouveau critère 2.2

### ISSUE THREAD

**Issue by OlivierNourry** [DISIC/RGAA#10]
La note de révision indique:
Nouveau critère 2.2
Critère 2.2 Chaque cadre a-t-il un titre de cadre ?

Or le nouveau critère 2.2 est "Pour chaque cadre ayant un titre de cadre, ce titre de cadre est-il pertinent ?"

**Comment by acaodinsic** [comment]
Merci pour votre signalement.

Il s'agit d'une mauvaise manip de copié-collé, uniquement dans la note révision.
La correction sera apportée dans la note de révision dans les documents de référence de la version RGAA 4.0, et également dans la note renommée note-de-revision-rgaa30-rgaa40 dans les documents de référence de la version RGAA 4.1

La correction est effectuée **en premier** dans les documents de référence du dépôt du RGAA 4.
La correction dans les serveurs de la publication du RGAA sur numerique.gouv.fr sera déployée dans un second temps.
