### ISSUE TITLE
Critère 6.2 : suppression de la définition "Ancre" dans le glossaire alors que la nouvelle note technique en fait mention

### ISSUE THREAD

**Issue by ghost** [DISIC/RGAA#101]
Suite au ticket https://github.com/DISIC/RGAA/issues/54, la définition du glossaire pour le mot "Ancre" a été supprimée. Pourtant, une note technique a été ajoutée au critère 6.2 faisant mention du mot "ancre" mais sans en donner la signification.

Cela porte à confusion pour les personnes qui mélangent "ancre" et "lien vers une ancre".

La définition du glossaire devrait être rétablie et un lien vers celle-ci devrait être mis dans la note technique du critère 6.2.

**Comment by juliemoynatPro** [comment]
Si je l'ai signalé c'est qu'il y a eu confusion par des personnes et la définition existait avant donc ça ne coûte rien de la remettre, d'où mon ticket mais bon, soit.

**Comment by acaodinsic** [comment]
Merci de vos signalements : point à discuter lors de la prochaine évolution du RGAA, fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
