### ISSUE TITLE
Critère 11.2 : le cas particulier fait référence à un test 11.9.3 qui n'existe pas

### ISSUE THREAD

**Issue by ghost** [DISIC/RGAA#102]
Dans le cas particulier du critère 11.2, on peut lire :

>Ce cas particulier s’applique également au test 11.9.3.

Or, le test 11.9.3 n'existe pas. Il me semble qu'il s'agit simplement d'une coquille et que ce devrait être 11.9.2.

**Comment by design-gouv** [comment]
Merci de votre signalement.

Le texte sera modifié : 
Ce cas particulier s’applique également au test **11.9.2**.

La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
