### ISSUE TITLE
Critère 10.11 et tests 10.11.1, 10.11.2 - formulations pas claires

### ISSUE THREAD

**Issue by acaodinsic** [DISIC/RGAA#103]
La reformulation du critère 10..11 est insuffisante en regard de WCAG 1.4.10, le principe de "présentation sans perte d'information ou fonctionnalité", n'est évoqué qu'au niveau des tests, il devrait être mentionné dès l'intitulé du critère.
 
en lien avec issue #29

**Comment by design-gouv** [comment]
Deux techniques WCAG ont été ajoutées au critère WCAG :
•	https://www.w3.org/WAI/WCAG21/Techniques/css/C34
•	https://www.w3.org/WAI/WCAG21/Techniques/css/C37
 Ces deux techniques seront ajoutées aux correspondances du critère 10.11.

L'intitulé du Critère sera clarifié voir #119

Ces corrections seront prises en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
