### ISSUE TITLE
Glossaire : Contraste - changer la valeur de seuil

### ISSUE THREAD

**Issue by acaodinsic** [DISIC/RGAA#105]
dans les formules de calcul, changer le seuil qui a été modifié de 0.03928 à 0.04045
voir w3c/wcag#1213

en lien avec issue #46

**Comment by design-gouv** [comment]
La modification n'est pas encore officialisée par WCAG.

Attendre la sortie officielle WCAG 2.2

**Comment by AlainVagner** [comment]
Ne faudrait-il pas attendre la publication d'une décision d'exécution de l'UE spécifiant une nouvelle version de la norme européenne EN 301 549 qui incluerait ce changement provenant de WCAG 2.2? 
La version de la norme actuellement en vigueur en Europe est la 3.2.1 qui se réfère à WCAG 2.1, cf la [décision d'exécution 2021/1339](https://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:32021D1339&from=EN) 
Ou bien est-ce que le RGAA sera en avance de phase sur la norme européenne ?

**Comment by design-gouv** [comment]
Effectivement, en toute rigueur, le RGAA attendra la version de la norme européenne qui se réfèrera aux WCAG 2.2.
Cependant, le RGAA doit évoluer pour se référer à la norme européenne 3.2.1 (ou ultérieure, si une décision d'exécution est actée entre temps).

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
