### ISSUE TITLE
Faire la distinction entre « nom accessible » et « nom visible » d’un élément

### ISSUE THREAD

**Issue by acaodinsic** [DISIC/RGAA#106]
Quand cela fait sens, il faudrait prendre en compte et faire la distinction entre « nom accessible » et « nom visible » d’un élément.

En lien avec issue #63 et avec issue #83

**Comment by design-gouv** [comment]
Un travail de clarification sera à effectuer globalement lors de la prochaine évolution du RGAA

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
