### ISSUE TITLE
Glossaire : "Identité sexuelle" à remplacer par "Identité de genre"

### ISSUE THREAD

**Issue by juliemoynat** [DISIC/RGAA#109]
Dans ce ticket https://github.com/DISIC/RGAA/issues/6, je (oui, mon ancien compte pro est devenu un "ghost"…) remontais des problèmes qui n'avaient pas été corrigés suite à la mise à jour du RGAA en v4.1. Les deux premiers points de [mon commentaire du 8 avril 2021](https://github.com/DISIC/RGAA/issues/6#issuecomment-815549482) ont bien été pris en compte mais pas le 3e point.
Je refais donc un ticket.

Dans le glossaire, pour l'expression **Liste des valeurs possibles pour l'attribut autocomplete**, @innoticFR a signalé que "identité sexuelle" était à remplacer par "identité de genre". Non seulement, c'est un sujet qui est largement remis en cause depuis longtemps, mais, de plus, la [documentation WCAG officielle](https://www.w3.org/TR/WCAG21/#input-purposes) dit bien "Gender identity (e.g., Female, Fa’afafine)" pour la valeur "sex" et [la spécification HTML officielle](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-sex) dit de même. Il faut donc corriger cette mauvaise traduction dans le glossaire du RGAA.

**Comment by design-gouv** [comment]
Merci pour votre signalement.

Une mise en cohérence de la **Liste des valeurs possibles pour l'attribut autocomplete**, avec les spécifications WCAG 2.1 FR sera effectuée.

La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
