### ISSUE TITLE
Critère 5.8 élements propres aux tableaux de données 

### ISSUE THREAD

**Issue by cescarment** [DISIC/RGAA#111]
Le critère 5.8 demande à vérifier l'absence d'élements propres aux tableaux de données dans un tableau de mise en forme.

La présence d'un attribut `role="presentation"` sur un tableau se propage à ces élements propres aux tableaux de données, annulant ainsi leur sémantique :
https://www.w3.org/TR/wai-aria-1.1/#presentation

D'un point de vue WCAG, il est donc à mon sens conforme d'avoir un tableau de mise en forme, qui a un `role="presentation"`, et des éléments propres aux tableaux de données.

De plus, même en l'absence d'un `role="presentation"`, la présence d'un élément `colgroup` ne me semble pas une non conformité WCAG automatique. En tout cas il n'y en a pas mention dans F46 : 
https://www.w3.org/WAI/WCAG21/Techniques/failures/F46

Et la documentation "ARIA in HTML" ne prévoit pas de rôle implicite pour cet élément : https://w3c.github.io/html-aria/#el-colgroup

Alors certes, "HTML Accessibility API Mappings" a prévu un rôle : https://w3c.github.io/html-aam/#el-colgroup 
Mais dans les faits aucun outil d'assistance à ma connaissance ne l'utilise, donc le RGAA impose une correction pour être conforme alors que c'est conforme WCAG, et pour un bénéfice utilisateur qui me semble inexistant.

**Comment by design-gouv** [comment]
Merci pour votre signalement.

L'élément colgroup sera retiré de la liste dans le test 5.8.1

La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
