### ISSUE TITLE
Critère 4.5 : Incohérence dans les tests sur l'existence d'une version alternative avec audiodescription synchronisée

### ISSUE THREAD

**Issue by juliemoynatPro** [DISIC/RGAA#112]
Dans le critère 4.1, lorsqu'on demande une version alternative avec une audiodescription synchronisée, on demande que celle-ci soit accessible via un lien ou bouton adjacent :

> Il existe une version alternative avec une audiodescription synchronisée accessible via un lien ou bouton adjacent.

Dans le critère 4.5, il n'est pas précisé comment accéder à la version alternative :

> Il existe une version alternative avec une audiodescription synchronisée.

**Comment by design-gouv** [comment]
Merci de votre signalement.

La mention « accessible via un lien ou bouton adjacent » sera ajoutée au critère 4.5.

La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
