### ISSUE TITLE
Test 1.3.6 : Incohérence entre le test, le glossaire, la méthodologie de test sur les méthodes autorisées pour le nom accessible des éléments SVG

### ISSUE THREAD

**Issue by juliemoynatPro** [DISIC/RGAA#113]
Je me permets de rouvrir un ticket en lien avec le ticket fermé #39 que @sbonaventure avait ouvert.

En effet, je me rends compte que la réponse apportée n'était pas satisfaisante donc je vais reprendre tous les éléments pour expliquer.

--- 

Nous avons **[ce test 1.3.6](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#test-1-3-6)** qui dit qu'**un `<svg>` doit avoir une alternative donnée via un élément `<title>`, un attribut `aria-label` ou un attribut `aria-labelledby`** :

> Test 1.3.6 : Pour chaque image vectorielle (balise `<svg>`) porteuse d’information, ayant une alternative textuelle, cette alternative est-elle pertinente (hors cas particuliers) ?
> - S’il est présent, le contenu de l’élément `<title>` est pertinent ;
> - S’il est présent, le contenu de l’attribut WAI-ARIA `aria-label` est pertinent ;
> - S’il est présent, le passage de texte associé via l’attribut WAI-ARIA `aria-labelledby` est pertinent.

**[Dans la méthodologie de test, pour le test 1.1.5](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/methodologie-test/#test-115)**, nous avons ce passage qui dit qu'**un `<svg>` doit avoir une alternative donnée via un attribut `aria-label` ou un attribut `aria-labelledby`** :

> Le cas échéant, vérifier que l’élément `<svg>` est pourvu au moins d’une alternative textuelle parmi les suivantes :
> - Passage de texte associé via l’attribut WAI-ARIA `aria-labelledby` ;
> - Contenu de l’attribut WAI-ARIA aria-label ;

**[Dans la méthodologie de test, pour le test 6.1.4](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/methodologie-test/#test-614)**, nous avons ce passage qui dit qu'**un `<svg>` a un nom accessible venant généralement d'un élément `<text>`** :

> Pour chaque lien SVG, vérifier que ce qui permet d’en comprendre la fonction et la destination est :
> - Soit l’intitulé du lien seul, fourni par le nom accessible de l’élément `<svg>` (résolu généralement à partir du contenu d’un élément `<text>`) ;
> - Soit le contexte du lien.

**Dans le glossaire, pour [Intitulé (ou nom accessible) de lien](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#intitule-ou-nom-accessible-de-lien) et [Lien SVG](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#lien-svg)**, nous avons ce passage qui dit qu'**on peut donner un nom accessible à un SVG via `aria-labelledby`, `aria-label`, `<title>`, `x:link:title`, `<text>`** puis un paragraphe qui explique que **seul l'élément `<text>` permet une compatibilité assurée avec tous les lecteurs d'écran à ce jour**.

> Dans le cas d’un lien SVG (version 1.1), le « nom accessible » est obtenu comme suit :
> - Passage de texte associé par l’attribut WAI-ARIA `aria-labelledby` ;
> - Sinon, contenu de l’attribut WAI-ARIA `aria-label` ;
> - Sinon, contenu de l’élément `<title>` enfant direct du lien ;
> - Sinon, contenu de l’attribut `xlink:title` ;
> - Sinon, contenu texte d’un ou plusieurs éléments `<text>`.
>
> Il faut cependant être vigilant car cet algorithme de calcul n’est pas encore pris en compte et effectif au sein des différents lecteurs d’écran. À ce jour, le support est disponible avec VoiceOver, mais incomplet ou lacunaire avec JAWS et NVDA. Si bien que le plus petit dénominateur commun sur lequel il est possible de se reposer pour fournir un intitulé au lien est l’élément `<text>`.

Enfin, dans le ticket #39, @design-gouv dit ceci :

>La référence à l’élément `<text>` signalé en note relate un cas d’utilisation qui peut se rencontrer mais qui n’est pas une bonne pratique. Il n’est donc pas répertorié parmi les tests.

---

Il n'y a absolument rien de cohérent dans tout ça. Je me suis d'abord dit que j'avais mal compris la phrase du glossaire sur l'élément `<text>` sauf que, je suis allée vérifier [un site qui répertorie des tests de compatibilité et j'y ai trouvé que l'élément `<title>` dans `<svg>` semble bien avoir des défauts de compatibilité](https://a11ysupport.io/tech/svg/title_element) (dernier test réalisé le 7 août 2021, ce qui est récent). L'élément `<text>` n'y est pas testé mais cela me laisse penser qu'il y a eu méprise dans la réponse du ticket #39 et que, peut-être, la personne qui a répondu a mélangé la compatibilité de `<title>` et celle de `<text>`.

Par conséquent, si le glossaire dit vrai et que `<text>` est le seul élément permettant de fournir un nom accessible à un `<svg>` de façon sûre, il faut modifier :

- Le test 1.3.6 pour faire figurer cette possibilité et pour préciser qu'il s'agit de la solution recommandée **ou** n'indiquer que cette possibilité ;
- La méthodologie de test pour le test 1.1.5 pour faire figurer toutes les possibilités et préciser que `<text>` est recommandé **ou** n'indiquer que cette possibilité ;
- La méthodologie de test pour le test 6.1.4 pour faire figurer toutes les possibilités en précisant que `<text>` est recommandé (si c'est la solution choisie pour les 2 points précédents) **ou** laisser tel quel.

Si le glossaire dit faux, il faut modifier le glossaire ainsi que la méthodologie de tests.

Je n'ai pas encore fait mes tests de mon côté. J'ajouterai un commentaire dans ce ticket quand j'aurais trouvé le temps de les faire (si d'autres veulent les faire, c'est avec plaisir !).

**Comment by design-gouv** [comment]
Merci de vos signalements.

Il sera ajouté l’élément <title> dans le test 1.1.5 afin d’être cohérent avec le test 1.3.6. et une modification de la méthodologie de test en conséquence.

La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
