### ISSUE TITLE
Test 10.7.1 : problème sur les propriétés CSS présentées dans la méthodologie de test pour vérifier la prise de focus

### ISSUE THREAD

**Issue by lbuffet-pro** [DISIC/RGAA#114]
Dans la méthodologie de test, il est précisé pour [le test 10.7.1](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/methodologie-test/#crit%C3%A8re-107dans-chaque-page-web-pour-chaque-%C3%A9l%C3%A9ment-recevant-le-focus-la-prise-de-focus-est-elle-visible) : 
> Pour chaque élément susceptible de recevoir le focus, vérifier que l’indication visuelle de la prise de focus est présente (propriétés outline, outline-width, outline-style, outline-color) et suffisamment contrastée (ratio de contraste égal ou supérieur à 3.0).

La liste des propriétés CSS entre parenthèses laisse entendre que l'utilisation d'autres propriétés CSS pour indiquer la prise de focus ne serait pas valide. Or, on pourrait aussi utiliser `border`, `background-color`...

**Comment by design-gouv** [comment]
Merci de votre signalement.
Toute propriété agissant sur le contour, le fond ou les 2 pourrait être utilisée.
Une reformulation sera effectuée dans la méthodologie de test :
Pour chaque élément susceptible de recevoir le focus, vérifier que l’indication visuelle de la prise de focus est présente (**en agissant sur le contour ou le fond ou les 2**) et est suffisamment contrastée (ratio de contraste égal ou supérieur à 3.0).

La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
