### ISSUE TITLE
Méthodologie de tests : thématique multimédia : la possibilité d'avoir une alternative via un bouton adjacent n'est pas présente

### ISSUE THREAD

**Issue by juliemoynatPro** [DISIC/RGAA#115]
Dans [la thématique "Multimédia"](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#topic4), les critères évoquant la possibilité d'avoir une version alternative parlent de "version alternative […] accessible via un lien ou bouton adjacent".

En revanche, [dans la méthodologie de tests](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/methodologie-test/#multim%C3%A9dia), il n'est question que de version alternative "accessible au moyen d’un lien adjacent (une URL ou une ancre)".

La méthodologie a besoin d'être mise à jour par rapport aux critères.

**Comment by design-gouv** [comment]
Merci de votre signalement.
 La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
