### ISSUE TITLE
Test 10.11.2 : coquille dans la méthodologie de test

### ISSUE THREAD

**Issue by lbuffet-pro** [DISIC/RGAA#116]
Dans la méthodologie de test [du test 10.11.2](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/methodologie-test/#test-10112) il est précisé : 

> Réduire la fenêtre d’affichage à une largeur de 256px et vérifier que les informations et les fonctionnalités restent disponibles sans aucun défilement vertical ;

Le mot "largeur" n'est pas le bon, il s'agit plutôt d'une hauteur de 256px.

**Comment by design-gouv** [comment]
Merci de votre signalement.
La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
