### ISSUE TITLE
Critères 1.6 et 1.7 : des tests permettent l'usage de longdesc qui est maintenant obsolète

### ISSUE THREAD

**Issue by juliemoynatPro** [DISIC/RGAA#117]
Les tests 1.6.1 et 1.7.1 permettent l'usage de l'attribut `longdesc` pour référencer une description longue.

L'attribut `longdesc` est [obsolète dans la spécification HTML](https://html.spec.whatwg.org/#attr-img-longdesc) (et son usage génère une erreur au validateur HTML).

Par ailleurs, la compatibilité de cet attribut avec les différents navigateurs et lecteurs d'écran n'est pas vraiment bonne. J'avais rassemblé [des tests en mai 2020 dans un tableau](https://codepen.io/juliemoynat/pen/xmXbgv). Ça a pu évoluer depuis mais je ne pense pas que ça ait évolué favorablement dans la mesure où l'attribut est maintenant obsolète.

Je pense que la prochaine version du RGAA devra considérer de retirer ces tests. La [technique WCAG H45 associée est d'ailleurs en discussion à ce sujet](https://github.com/w3c/wcag/issues/950).

**Comment by design-gouv** [comment]
Merci de votre signalement.
Avec la réserve que cette obsolescence ne vaut que pour la version de HTML en cours, mais qu’elle ne concerne pas les versions antérieures à HTML5.

Une remarque en ce sens sera ajoutée dans les notes techniques des critères concernés.
La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
