### ISSUE TITLE
Test 10.13.1 : Incohérence entre le cas particulier énoncé et la méthodologie

### ISSUE THREAD

**Issue by lbuffet-pro** [DISIC/RGAA#118]
Le cas particulier du test 10.13.1 précise ceci : 
> Lorsque le contenu additionnel ne masque ou ne remplace aucun contenu porteur d’information, le test 10.13.1 est non applicable.

Et la méthodologie de test du test 10.13.1 précise ceci : 

> Pour chaque contenu additionnel, vérifier que :
>
> Soit le contenu additionnel est positionné de façon à ce qu’il ne gêne pas la consultation des autres contenus informatifs sur lesquels il viendrait se superposer (y compris le composant d’interface qui a déclenché son apparition), quelles que soient les conditions de consultation (y compris lors de l’utilisation d’un mécanisme de zoom) ;
>
> Soit un mécanisme (au clavier) permet de faire disparaître le contenu additionnel (par exemple, la touche Echap).
>
> Si c’est le cas pour chaque contenu additionnel, le test est validé.

Du coup, en cas de contenu additionnel qui ne masque ou ne remplace aucun contenu informatif, mon test est-il non applicable ou validé ?

**Comment by design-gouv** [comment]
Il n'y a pas d'incohérence.
La méthodologie vient préciser la démarche de test : "quelles que soient les conditions de consultation, y compris lors de l'utilisation d'un mécanisme de zoom"

Aucune action envisagée.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
