### ISSUE TITLE
Critère 10.11 : Intitulé non représentatif des tests

### ISSUE THREAD

**Issue by Altrue** [DISIC/RGAA#119]
Bonjour,

Le Critère 10.11 indique :

> Pour chaque page web, les contenus peuvent-ils être présentés sans avoir recours à un défilement vertical pour une fenêtre ayant une hauteur de 256px ou à un défilement horizontal pour une fenêtre ayant une largeur de 320px (hors cas particuliers) ?

Lors d'une première lecture, la formulation ici est paradoxale : Une page web faisant la taille d'un timbre-poste en format portrait, ne devrait présenter ni défilement vertical, ni défilement horizontal ?

Bien entendu, la lecture des tests 10.11.1 et 10.11.2 clarifie ensuite cela. Il s'agit en fait de deux critères distincts et **mutuellement exclusifs** car basés sur un sens de lecture différent.

Mais cela soulève plusieurs problèmes :

1. Si les deux tests sont mutuellement exclusifs, alors l'intitulé doit être composé de deux parties et **explicitement invalider** l'une des deux parties en fonction d'une condition claire.

- Concernant l'**invalidation** : Cela n'est pas le cas ici puisque le critère d'invalidation est le sens de lecture, et aucune mention du sens de lecture n'est présente.
- Concernant la mention **explicite** de deux parties distinctes : le "ou" français étant ambigu, il ne peut pas être considéré comme satisfaisant.
- La présence de tests qui clarifient la situation n'est pas suffisante, car cela introduit un nouveau paradigme qui est que la compréhension des critères n'est possible qu'avec la compréhension des tests.. Mais si c'est le cas, pourquoi avoir un intitulé de critère ?

2. Si le critère est composé de deux parties qui sont régies par des conditions différentes, pourquoi ne pas faire deux critères ?

Si c'est par respect pour la structure du WCAG, il faudrait changer la mise en page pour utiliser les listes à puces du WCAG, qui simplifient grandement la compréhension.

3. Dans tous les cas, est-il vraiment acceptable d'avoir une description qui s'éloigne autant du WCAG ? 

Pour référence, voici la formulation du WCAG :

> Content can be presented without loss of information or functionality, and without requiring scrolling in two dimensions for:
>
>    - Vertical scrolling content at a width equivalent to 320 CSS pixels;
>    - Horizontal scrolling content at a height equivalent to 256 CSS pixels.

L'esprit de la règle est clairement d'éviter la présence d'un défilement à deux dimensions. Ou plus précisément, **il faut un défilement à une dimension maximum, qui respecte le sens de lecture**. Tout le reste, incluant le nombre exact de pixels de chaque côté, n'est qu'un garde-fou pour éviter de devoir appliquer la règle sur les cas à la marge.

-----

Je vous propose donc une reformulation du critère qui reprends les attributs principaux de celui-ci : Le **sens de lecture** et le fait d'**éviter le double défilement**.

> Critère 10.11 : Pour chaque page web, les contenus nécessitant un défilement peuvent-ils être présentés, sans perte d'information ou fonctionnalité, en n'utilisant qu'un défilement à une seule dimension, qui est en identique au le sens de lecture ?

(Tests laissés à l’identique)

Cette reformulation est proposée dans l'optique d'avoir une critique constructive, mais peut-être trouverez-vous une formulation encore plus explicite. Ou peut-être préfèrerez-vous scinder le critère en deux.

On peut d'ailleurs s'appuyer sur le critère 10.12, juste en dessous, qui est un bon exemple d'un cas où l'on a choisi d'utiliser le critère pour représenter uniquement l'esprit de la règle, tandis que les tests définissent les détails techniques (ici des balises, mais cela aurait pu être des nombre de pixels).

En vous remerciant de votre attention !

**Comment by juliemoynatPro** [comment]
En complément, voir le ticket #103 (lui-même créé suite à la fermeture du ticket #29) pour un autre problème dans la formulation de ce critère.

**Comment by Altrue** [comment]
Merci du rappel, j'avais aperçu le ticket #103 en cherchant des doublons éventuels mais j'ai oublié de l'incorporer à la suggestion de reformulation en fin d'issue. Cette suggestion a été éditée pour tenir compte de la #103.

**Comment by design-gouv** [comment]
Merci de votre signalement.

L'intitulé du critère 10.11 fera l'objet d'une reformulation pour exprimer correctement l'exclusivité.
Critère 10.11 - Pour chaque page web, les contenus peuvent-ils être présentés sans avoir recours **soit** à un défilement vertical pour une fenêtre ayant une hauteur de 256px, **soit** à un défilement horizontal pour une fenêtre ayant une largeur de 320px (hors cas particuliers) ?

WCAG 1.4.10 explique un défilement dans une unique direction pour permettre une lecture facilitée selon le sens de l'écriture de l'information. Une phrase sera ajoutée, pour l'indiquer.

La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by juliemoynatPro** [comment]
@design-gouv cette reformulation n'inclue pas la remarque du ticket #103.

Je propose :

>Critère 10.11 - Pour chaque page web, les contenus peuvent-ils être présentés **sans perte d'information ou fonctionnalité et** sans avoir recours soit à un défilement vertical pour une fenêtre ayant une hauteur de 256px, soit à un défilement horizontal pour une fenêtre ayant une largeur de 320px (hors cas particuliers) ?

**Comment by design-gouv** [comment]
Merci pour votre proposition.

Cette formulation permet effectivement de mieux exprimer la concordance du critère 10.11 du RGAA avec WCAG 1.4.10

Critère 10.11 - Pour chaque page web, les contenus peuvent-ils être présentés sans perte d'information ou de fonctionnalité et sans avoir recours soit à un défilement vertical pour une fenêtre ayant une hauteur de 256px, soit à un défilement horizontal pour une fenêtre ayant une largeur de 320px (hors cas particuliers) ?

La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
