### ISSUE TITLE
Critère 3.2: 18,5px?

### ISSUE THREAD

**Issue by OlivierNourry** [DISIC/RGAA#12]
Je ne comprends pas comment est calculée la valeur de 18,5px.
Si on se réfère à l'ancien critère, et à la valeur de 24px pour le texte sans graisse, il semble que la taille de base prise en considération est 16px (24px / 150% = 16px).
Donc suivant cette logique, pour le texte en gras, on devrait avoir 16px * 120% = 19,2 px

**Comment by kantoche** [comment]
La technique G18 (https://www.w3.org/WAI/WCAG21/Techniques/general/G18) explique l'obtention de cette valeur dans une note : 
"When evaluating this success criterion, the font size in points should be obtained from the user agent or calculated on font metrics in the way that user agents do. Point sizes are based on the CSS pt size CSS3 Values. The ratio between sizes in points and CSS pixels is 1pt = 1.333px, therefore 14pt and 18pt are equivalent to approximately 18.5px and 24px."

**Comment by OlivierNourry** [comment]
Bonjour,
Merci pour cette référence. Néanmoins, dans le glossaire, on trouve https://www.w3.org/TR/WCAG21/#dfn-large-scale précisant un mode de calcul différent, basé sur 120% de la taille de base (ou 1.2em). Or le glossaire est dans la partie normative des WCAG, pas les techniques. J'aurais donc eu tendance à partir du glossaire plutôt que d'une technique.
Toute l'ambiguïté est dans le "roughly", car en réalité, même si l'écart est faible entre la valeur exacte et son approximation, il n'est pas nul, et cela fait la différence entre plus de 19px, et moins.
Il m'aurait semblé cohérent de retenir la valeur de 19px pour ce critère (tant qu'à choisir une valeur arbitraire...).

**Comment by kantoche** [comment]
Bonjour,
Cette question de la définition de "Large text" a fait l'objet d'une longue discussion en 2016 dont voici les jalons principaux :

- https://github.com/w3c/wcag/issues/181
- https://github.com/w3c/wcag/pull/184
- https://lists.w3.org/Archives/Public/w3c-wai-gl/2016AprJun/0670.html

Le groupe de travail WCAG a donc clarifié cette définition dans les "understanding" (qui ne sont certes pas non plus normatifs) des critères de succès 1.4.3 et 1.4.6. Cette clarification correspond au contenu de la note signalée plus haut (reprise ensuite dans les techniques) : "When evaluating this success criterion, the font size in points should be obtained from the user agent or calculated on font metrics in the way that user agents do. Point sizes are based on the CSS pt size as defined in CSS3 Values. The ratio between sizes in points and CSS pixels is 1pt = 1.333px, therefore 14pt and 18pt are equivalent to approximately 18.5px and 24px."

**Comment by innoticFR** [comment]
Cette modification était effectivement très attendue et avait été soulevée dans un [ticket relatif à la précédente version](https://github.com/DISIC/rgaa_referentiel/issues/52)

Concernant les aspects normatifs, [l'équivalence pt / px est définie dans la norme CSS ](https://www.w3.org/TR/css-values-3/#absolute-lengths) : `72pt = 96px`. 

La phrase "*When evaluating this success criterion, the font size in points should be obtained from the user agent or calculated on font metrics in the way that user agents do*" indique que le point reste l'unité de référence pour l'application de ce critère, après conversion.

Il faut noter qu'on parle ici du "point" (unité d'imprimerie) qui est une unité indivisible, contrairement aux unités CSS (`px`, `pt`, ...).

En l'état `18,5px = 18,5 / 1.33 pt = 13,875pt`, arrondi selon les règles d'arrondi habituelles *(le WCAG n'ayant pas précisé de règles particulières d'arrondi)*, cela représente bien 14 points d'imprimerie, sans trop s'éloigner de `18,67px`, et cette valeur semble aller dans le sens des futures évolutions du WCAG *(même si j'aurais été d'avis d'utiliser 18,67 comme valeur, parce que c'est ce seuil qui sera testée par beaucoup d'outils automatisés)*

**Comment by alixraison** [comment]
Nous confirmons les échanges qui ont permis de lever l’incompréhension de départ.

Aucune modification n’est envisagée.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse et n'envisage pas de modification.

**Je ferme donc ce ticket qui concerne la version RGAA 4.0**

_Néanmoins, si le point donne lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure._
