### ISSUE TITLE
Critère 12.10 : les raccourcis clavier concernés ne sont pas forcément qu'à une seule touche

### ISSUE THREAD

**Issue by juliemoynatPro** [DISIC/RGAA#120]
Dans le [critère 12.10](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-12-10) du RGAA, il n'est question que de raccourcis clavier à une seule touche.

Cependant, le critère WCAG associé ([2.1.4](https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html)) n'est pas exclusif aux raccourcis clavier à une seule touche. Cela peut aussi être un raccourci clavier à deux touches dans la mesure où il n'y a pas de touche de modification utilisée. A+2 est un raccourci concerné par ce critère.

Cela a été confirmé par le W3C lors du travail de traduction des WCAG 2.1.

Le critère RGAA devrait donc être réécrit en conséquence afin de couvrir tous les cas couverts par le critère WCAG.

---

Note : le glossaire pour "[raccourci clavier](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#raccourci-clavier)" dit :

> Un moyen de déclencher une action associée à un composant de l’interface utilisateur en appuyant **sur une ou plusieurs touches**.

Cependant, cette note dans le glossaire n'est pas suffisante car elle entre en contradiction directe avec l'intitulé du critère.

**Comment by design-gouv** [comment]
La formulation du critère 12.10 reste conforme à l’énoncé et au contenu du critère WCAG 2.1.4.

Le type de raccourci donné en exemple (“A+2”) :
- fait référence à une séquence de touches et non pas à une combinaison de touches et se trouve, de fait, hors du périmètre du présent critère ;
- ne figure pas dans le critère WCAG (understanding et techniques comprises) ;
- la confirmation du W3C évoquée n’est pas sourcée et ne peut être indiquée en référence.

Le glossaire donne une définition générique de ce qu’est un raccourci clavier. Cette définition signale qu’il peut être fait recours à une ou plusieurs touches et dans ce dernier cas il s’agit de touches de modification en plus de la touche principale du raccourci. Dans la formulation du critère, la mention de raccourci est restreinte à l’usage d’une seule touche. Il n’y a donc aucune contradiction entre les formulations du critère et du glossaire, juste une différence de perspective.

Aucune modification n'est envisagée dans l'immédiat.

**Comment by acaodinsic** [comment]
Merci de vos signalements : points à discuter lors d'une prochaine évolution du RGAA.
Fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
