### ISSUE TITLE
Manque un critère pour invalider formellement un lien d'accès rapide non fonctionnel s'il ne concerne pas le contenu principal

### ISSUE THREAD

**Issue by juliemoynatPro** [DISIC/RGAA#121]
J'avais déjà remonté ce problème dans un précédent ticket mais il a été fermé sans résoudre le problème : https://github.com/DISIC/RGAA/issues/19

Le critère 12.7 permet d'invalider un lien d'accès rapide au contenu principal qui ne serait pas fonctionnel.

Le critère 12.6 permet d'invalider un lien d'accès rapide non fonctionnel si c'est une des conditions utilisée. Mais si plusieurs des solutions sont mises en place, finalement, ce serait un peu détourné d'invalider un lien d'accès rapide qui ne fonctionnerait pas.

Il faut donc un critère ou un test dédié pour tester la validité des liens d'accès rapide même si une autre condition remplissant le critère 12.6 est utilisée et fonctionnelle.

**Comment by design-gouv** [comment]
Merci pour votre signalement.

Une modification sera à envisager dans les conditions du test en précisant que les liens d’évitement ou de raccourci doivent être fonctionnels : 
•	“La zone peut être évitée par le biais d’un [lien d’évitement](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#liens-d-evitement-ou-d-acces-rapide) **fonctionnel précédant** directement la zone dans l’ordre du code source ;
•	La zone peut être atteinte par le biais d’un [lien d’accès rapide](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#liens-d-evitement-ou-d-acces-rapide) **fonctionnel** et visible ou, à défaut, visible à la prise de focus.”

Également, une clarification de la formulation du test et de ses conditions :
- En effet, pour une zone de contenu donnée (par exemple, la zone de navigation principale), la présence d’un lien d’accès rapide et la présence d’un lien d’évitement peuvent être toutes les deux requises car chacun de ces deux liens poursuit un objectif différent : le lien d’accès rapide permet de naviguer vers cette zone afin de la consulter alors que le lien d’évitement permet de passer la zone pour ne pas avoir à la consulter.
- La condition “La zone peut être évitée par le biais d’un [lien d’évitement](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#liens-d-evitement-ou-d-acces-rapide) **fonctionnel précédant** directement la zone dans l’ordre du code source” devrait être complétée par l’ajout d’un second lien d’évitement **suivant** directement la zone concernée afin de permettre la navigation au clavier dans les deux directions (tabulation avant et tabulation arrière).

Aucune modification dans l'immédiat.
Ces modifications seront mises en discussion lors de la prochaine évolution du RGAA.

**Comment by juliemoynatPro** [comment]
@design-gouv, je parle des liens d'accès rapide qui ne permettent pas d'éviter ou d'accéder au contenu principal mais à d'autres zones. S'il y a un lien d'accès rapide au pied de page et qu'il n'est pas fonctionnel, nous n'avons rien pour l'invalider si un autre test du critère 12.6 est conforme. Ce que vous envisagez ne résoudrait pas le problème.

**Comment by juliemoynatPro** [comment]
@design-gouv, je ne suis pas d'accord.

On doit respecter au moins une des conditions de ce test. Si on respecte le point 1 et qu'on a, en plus, des liens d'accès rapide au pied de page ou autre non fonctionnels, on n'a rien pour les invalider.

**Comment by design-gouv** [comment]
Les conditions doivent être vérifiées pour  **chaque zone de regroupement de contenus** présente dans plusieurs pages web

**Comment by juliemoynatPro** [comment]
Il y a marqué "au moins une de ces conditions" dans le test. On peut donc respecter la première condition sur les landmarks ARIA : par exemple, mon pied de page a un attribut `role="contentinfo"`. Et s'il y a aussi un lien d'accès rapide à ce pied de page mais non fonctionnel, alors, on fait quoi ? On fait respecter deux conditions de ce test ? Ça n'est pas logique par rapport à la façon dont le test est écrit puisqu'au moins une des conditions est bien remplie. Toute solution implémentée doit être fonctionnelle mais ce test ne permet pas de vérifier si, s'il y a plusieurs solutions implémentées, elles le sont toutes correctement.

**Comment by design-gouv** [comment]
ok, je n'ai évoqué que "_Par exemple_", mais, cela ne convient pas.

D'un point de vue "accessibilité", l'important n'est-il pas que ce soit **fonctionnel** , indépendamment de la façon de définir la zone de regroupement ? ainsi, certaines conditions ne seraient-elles pas en trop pour ce test ?

Á discuter, lors de la prochaine évolution du RGAA (_car cela impacte les résultats d'un audit sur ce critère/test_)
