### ISSUE TITLE
Environnement de test Ordinateur : mise à jour des combinaisons lecteur d'écran / navigateur 

### ISSUE THREAD

**Issue by AlainVagner** [DISIC/RGAA#127]
Pour faire suite à l'issue #13 qui concernait le RGAA 4.0, devrait-on envisager de mettre à jour l'environnement de test pour ordinateur? 
En effet, [Internet Explorer n'est plus supporté par Microsoft](https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/) depuis juin 2022.  Par ailleurs, Google Chrome, qui a des parts de marchés importantes (voir par exemple le dernier [sondage Webaim sur les lecteurs d'écrans de 2021](https://webaim.org/projects/screenreadersurvey9/)), ne fait pas partie de l'environnement de test.

(edit) Un article récent en anglais sur la [fin du support d'Internet Explorer et l'accessibilité](https://tetralogical.com/blog/2022/08/24/ie-support/) chez Tetralogical.

Proposition: faire entrer Google Chrome et Microsoft Edge dans l'environnement de test et supprimer Internet Explorer.

**Comment by design-gouv** [comment]
Merci de votre signalement.

Ces corrections seront proposées pour la prochaine évolution du RGAA.

**Comment by acaodinsic** [comment]
Merci de votre signalement.

En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 

****************************************
