### ISSUE TITLE
Critère 12.6 : "lien d'accès rapide visible à la prise de focus lors d’une tabulation" : il manque "au moins"

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#14]
Bonjour,

Dans le test 12.6.1, dans la phrase « la zone peut être atteinte par le biais d'un lien d'accès rapide visible à la prise de focus lors d’une tabulation », il semble manquer "au moins" après "à la prise de focus lors d'une tabulation" sinon, un lien d'accès rapide visible par défaut n'est pas conforme et cela n'aurait pas de sens.

C'était correct dans la [consultation](https://web.archive.org/web/20191024094311/https://evolution-rgaa.numerique.gouv.fr/participer/navigation/critere-1210-dans-chaque-page-web-les-groupes-de-liens-importants-menu-barre) donc j’imagine que c’est juste une coquille.

**Comment by innoticFR** [comment]
Il faut également supprimer les termes *"lors d'une tabulation"*, comme c'est déjà le cas dans le point 12.7

La prise de focus n'est pas limitée à un seul dispositif d'entrée, celle-ci peut être faite via des gestes tactiles ou des mouvements de la souris ("mouse-gesture"), par exemple, eye-tracking, reconnaissance de geste, navigation vocale, etc.

Dans l'idéal, il faut préférer une formulation qui privilégie la visibilité du bouton (afin de prendre en compte, notamment les interfaces tactiles). Par exemple:
> La zone peut être atteinte par le biais d’un lien d’accès rapide visible, **ou à défaut visible** à la prise de focus.

**Comment by alixraison** [comment]
Merci pour votre signalement.

●	Modification de la dernière condition du test 12.6.1 :
 “La zone peut être atteinte par le biais d’un lien d’accès rapide visible ou, à défaut, visible à la prise de focus.”

●	Modification de la troisième condition du test 12.7.2 : 
“Le lien est visible ou, à défaut, visible à la prise de focus.”

**Comment by juliemoynat-tanaguru** [comment]
Corrigé en RGAA 4.1
