### ISSUE TITLE
Critère 5.3 - cas particulier

### ISSUE THREAD

**Issue by sbonaventure** [DISIC/RGAA#16]
Le critère 5.3 mentionne un cas particulier dans son intitulé (https://github.com/DISIC/RGAA/blob/master/criteres.json#L1324) , alors qu'aucun cas particulier n'est présent en référence à ce critère.

La note de révision ne mentionne pas non plus de modification sur ce point.

Pour information, voici le cas particulier présent dans le référentiel RGAA 3.2017 : https://references.modernisation.gouv.fr/rgaa-accessibilite/cas-particuliers.html#cp-5-3

Est-ce un oubli de la note de révision, ou bien du référentiel ?

**Comment by alixraison** [comment]
Merci pour votre signalement.

La référence au cas particulier est effectivement présente dans l’énoncé du critère. Le cas particulier du RGAA 3 n’est pas pertinent puisqu’on y lit qu’un élément table pourvu d’un rôle "list" est un tableau de mise en forme, ce qui est inexact dans la mesure où il s’agit d’un changement de sémantique. En raison de son inexactitude de contenu, ce cas particulier n’a pas non plus sa place ailleurs et peut être supprimé.

•	Suppression de la mention “(hors cas particuliers)” du critère 5.3 :
 “Critère 5.3 Pour chaque tableau de mise en forme, le contenu linéarisé́ reste-t-il compréhensible ?”
