### ISSUE TITLE
Critère 7.5 : besoin de clarification dans la formulation

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#17]
Bonjour,

Si on lit le [critère de succès WCAG 4.1.3 « Status messages »](https://www.w3.org/WAI/WCAG21/Understanding/status-messages.html) et notamment les points suivants, on comprend que les messages de statut ne sont pas nécessaires dans tous les cas :

- >The intent of this Success Criterion is to make users aware of important changes in content that are not given focus, and to do so in a way that doesn't unnecessarily interrupt their work.
- > The scope of this Success Criterion is specific to changes in content that involve status messages. A status message is a defined term in WCAG. There are two main criteria that determine whether something meets the definition of a status message:
    1. >the message "provides information to the user on the success or results of an action, on the waiting state of an application, on the progress of a process, or on the existence of errors;"
    2. >the message is not delivered via a change in context.

Lorsque je lis le critère 7.5 du RGAA, je comprends que tous les messages d’erreur (par exemple) doivent être restitués via `role="alert"`.

Or, il semble que la définition de « Message de statut » dans le glossaire (passage concerné : « (il n’y a pas de changement de contexte par exemple un repositionnement du focus sur le message). ») permette de dire que si le message interrompt l’activité principale d’un utilisateur via un changement de contexte comme un repositionnement du focus sur le message, alors, ce n’est pas un message de statut et ce critère serait non applicable. Mais la définition n’est, à mon avis, pas suffisamment claire pour que l’on comprenne cela facilement.

Je propose que :

- soit on reformule le critère pour pouvoir faire apparaître une mention « si nécessaire » afin de rendre le critère plus clair directement ;
- soit on reformule la définition du glossaire pour que ce soit compris facilement que, par exemple, un message d’erreur sur lequel on vient placer le focus n’est pas concerné par ce critère.

Qu’en pensez-vous ?

**Comment by alixraison** [comment]
Un message de statut est défini dans le glossaire comme un message qui “informe l'utilisateur d'un changement de contenu dans la page sans interrompre son activité principale (il n'y a pas de changement de contexte par exemple un repositionnement du focus sur le message).”

Sa définition comprend donc bien les deux caractéristiques qui déterminent un message de statut du point de vue des WCAG : 
1.	the message "provides information to the user on the success or results of an action, on the waiting state of an application, on the progress of a process, or on the existence of errors;"
2.	the message is not delivered via a change in context.

A partir de là, il n’est pas possible de dire que le critère 7.5 considère tout message comme un message de statut.

Aucune modification n’est envisagée.

**Comment by juliemoynat-tanaguru** [comment]
Plusieurs personnes se posent des questions quant à la formulation de ce critère et de la définition du glossaire. Par conséquent, je pense qu'il est absolument nécessaire d'envisager une reformulation.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse et n'envisage pas de modification.

**Je ferme donc ce ticket qui concerne la version RGAA 4.0**

_Néanmoins, si le point donne lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure._
