### ISSUE TITLE
Test 10.4.1 : ce test devait être supprimé

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#18]
Bonjour,

D’après la consultation RGAA, le test 10.4.1 devait être supprimé : https://web.archive.org/web/20191024094311/https://evolution-rgaa.numerique.gouv.fr/participer/presentation-de-linformation/critere-104-aa-dans-chaque-page-web-le-texte-reste-t-il 

De plus, la note de révision parle de sa suppression alors qu’il est toujours bien là : 

> Mise à jour suite à la suppression des tests 10.4.1 et 10.4.2 et prise en compte des cas particuliers prévus dans le critère 1.4.4 des WCAG.

Est-il prévu que ce test soit finalement supprimé de la prochaine version mineure du RGAA 4 ?

**Comment by alixraison** [comment]
Merci pour votre signalement.

La remarque est pertinente et le test doit effectivement être supprimé, dans la mesure où la taille des unités en question change lors d’un zoom :
●	Suppression du test 10.4.1 et renumérotation des tests suivants.

**Comment by juliemoynat-tanaguru** [comment]
Pris en compte dans RGAA 4.1

En revanche, non, la taille des unités en question ne change pas si on modifie la taille par défaut dans les navigateurs (sous Windows au moins) donc ces tests n'auraient selon moi pas dus être supprimés mais ce n'était pas l'objet de ce ticket.
