### ISSUE TITLE
Critère 12.7 : comment traiter les liens d'évitement non fonctionnels qui ne concernent pas la zone de contenu principal

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#19]
Bonjour,

Le test 12.11.3 : « Dans chaque page web, chaque lien d'évitement ou d'accès rapide est-il fonctionnel (hors cas particuliers) ? » a été supprimé suite à la mise à jour de [l’entrée de glossaire « Liens d’évitement ou d’accès rapide »](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#liens-d-evitement-ou-d-acces-rapide).

Cependant, comme le test 12.7.1 « Dans chaque page web, un lien permet-il d'éviter la zone de contenu principal ou d'y accéder (hors cas particuliers) ? » ne concerne que la zone de contenu principal, comment invalider un lien d’accès rapide non fonctionnel qui ne concerne pas la zone de contenu principal ?

Je pense que le test sur le fonctionnement de chaque lien d’évitement ou d’accès rapide devrait être rétabli. En effet, un site peut très bien contenir plusieurs liens d’évitement ou d’accès rapide, spécifiquement pour des raisons d’accessibilité et, pourtant, ne pas fonctionner. Il me semble problématique de ne pas pouvoir invalider tout lien d'accès rapide ou d'évitement non fonctionnel.

Par ailleurs, la [technique WCAG G124](https://www.w3.org/WAI/WCAG21/Techniques/general/G124.html), référencée par ce critère et qui n'est pas spécifique à la zone de contenu principal, demande justement à vérifier que l’activation de chaque lien permet de déplacer le focus à la section concernée :

> Check that activating the link moves the focus to that section of the content.

Qu'en pensez-vous ?

**Comment by alixraison** [comment]
Merci pour votre signalement.

Le caractère fonctionnel d’un lien d’évitement ou d’accès rapide est rappelé dans l’entrée de glossaire “Liens d'évitement ou d'accès rapide”, note 1.

Les modifications suivantes seront effectuées :

- Ajout d’une quatrième condition au test 12.7.2 : “Le lien est fonctionnel”.
- Reformulation de la note 1 du glossaire pour préciser le caractère fonctionnel du lien : “Un lien d'évitement ou d'accès rapide fonctionnel est un lien dont l'activation permet de reprendre la lecture et la navigation clavier à partir de la cible du lien lors de l'utilisation des navigateurs et des aides techniques retenus dans l’environnement de test (ou « base de référence »).”

**Comment by juliemoynat-tanaguru** [comment]
Bonjour @alixraison,

Le problème n'est pas qu'il n'y ait pas de condition sur le fait que le lien soit fonctionnel même s'il sera effectivement appréciable que la condition soit au niveau du test et non plus du glossaire.

Le problème que je remonte, ici, est que le test 12.7.1 ne concerne que les liens d'accès rapides à la zone de contenu principal. Par conséquent, si un autre lien d'accès rapide existe et qu'il ne permet pas d'atteindre la zone de contenu principal, mais le pied de page, par exemple, et qu'il ne fonctionne pas, on ne peut pas l'invalider. Il n'existe plus de test pour invalider ça dans le RGAA 4 contrairement à ce qui existait dans le RGAA 3.

**Comment by juliemoynat-tanaguru** [comment]
Je n'ai pas obtenu de réponse à ma question initiale donc le point n'a pas été corrigé en RGAA 4.1.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** (_alias alixraison_) y donne une réponse qui est prise en compte dans la version RGAA 4.1 

**Je ferme donc ce ticket qui concerne la version RGAA 4.0**

_Néanmoins, si le point donne lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une mise à jour ultérieure._
