### ISSUE TITLE
Critère 11.10 : indication des champs obligatoires / facultatifs

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#2]
Bonjour,

Je travaille sur un projet avec de nombreux formulaires sur différentes pages. Parfois, ce sont de petits formulaires avec tous les champs obligatoires. Parfois, ce sont de grands formulaires avec la plupart des champs obligatoires et quelques-uns facultatifs.

### Point 1 :

L’équipe design a toujours préféré indiquer les champs facultatifs sur ces grands formulaires plutôt que de mettre des astérisques dans les libellés de la plupart des champs. On peut désormais le faire avec RGAA 4 via le cas particulier du critère 11.10.

Cependant, il nous paraît essentiel :

- De mettre une phrase en haut du formulaire signalant que tous les champs sont obligatoires sauf ceux indiqués comme étant facultatifs (mais sans l’attacher à chaque champ via `aria-describedby` pour éviter trop de lourdeurs dans la restitution par un lecteur d’écran) ;
- D’indiquer techniquement les champs obligatoires avec l’attribut `aria-required="true"` ou `required` pour plus de clarté (le message générique n’étant pas associé, on s’assure que les personnes aveugles puissent aussi avoir une information claire) ;
- D’indiquer visuellement et explicitement via le texte « (facultatif) » dans le libellé des champs ou la légende du groupe de champs, les champs facultatifs.

Ainsi, tout le monde aurait le même niveau d’information visuellement et techniquement. De plus, cela nous permettrait d’avoir la même gestion pour tous les formulaires, qu’il y ait des champs facultatifs ou non.

Pourtant, cela ne semble pas valide au regard du RGAA 4.
En effet, si on indique les champs obligatoires via `aria-required="true"` ou `required`, il faut :

- Soit, une indication visible dans l’étiquette du champ ;
- Soit, une indication visible dans le passage de texte associé au champ (donc, via `aria-describedby` ici, ce qui doublerait l’information donnée aux lecteurs d’écran).

### Point 2 : 

De même, si l’on mettait une phrase en début de formulaire « Tous les champs sont obligatoires », et qu’on mettait un attribut `aria-required="true"` ou `required`, il faudrait l’associer à chaque champ via `aria-describedby`. Ce serait donc, là aussi, redondant.

On ne devrait pas avoir besoin d'attacher cette phrase à chaque champ.

Cela me semble vraiment lourd pour une personne utilisant un lecteur d’écran et, il ne me semble pas que ces deux pratiques (point 1 et point 2) seraient invalidées avec un audit WCAG.

Là, cela nous obligerait finalement à mettre des astérisques partout pour éviter l’effet de redondance alors que c’est précisément ce qu’on voudrait pouvoir éviter dans le cas présent.

### Point 3 : 

Par ailleurs, je remarque que la technique WCAG G184 n’a pas été incluse dans ce critère 11.10 du RGAA 4. On parle de « préalablement à la validation du formulaire » sans jamais évoquer le positionnement des messages génériques (« tous les champs sont obligatoires », par exemple) qui devraient être en haut du formulaire.

---

Je ne comprends pas trop pourquoi ces tests ont été écrits de cette façon. Est-ce moi qui comprend les tests de travers ? 

À ce jour, j'ai besoin de savoir si le RGAA 4 va être modifié pour que les 2 premiers points que j'ai évoqué puissent être valides au RGAA par la suite. Ainsi, cela nous aiguillera sur les pratiques à mettre en place, même si, pour l'instant, ce n'est pas valide avec le RGAA.

En vous remerciant

**Comment by innoticFR** [comment]
La formulation de ces différents critères est très fastidieuse, et effectivement laisse pas mal d'interrogations...

Le test 11.10.1 oppose, par exemple, la présence d'un attribut `required` (ou `aria-required`) et une indication visuelle de champ obligatoire non liée programmatiquement, ce qui n'aide pas l'intention portée par les critères [3.3.1: Error Identification](https://www.w3.org/WAI/WCAG21/Understanding/error-identification.html), [3.3.2: Labels or Instructions](https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html) et [3.3.3 Error Suggestion](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-suggestions.html)

Ces tests pourraient être réorganisés d'une manière aidant mieux à la compréhension. Par exemple:

> Test 1. Les [indications du caractère obligatoire, du type et/ou du format de données](https://www.w3.org/WAI/WCAG21/Understanding/labels-or-instructions.html) de la saisie des champs doivent vérifier au moins une de ces conditions (sauf cas particulier) :
> - [être visibles en début de formulaire,](https://www.w3.org/WAI/WCAG21/Techniques/general/G184)
> - [être visibles dans l'étiquette associée au champ](https://www.w3.org/WAI/WCAG21/Techniques/html/H90)
> - [être associées programmatiquement au champ ](https://www.w3.org/TR/WCAG20-TECHS/ARIA1.html)
>
> *Cas particulier : formulaire à champ unique*
>
> *Note : Il est également possible de n'indiquer que les champs facultatifs*
>
> Test 2. Les champs obligatoires doivent posséder l'attribut `required` et, à défaut,
> si cet attribut n'est pas disponible, l'attribut `aria-required="true"`
>
> Test 3. Les [indications et descriptions d'erreurs](https://www.w3.org/WAI/WCAG21/Understanding/error-identification) correspondant aux données absentes ou erronées doivent respecter, au moins, une de ces conditions:
> - [être visibles en début de formulaire,](https://www.w3.org/WAI/WCAG21/Techniques/general/G83)
> - [être visibles dans l'étiquette associée au champ](https://www.w3.org/WAI/WCAG21/Techniques/html/H90)
> - [être associées programmatiquement au champ ](https://www.w3.org/WAI/WCAG21/Understanding/error-suggestion.html) 
>
> Test 4. Les champs possédant des  données absentes ou erronées doivent vérifier, au moins, d'une de ces conditions:
> - générer [une erreur de contrainte du navigateur](https://developer.mozilla.org/fr/docs/Web/Guide/HTML/HTML5/Constraint_validation)
> - disposer de l'attribut `aria-invalid="true"`

Dans cet exemple, les tests 2 et 4 s'assurent que les technologies d'assistance pourront identifier les champs requis (= `aria-required`) et en erreur (=`aria-invalid`).

**Comment by innoticFR** [comment]
Ticket lié: https://github.com/DISIC/RGAA/issues/7

**Comment by alixraison** [comment]
Merci pour votre signalement.

Le cas soumis prend le contrepied de ce qui se pratique habituellement ; la logique exprimée paraît bonne, quoique la mise en œuvre puisse sembler plus problématique du point de vue du handicap cognitif (inversion d’une consigne habituelle, précision du caractère facultatif au niveau du groupement de champs). Mais de ces différents points de vue, le RGAA comme les WCAG n’ont pas prévu ce genre de cas et il n’est donc pas non valide.

Toutefois, ce cas d’usage sera ajouté dans une note technique au critère 11.10 : 
“Note technique
Dans un long formulaire dont la majorité des champs sont obligatoires, on pourrait constater que ce sont les quelques champs restés facultatifs qui sont explicitement signalés comme tels. Dans ce cas, il faudrait s’assurer que : 
1.	Un message précise visuellement en haut de formulaire que “tous les champs sont obligatoires sauf ceux indiqués comme étant facultatifs” ;
2.	Une mention “facultatif” est présente visuellement dans le libellé des champs facultatifs ou dans la légende d’un groupe de champs facultatifs ;
3.	Un attribut required ou aria-required=”true” reste associé à chaque champ qui n’est pas concerné par ce caractère facultatif.”

Concernant la technique G184, le RGAA considère tout à fait la possibilité d’indiquer visuellement par un message en haut de formulaire que “tous les champs du formulaire sont obligatoires” sans avoir besoin de le lier dans le code à chacun des champs. C’est l’objet de la première condition du test 11.10.1 : 
“Une indication de champ obligatoire est visible et permet d'identifier nommément le champ concerné préalablement à la validation du formulaire.”
Ce point est ensuite précisé dans la note de l’entrée de glossaire “Indication de format obligatoire" : 
"Dans le cas où cette indication n'est pas réalisée de manière textuelle explicite (icône, *, !,...) l'explication de la signification de cette indication doit être visible et dans l'ordre du code source se situer avant la première utilisation de l'indication.”

Une amélioration de la formulation sera envisagée ultérieurement.

**Comment by juliemoynat-tanaguru** [comment]
@design-gouv Merci pour l'ajout de la note technique en RGAA 4.1.

Il me reste des questions : 

- Au test 11.10.1, considère-t-on donc que la phrase "Tous les champs sont obligatoires" permet d'identifier nommément les champs concernés ? La formulation ne me semble vraiment pas explicite pour ce cas de figure.
- Si on entre dans le cas de figure de la note technique, dans ce cas, le test 11.10.2 ne peut être que non applicable. Ne faudrait-il pas le préciser ? À moins qu'il faille ajouter une condition quant au fait que les champs facultatifs doivent être indiqués visuellement ?

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans la version RGAA 4.1 et précise : _"Une amélioration de la formulation sera envisagée ultérieurement."_

**Je ferme donc ce ticket** qui concerne la version RGAA 4.0

_Néanmoins, si le point donne lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées dans "l'amélioration envisagée ultérieurement."_
