### ISSUE TITLE
Suppression du test 9.1.1 du RGAA 3 et nécessité du h1 selon le contexte

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#20]
Bonjour,

Le test vérifiant la présence d'un titre h1 n'existe plus :

> Test 9.1.1 : Dans chaque page web, y a-t-il un titre de niveau 1 (balise h1 ou balise possédant un rôle ARIA "heading" associé à une propriété aria-level="1") ?

Lors de la consultation, une question sur l'application du test qui demande une pertinence de la hiérarchie a été posée.

La réponse apportée côté DINSIC était : 

> Bonjour, la suppression de 9.1.1 permet de ne plus pénaliser une page web pour laquelle l'utilisation de titres n'offrirait pas d'intérêt et donc où serait absent au moins un titre de niveau de 1. Néanmoins, pour les pages qui utilisent une hiérarchie de titres, la présence d'au moins un titre de niveau 1 reste nécessaire.

Cependant, ce point n'apparaît ni dans le critère ni dans la note technique, ni dans le glossaire. 

Pourrait-il être précisé dans un de ces endroits afin que ce soit connu de tout le monde ?

**Comment by alixraison** [comment]
Merci pour votre signalement.

Cette remarque concerne la question d’une stricte hiérarchie entre les niveaux de titre et la nécessité sous-jacente d’avoir un titre de niveau 1 (h1) pour débuter une hiérarchie de titres.

La mise au point effectuée par un article récent : https://developer.paciellogroup.com/blog/2020/03/heading-off-confusion-when-do-headings-fail-wcag/ rappelle que le WCAG n’impose aucunement la présence d’un titre h1 pour valider la cohérence d’une hiérarchie de titres. 

Le RGAA considère que :
La présence d'au moins un titre de niveau 1 n’est plus une nécessité en tant que telle puisque des niveaux de titre peuvent être omis tant que la hiérarchie globale des titres reste cohérente. Cela reste néanmoins une bonne pratique.

Dans la note technique du critère 9.1, suppression du second paragraphe “Bien que la spécification HTML5 autorise l'utilisation exclusive de titres de niveau 1 (h1), le manque de support des technologies d'assistance oblige à utiliser une hiérarchie de titres pertinente.” qui fait référence à une discussion datée n’ayant plus d’intérêt dans le contexte actuel 

Voir la réponse associée au ticket #51 concernant l’entrée de glossaire Titres.

**Comment by juliemoynat-tanaguru** [comment]
Ok. Ce point est regrettable mais soit, c'est conforme aux WCAG…
