### ISSUE TITLE
Suppression du test 9.1.3 du RGAA 3 – Incidence sur la référence WCAG H69 à déplacer au 12.6

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#21]
Bonjour,

Le test demandant la mise en place de titres lorsque nécessaire à la structure de l’information a été supprimé :

> Test 9.1.3 : Dans chaque page web, chaque titre (balise h ou balise possédant un rôle ARIA "heading" associé à une propriété aria-level) nécessaire à la structure de l'information est-il présent ?

La raison est : 

> Condition non présente dans les WCAG et non nécessaire si une autre technique que l’utilisation des balises <hx> est mise en place pour satisfaire le contournement des blocs de contenu (critère WCAG 2.4.1 Bypass Block).

Par conséquent, la [technique WCAG H69](https://www.w3.org/WAI/WCAG21/Techniques/html/H69.html) référencée sur ce critère n’est plus traitée dans le critère 9.1 du RGAA 4 mais dans le critère 12.6 où elle n’est pas référencée à ce jour.

Pour plus de clarté, la technique WCAG H69 devrait, il me semble, être retirée des références pour le critère 9.1 et ajoutée aux références pour le critère 12.6.

**Comment by alixraison** [comment]
Merci pour votre signalement.

La remarque est pertinente :
●	Suppression de la technique WCAG H69 des références du critère 9.1 ;
●	Ajout de la technique WCAG H69 aux références du critère 12.6.

**Comment by juliemoynat-tanaguru** [comment]
Pris en compte dans RGAA 4.1
