### ISSUE TITLE
Critère 1.6 et attribut aria-describedby possible ou pas possible : informations contradictoires

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#22]
Bonjour,

Les tests 1.6.4 (bouton `<input type="image">`), 1.6.5 (`<svg>`), 1.6.10 (`role="img"`) permettent comme condition possible d’utiliser l’attribut `aria-describedby` pour associer à une image, un passage de texte faisant office de description détaillée.

Par ailleurs, le test 1.6.9 évoque la possible utilisation de l’attribut `aria-describedby` pour associer une description détaillée à tous les types d’image alors que les autres tests ne le permettent pas pour tous les types d’image.

Pourtant, la note technique indique :

> L'utilisation de l'attribut WAI-ARIA aria-describedby n'est pas possible pour lier une image à sa description détaillée par manque de support des technologies d'assistance.

Par conséquent, que faire ? L’utilisation d’`aria-describedby` est-elle possible ou non ? Les informations sont incohérentes entre elles. Peut-être faudrait-il reformuler la note technique pour ne pas dire que ce n’est « pas possible » mais que c’est déconseillé ?

J’ai essayé de regarder ce qui avait été dit lors de la consultation mais la page du critère 1.6 n’a pas été indexée par la Wayback Machine…

**Comment by alixraison** [comment]
Merci pour votre signalement.

Remplacement du deuxième paragraphe de la note technique par : 
“L'utilisation de l'attribut WAI-ARIA aria-describedby n'est pas recommandée pour lier une image (img, object, embed, canvas) à sa description détaillée, par manque de support des technologies d'assistance. Néanmoins, lorsqu’il est utilisé il devra nécessairement faire référence à l’id de la zone contenant la description détaillée.”

Un test du support pourra être envisagé ultérieurement lors d’une évolution majeure du RGAA.

**Comment by juliemoynat-tanaguru** [comment]
Pris en compte dans RGAA 4.1
