### ISSUE TITLE
Note de révision : il manque le critère 10.1

### ISSUE THREAD

**Issue by ghost** [DISIC/RGAA#24]
Bonjour,

Dans la [note de révision sur le RGAA 4](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/notes-revision/#contenu), il n'est pas fait mention de la modification du critère 10.1. Pourtant, le mot "généré" a été ajouté à l'expression "code source" des tests 10.1.1 et 10.1.2.

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.

**Comment by juliemoynat-tanaguru** [comment]
La note de révision n'a pas été mise à jour.

**Comment by design-gouv** [comment]
Merci de votre signalement.
La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
