### ISSUE TITLE
Test 11.1.1 : bouton adjacent et possibilité d'utiliser un label caché non présente

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#25]
Bonjour,

Dans le test 11.1.1, la phrase suivante me pose question :

> Un bouton adjacent au champ de formulaire lui fournit une étiquette visible et un attribut WAI-ARIA aria-label, aria-labelledby ou title lui fournit un nom accessible.

En effet, on demande qu'en cas de bouton adjacent fournissant une étiquette visible, le champ ait quand même une étiquette "technique" (`aria-label`, `aria-labelledby` ou `title`). Pourquoi la possibilité d'utiliser un `<label>` masqué de façon à être accessible aux technologies d'assistance n'est-elle pas présente ?

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de la cinquième condition du test 11.1.1 :
“Un bouton adjacent au champ de formulaire lui fournit une étiquette visible et un élément <label> visuellement caché ou un attribut WAI-ARIA aria-label, aria-labelledby ou title lui fournit un nom accessible.”

**Comment by juliemoynat-tanaguru** [comment]
Corrigé en RGAA 4.1
