### ISSUE TITLE
Test 11.4.3 : incohérence avec la demande que l'étiquette soit au-dessus des champs radio et checkbox

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#26]
Bonjour,

Je remarque qu'il y a un problème dans l'écriture du test 11.4.3. Je cite :

>  Test 11.4.3 : Chaque étiquette accolée à un champ de type checkbox ou radio ou à une balise ayant un attribut WAI-ARIA role="checkbox", role="radio" ou role="switch", vérifie-t-elle ces conditions (hors cas particuliers) ?

- >L’étiquette est visuellement accolée immédiatement au-dessus ou à droite du champ de formulaire lorsque le sens de lecture de la langue de l’étiquette est de gauche à droite.

- >L’étiquette est visuellement accolée immédiatement au-dessus ou à gauche du champ de formulaire lorsque le sens de lecture de la langue de l’étiquette est de droite à gauche.

Je vais parler uniquement du sens de lecture de gauche à droite pour être plus claire.

Il est dit que, pour les champs de type checkbox ou radio, l'étiquette doit être visuellement accolée immédiatement **au-dessus ou à droite** du champ de formulaire. Cela n'a pas de sens que l'étiquette soit au-dessus d'un champ radio ou checkbox. Elle pourrait être en-dessous mais sûrement pas au-dessus. Il s'agit manifestement d'une erreur ici.

D'ailleurs, la [technique G162](https://www.w3.org/WAI/WCAG21/Techniques/general/G162.html) des WCAG dit dans la procédure de tests : 

>If the form field is a checkbox or radio button, check that the label is immediately after the field.

Autrement dit, si l'étiquette est au-dessus du champ, elle n'est pas immédiatement après le champ.

Par ailleurs, quand on regarde les exemples donnés dans la technique, on voit qu'il n'y en a pas avec un champ radio ou checkbox au-dessus de son étiquette (ou inversement). Il est même dit que ces champs ont une largeur uniforme et que de les avoir en premier permettrait un alignement vertical de ces champs. Je cite : 

>Checkboxes and radio buttons have a uniform width while their labels often do not. Having the radio button or checkbox first therefore allows both the buttons and the labels to line up vertically. 

Ainsi, placer les étiquettes des radio et checkbox en-dessous de leur champ serait-il bien approprié selon cette technique ? Serait-ce bien un usage approprié pour les utilisateurs et utilisatrices ? Je ne crois pas avoir déjà vu cet usage.

Ne faudrait-il pas tout simplement demander que les champs radio et checkbox aient toujours leur étiquette placée à droite du champ ?

**Comment by innoticFR** [comment]
Je confirme que la [technique H44](https://www.w3.org/WAI/WCAG21/Techniques/html/H44.html) indique également:

> Note that the label is positioned after input elements of type="checkbox" and type="radio".

puis plus loin:

> For all input elements of type `checkbox` or `radio` in the Web page::
>
> Check that there is a `label` element that identifies the purpose of the control **after** the input element
> Check that the `for` attribute of the `label` element matches the `id` of the input element
> Check that the `label` element is visible.

---

Toutefois, je conçois que dans un affichage sous forme de tableau de données, il arrive fréquemment que la première colonne possède une case à cocher pour sélectionner une ligne entière, et que l'intitulé de la colonne indique par exemple "Sélectionner", mais dans ce cas là ce n'est pas "immédiatement au dessus" et le recours à l'attribut `title` est suggéré (utile pour les lecteurs d'écran notamment).

Voir par exemple la technique H65 du WCAG [Example 4: A data table of form controls](https://www.w3.org/TR/WCAG20-TECHS/H65.html)

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de la formulation du test :
“visuellement accolée immédiatement au-dessous ou à droite du champ”.

Modification dans les deux conditions du test 11.4.3 de l’occurrence “au-dessus” par “au-dessous”.

**Comment by juliemoynat-tanaguru** [comment]
Correction OK dans version 4.1
