### ISSUE TITLE
Critère 11.12: faille logique pour les formulaires à 1 étape

### ISSUE THREAD

**Issue by OlivierNourry** [DISIC/RGAA#27]
Dans les conditions des tests, le cas des formulaires à une étape n'est pas traité explicitement, ce qui fait qu'en appliquant les tests à la lettre, un tel formulaire se trouve NC s'il ne répond ni à la condition 1 ni à la 3 du test 11.12.1. En effet il est NA pour la condition 2, qui ne cible que les formulaires à plusieurs étapes.

Or un formulaire à une page répond à l'exigence d'accessibilité. Cf [G98](https://www.w3.org/WAI/WCAG21/Techniques/general/G98): 

> On a simple, 1-page form this is easy because the user can review the form before submitting.

**Comment by alixraison** [comment]
Logiquement, un formulaire à étapes contient au moins deux étapes. Un formulaire qui ne contiendrait qu’une “seule étape” est un simple formulaire dont l’utilisateur a donc la possibilité de vérifier directement les données saisies avant soumission. Merci de préciser votre question, en donnant si possible un exemple.

Aucune modification n’est envisagée.
