### ISSUE TITLE
Glossaire: référence à un critère supprimé (6.4)

### ISSUE THREAD

**Issue by OlivierNourry** [DISIC/RGAA#28]
A l'entrée: https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#intitule-ou-nom-accessible-de-lien 

> Note 4 : lorsqu’un lien ne comporte aucun contenu (à l’exception des ancres), il sera non conforme au regard du critère 10.2 et du critère 6.4.

Or le critère 6.4 a été supprimé (par ailleurs je présume que cette note fait référence au critère sur les liens vides, numéroté 6.2 dans le RGAA3, et 6.5 dans le RGAA3).

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.
