### ISSUE TITLE
Critère 10.11: formulation incomplète et incorrecte

### ISSUE THREAD

**Issue by OlivierNourry** [DISIC/RGAA#29]
> Critère 10.11. Pour chaque page web, les contenus peuvent-ils être présentés sans avoir recours à la fois à un défilement vertical pour une fenêtre ayant une hauteur de 256px ou une largeur de 320px (hors cas particuliers) ?

L'expression "à la fois", à cet endroit de la phrase, suggère que deux caractéristiques devront être absentes pour valider le critère. La première est le défilement vertical, mais il n'y a pas de seconde caractéristique.

De fait, il n'est fait mention que du défilement vertical (dont l'absence est souhaitable pour un sens de lecture vertical uniquement). Puisque le sens de lecture horizontal est invoqué (au travers de la condition de largeur de fenêtre), il aurait fallu également faire mention du défilement horizontal dans le critère.

Suggestion: pour éviter toute circonvolution préjudiciable à la compréhension, séparer le critère en 2, un pour le sens de lecture horizontal (le nôtre) et un pour le vertical.

Si problème insurmontable de renumérotation: trouver une formulation générique qui fonctionne indépendamment du sens de lecture, et détailler via les tests.

**Comment by juliemoynat-tanaguru** [comment]
Ce sujet avait été discuté sur la liste RGAA dont l'archive du message est ici : https://framalistes.org/sympa/arc/rgaa/2019-10/msg00036.html

Bénédicte avait donné une formulation corrigée (mais non disponible en ligne pour le moment) : 

>Critère 10.11. Pour chaque page web, les contenus peuvent-ils être présentés sans avoir recours à un défilement vertical pour une fenêtre ayant une hauteur de 256px ou à un défilement horizontal pour une fenêtre ayant une largeur de 320px  (hors cas particuliers) ?

**Comment by OlivierNourry** [comment]
Merci pour cette précision. En effet cette formulation est plus claire.
Pour les administrateurs du dépôt: merci de vérifier dans les archives de cette liste (fermée par définition) la présence d’autres remontées susceptibles d’être converties en issues sur ce dépôt.

**Comment by juliemoynat-tanaguru** [comment]
En fait, après avoir rencontré un cas d'usage, je me rends compte que même la reformulation n'est pas correcte par rapport au critère WCAG.

[WCAG 1.4.10](https://www.w3.org/TR/WCAG21/#reflow) dit : 

> Content can be presented without loss of information or functionality, and without requiring scrolling in two dimensions for:
>
>- Vertical scrolling content at a width equivalent to 320 CSS pixels;
>- Horizontal scrolling content at a height equivalent to 256 CSS pixels.

Autrement dit, le contenu peut être présenté sans perte d'information ou fonctionnalité, **et** sans recourir à un défilement en deux dimensions.

Dans le RGAA, on demande juste que le contenu à 320px de large n'ait pas un défilement horizontal (et le contenu à 256px de haut n'ait pas un défilement vertical). Or, il manque un point essentiel : il ne doit pas y avoir de perte de contenu ou fonctionnalité.

Par exemple, je suis sur un site où j'ai un composant (mettons une vidéo) qui n'est pas gérée correctement en responsive donc on aurait normalement un défilement horizontal. Mais, il se trouve qu'une propriété CSS `overflow: hidden;` masque le contenu qui dépasse du conteneur principal. Par conséquent, il y a une perte de contenu mais on ne peut pas l'invalider via le RGAA alors que ce serait invalidé avec le critère WCAG.

**Comment by alixraison** [comment]
Merci pour votre reformulation.

Modification de l’intitulé du critère :
“Critère 10.11. Pour chaque page web, les contenus peuvent-ils être présentés sans avoir recours à un défilement vertical pour une fenêtre ayant une hauteur de 256px ou à un défilement horizontal pour une fenêtre ayant une largeur de 320px (hors cas particuliers) ?”

La nécessité qu’il ne doive pas y avoir de perte de contenu ou fonctionnalité, apparaît clairement au niveau de chacun des deux tests où il est précisé que “l'ensemble des informations et des fonctionnalités” doivent rester disponibles.

**Comment by juliemoynat-tanaguru** [comment]
@design-gouv, je ne suis pas d'accord avec le postulat que les tests sont clairs car il est écrit "sont-elles disponibles sans aucun défilement horizontal" ce qui ne veut pas dire "sont-elles disponibles sans défilement horizontal ni perte de contenu ou fonctionnalité" mais juste que c'est disponible sans défilement horizontal.

D'ailleurs, on vient encore de se poser la question en interne. Par conséquent, la formulation des tests n'est pas claire et ne permet pas, en l'état, de dire qu'elle est conforme au critère WCAG.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

design-gouv y donne une réponse et mentionne la modification apportée dans la version 4.1 du RGAA.

Je ferme donc ce ticket qui concerne l'intitulé du critère dans la version RGAA 4.0

Néanmoins, pour la version RGAA 4.1,  le point de juliemoynat-tanaguru adresse en complément la formulation des tests du dit critère. Il convient d'ouvrir un nouveau ticket pour la version 4.1 avec une référence liée à ce ticket, pour que le point puisse être analysé lors de la prochaine amélioration ultérieure.
