### ISSUE TITLE
Note de révision: erreurs d'écriture HTML (Tests 11.1.1 et 11.1.2)

### ISSUE THREAD

**Issue by OlivierNourry** [DISIC/RGAA#30]
Le code généré est:
```html
<p> Référence directe à la balise <label>. &lt;/p&gt; </label></p>
```

Ce qui s'affiche:
Référence directe à la balise
. &lt;/p&gt;

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.
