### ISSUE TITLE
Test 12.7.1 : pourquoi permettre un lien pour éviter la zone de contenu principal alors que le but est d'y accéder rapidement ?

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#31]
Bonjour,

Le [test 12.7.1](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#test-12-7-1) permet de créer un lien pour éviter la zone de contenu principal aussi bien qu'un lien pour y accéder.

>Test 12.7.1 : Dans chaque page web, un lien permet-il d’éviter la zone de contenu principal ou d’y accéder (hors cas particuliers) ?

Le but est normalement d'accélérer la navigation clavier vers les zones importantes. Aussi, dans un site web, si un lien d'évitement de la zone de contenu principal (donc, finalement, un lien d'accès rapide au pied de page) a été créé, cela ne pourra pas être invalidé alors qu'il aurait été plus pertinent d'avoir un lien d'accès rapide vers la zone de contenu principal.

Dans les WCAG, il semble que "skip link" soit utilisé de façon assez générique pour signifier l'un ou l'autre. Cependant, la [technique G1](https://www.w3.org/WAI/WCAG21/Techniques/general/G1.html) est assez claire : 

>Adding a link at the top of each page that goes directly to the main content area

On demande un lien pour aller à la zone de contenu principal et non pas pour l'éviter.

Cette écriture était déjà présente dans le RGAA 3 et donc déjà problématique.

Il me semble qu'on devrait demander un lien d'évitement ou d'accès rapide vers la zone de contenu principal (un lien d’évitement de l'en-tête permettrait finalement d'accéder au contenu principal) ou tout simplement un lien d'accès rapide vers la zone de contenu principal.

Qu'en pensez-vous ?

**Comment by alixraison** [comment]
La formulation actuelle reste en conformité avec le WCAG, même si le fait de n’avoir qu’un lien d'évitement sans lien d'accès rapide n’est effectivement pas très pertinent.

Aucune modification n’est envisagée.

**Comment by juliemoynat-tanaguru** [comment]
Je ne suis pas d'accord. Cela n'a pas de sens de permettre à un site d'avoir un lien pour éviter la zone de contenu principal s'il n'y en a pas pour y accéder.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse et n'envisage pas de modification.

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
