### ISSUE TITLE
Critère 12.7 : 404 sur le lien vers la correspondance WCAG SCR28

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#32]
Dans les correspondances WCAG du [critère 12.7](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-12-7), le lien vers la correspondance WCAG "SCR28" renvoie vers une page 404.

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.

**Comment by juliemoynat-tanaguru** [comment]
Corrigé en RGAA 4.1
