### ISSUE TITLE
Glossaire : définitions non liées aux critères et tests

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#33]
Bonjour,

Étant donné que le glossaire contient un certain nombre d'informations permettant de définir le statut conforme, non conforme ou non applicable de certains tests, j'ai vérifié que chaque définition présente dans le glossaire était bien associée à au moins un critère ou test.

Il semble que certaines définitions n'aient plus lieu d'être et d'autres n'ont pas été liées (oubli). En voici la liste :

1. **Accéder à chaque page de la collection de pages** : le RGAA 4 ne parle plus de collection de pages donc cette définition devrait sans doute être supprimée
2. **Alerte** : ce mot n'est pas utilisé dans les critères et tests
3. **Alternative à une image SVG** : devrait sûrement être supprimée car cela n'est pas cohérent avec la définition "[Alternative textuelle (image)](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#alternative-textuelle-image)"
4. **Ambigu pour tout le monde** : peut être lié aux critères et tests
5. **Champs de même nature** : modifié en RGAA 4 - peut être lié aux critères et tests
6. **Contrôle de saisie (formulaire)** : modifié en RGAA 4 -  peut être lié aux critères et tests
7. **Élément graphique** : modifié en RGAA 4 -  peut être lié aux critères et tests
8. **Formulaire** : modifié en RGAA 4 -  peut être lié aux critères et tests
9. **Indication de format obligatoire** : modifié en RGAA 4 -  peut être lié aux critères et tests
10. **Indication du type de données et/ou de format** : modifié en RGAA 4 -  peut être lié aux critères et tests
11. **Image texte objet** : peut être lié aux critères et tests
12. **Items de même nature des listes de choix** : peut être lié aux critères et tests
13. **Légende d'image** : peut être lié aux critères et tests
14. **Liens identiques** : devait être supprimé en RGAA 4 d'après la note de révision
15. **Liste des valeurs possibles pour l'attribut autocomplete** : modifié en RGAA 4 -  peut être lié aux critères et tests
16. **Modifier ou annuler les données et les actions effectués** : modifié en RGAA 4 -  peut être lié aux critères et tests
17. **Motif de conception** : modifié en RGAA 4 + lié dans le glossaire à la définition "Composant d'interface" mais pas dans les critères et tests
18. **Pertinence (information autrement que par la couleur)** : devrait sûrement être supprimée puisque la définition "[Information (donnée par la couleur)](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#information-donnee-par-la-couleur)" a été mise à jour
19. **Résumé (de tableau)** : peut être lié aux critères et tests
20. **Si nécessaire (texte visible en complément de l'attribut aria-label ou aria-labelledby)** : date du [test 11.1.4 du RGAA 3](https://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#test-11-1-4) qui a été supprimé donc ce n'est sans doute pas une définition à conserver
21. **Structure du document** : peut être lié aux critères et tests
22. **Titre de cadre** : modifié en RGAA 4 -  peut être lié aux critères et tests
23. **Type et format de données** : peut être lié aux critères et tests
24. **Zone cliquable** : peut être lié aux critères et tests

Il est important que chaque définition soit bien associée à chaque critère ou test concerné afin que l'on sache à quels tests appliquer des invalidités lorsqu'il y en a correspondant aux règles présentes dans le glossaire.

Pouvez-vous éclaircir des points ?

**Comment by innoticFR** [comment]
A noter que le lien "Résumé" du critère 5.1 (signalé ici : https://github.com/DISIC/RGAA/issues/5) qui est le seul lien non fonctionnel vers la page glossaire depuis la page critère devrait pointer vers "Résumé (de tableau)" indiqué au point 19.

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans la version RGAA 4.1

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
