### ISSUE TITLE
Glossaire : entrée "Bouton (formulaire)" : erreur dans le critère cité

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#34]
Bonjour,

Dans le glossaire, pour la définition ["Bouton (formulaire)"](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#bouton-formulaire), il est dit : 

> Par ailleurs, un « nom accessible » sera considéré comme non-pertinent s’il ne reprend pas le texte visible du bouton. Par exemple : `<button aria-label="confirmer la saisie">valider la saisie</button>` sera considéré comme non conforme au critère 11.2.

En réalité, ce sera non conforme au critère 11.9, test 11.9.2.

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.

**Comment by juliemoynat-tanaguru** [comment]
Corrigé en RGAA 4.1
