### ISSUE TITLE
Glossaire : entrée "Contrôle de la consultation (d'un média temporel)" : doublon de texte et liste mal structurée

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#35]
Bonjour,

Dans la définition "[Contrôle de la consultation (d'un média temporel)](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#controle-de-la-consultation-d-un-media-temporel)" du glossaire, on a une liste HTML très bizarrement structurée avec un doublon de la phrase "Liste des fonctionnalités obligatoires de contrôle de la consultation&nbsp;:".

Voici le code initial :

```
<ul>
    <li><p>Liste des fonctionnalités obligatoires de contrôle de la consultation&nbsp;:</p></li>
    <li style="list-style: none;"> 
        <ul> 
            <li><p>Liste des fonctionnalités obligatoires de contrôle de la consultation&nbsp;:</p> </li> 
            <li><p>L’objet multimédia doit toujours avoir les fonctionnalités suivantes, au minimum&nbsp;: lecture, pause ou stop;</p> </li> 
            <li><p>Si l’objet multimédia a du son, il doit avoir une fonctionnalité d’activation / désactivation du son;</p> </li> 
            <li><p>Si l’objet multimédia a des sous-titres, il doit avoir une fonctionnalité de contrôle de l’apparition/disparition des sous-titres;</p> </li> 
            <li><p>Si l’objet multimédia a une audiodescription, il doit avoir une fonctionnalité de contrôle de l’apparition/disparition de l’audiodescription.</p> </li> 
        </ul> 
    </li> 
    <li><p>Chaque fonctionnalité doit être accessible par le clavier, via la touche de tabulation, et par tout dispositif de pointage au moins.</p> </li> 
    <li><p>Chaque fonctionnalité doit être activable par le clavier et par tout dispositif de pointage, au moins.</p> </li>
</ul>
```

Il me semble que le code devrait plutôt ressembler à ça (si j'ai bien compris) : 

```
<ul>
    <li>Liste des fonctionnalités obligatoires de contrôle de la consultation&nbsp;:
        <ul>
            <li>L’objet multimédia doit toujours avoir les fonctionnalités suivantes, au minimum&nbsp;: lecture, pause ou stop&nbsp;;</li>
            <li>Si l’objet multimédia a du son, il doit avoir une fonctionnalité d’activation / désactivation du son&nbsp;;</li>
            <li>Si l’objet multimédia a des sous-titres, il doit avoir une fonctionnalité de contrôle de l’apparition/disparition des sous-titres&nbsp;;</li>
            <li>Si l’objet multimédia a une audiodescription, il doit avoir une fonctionnalité de contrôle de l’apparition/disparition de l’audiodescription.</li>
        </ul>
    </li>
    <li>Chaque fonctionnalité doit être accessible par le clavier, via la touche de tabulation, et par tout dispositif de pointage au moins.</li>
    <li>Chaque fonctionnalité doit être activable par le clavier et par tout dispositif de pointage, au moins.</li>
</ul>
```

Par ailleurs, en passant, dans cette définition, on a modifié "souris" par "tout dispositif de pointage" mais cela n'apparaît pas dans la note de révision.

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.

**Comment by juliemoynat-tanaguru** [comment]
La liste n'est toujours pas bien implémentée dans le code source car les 3 sous-points ne sont pas imbriqués dans l'élément de liste "Liste des fonctionnalités obligatoires de contrôle de la consultation :". C'est sémantiquement incorrect et donc pas accessible.

**Comment by acaodinsic** [comment]
Le ticket concerne le glossaire de la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans la version RGAA 4.1

Je ferme donc ce ticket qui concerne le glossaire de la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
