### ISSUE TITLE
Test 4.8.1 : tournure de phrase étrange (bouton qui contient une URL)

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#36]
Bonjour,

Dans le [test 4.8.1](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#test-4-8-1), la phrase suivante est bizarrement tournée : 

>Un lien ou bouton adjacent, clairement identifiable, contient l'adresse (url) d'une page contenant une alternative.

En effet, un bouton ne peut pas contenir l’adresse d’une page.

Proposition : 

>Un lien ou bouton adjacent, clairement identifiable, permet d’accéder à une page contenant une alternative.

**Comment by alixraison** [comment]
Merci pour votre reformulation.

Modification dans le test 4.8.1 ;
“Un lien ou bouton adjacent, clairement identifiable, permet d’accéder à une page contenant une alternative.”

**Comment by juliemoynat-tanaguru** [comment]
Corrigé en RGAA 4.1
