### ISSUE TITLE
Test 5.5.1 : Titre concis difficile s'il contient aussi le résumé

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#37]
Bonjour,

Le [test 5.5.1](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#test-5-5-1) demande un titre de tableau concis.

Le titre du tableau de données ne pourra pas être concis si on utilise `<caption>` pour titrer et résumer un tableau complexe, seule technique correctement accessible (cf. critère 5.1).

Peut-être faut-il ajouter un cas particulier à ce sujet ?

**Comment by alixraison** [comment]
Si l’élément <caption> est utilisé pour fournir à la fois le titre et le résumé du tableau, c’est alors le contenu de l’élément lui-même qui ne pourra pas être considéré comme concis. Le critère n’en reste pas moins valide afin de déterminer au sein de ce contenu un titre dont il faudra apprécier la clarté et la concision. Il n’y a pas lieu d’en faire un cas particulier.

Aucune modification n’est envisagée.
