### ISSUE TITLE
Critères 5.7, 9.3, 11.5 : écriture des rôles ARIA peu claire

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#38]
Bonjour,

Dans le test 9.3.1, la tournure de phrase « La liste utilise les attributs WAI-ARIA `role="list"` et `"listitem"`. » laisse penser qu'il existe un attribut `listitem`. Pour que ce soit correct, il me semble que l'on devrait écrire `role="listitem"` car c'est bien de l'attribut `role` dont il s'agit.

Pour le critère 9.3, la même tournure est utilisée plusieurs fois dans les notes techniques (dans les deux paragraphes).

Idem pour le critère 5.7 pour la tournure « `role="rowheader"` ou `"columnheader"` ».

Idem pour le critère 11.5 pour la tournure « un attribut WAI-ARIA `role=”radiogroup”` ou `“group”` ».

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.

**Comment by juliemoynat-tanaguru** [comment]
Pris en compte dans RGAA 4.1
