### ISSUE TITLE
Test 1.3.6 : Incohérence entre le test et le glossaire sur les méthodes autorisées pour les alternatives d'images SVG

### ISSUE THREAD

**Issue by sbonaventure** [DISIC/RGAA#39]
Le [test 1.3.6](https://numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#test-1-3-6) est écrit de cette manière : 

> Pour chaque image vectorielle (balise `<svg>`) porteuse d’information, ayant une alternative textuelle, cette alternative est-elle pertinente (hors cas particuliers) ?
> - S’il est présent, le contenu de l’attribut `title` est pertinent.
> - S’il est présent, le contenu de l’attribut WAI-ARIA `aria-label` est pertinent.
> - S’il est présent, le passage de texte associé via l’attribut WAI-ARIA `aria-labelledby` est pertinent.

Alors que la [note de glossaire](https://numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#alternative-textuelle-image) autorise les méthodes suivantes : 
- Passage de texte associé via l’attribut WAI-ARIA `aria-labelledby`
- contenu de l’attribut WAI-ARIA `aria-label`
- l’alternative textuelle pourrait se trouver aussi présente dans une balise `<text>`

Pouvez-vous clarifier cela ?

Par ailleurs, c'est très perturbant dans la note de glossaire qui pressente les différentes méthodes autorisées par les attributs et non par types de balises. Je ne sais pas quelles est l'utilisation du RGAA pour chacun d'entre vous, mais de mon coté, je cherche avant tout pour une balise donnée, quelles sont les méthodes accessibles pour lui attribuer une alternative et non l'inverse...

**Comment by juliemoynat-tanaguru** [comment]
Par ailleurs, dans la [définition de l'intitulé de lien](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#intitule-ou-nom-accessible-de-lien), on trouve ceci : 

> Dans le cas d’un lien SVG (version 1.1), le « nom accessible » est obtenu comme suit :
> 
> - Passage de texte associé par l’attribut WAI-ARIA aria-labelledby;
> - Sinon, contenu de l’attribut WAI-ARIA aria-label;
> - Sinon, contenu de l’élément <title> enfant direct du lien;
> - Sinon, contenu de l’attribut x-link:title;
> - Sinon, contenu texte d’un ou plusieurs éléments <text>.
> Il faut cependant être vigilant car cet algorithme de calcul n’est pas encore pris en compte et effectif au sein des différents lecteurs d’écran. A ce jour, le support est disponible avec VoiceOver, mais incomplet ou lacunaire avec JAWS et NVDA. Si bien que le plus petit dénominateur commun sur lequel il est possible de se reposer pour fournir un intitulé au lien est l’élément <text>.

**Comment by alixraison** [comment]
Il y a effectivement une erreur au niveau du test 1.3.6, car l’attribut title n’est pas valide sur un élément SVG et ne constitue donc pas une possibilité d’alternative dont il ne fait alors aucun sens de s’enquérir de la pertinence.

Modification de la condition dans le test 1.3.6 :
“S'il est présent, le contenu de l’élément <title> est pertinent.”

La référence à l’élément <text> signalé en note relate un cas d’utilisation qui peut se rencontrer mais qui n’est pas une bonne pratique. Il n’est donc pas répertorié parmi les tests.
Aucune modification n’est envisagée.

**Comment by sbonaventure** [comment]
Bonjour,

Pourquoi est-il indiqué qu'aucune modification n'est envisagée alors que quelques lignes plus haut vous me dites : 

> Modification de la condition dans le test 1.3.6 :
“S'il est présent, le contenu de l’élément <title> est pertinent.”

D'ailleurs, serait'il possible d'ajouter des mots clé aux issues afin d'identifier rapidement celles qui seront traitées de celles ou aucune modification n'est envisagée ?

**Comment by design-gouv** [comment]
Bonjour,

Il y deux points différents à considérer :

- Une modification est bien prévue concernant la formulation de la première condition du test 1.3.6 ;
- Aucune modification n’est cependant envisagée concernant la référence à l’élément `<text>`.
