### ISSUE TITLE
Critère 1.2: problème de logique posé par la modification de formulation: "une de ces conditions"

### ISSUE THREAD

**Issue by OlivierNourry** [DISIC/RGAA#4]
Tels qu'ils sont rédigés, les tests du critère 1.2 ont une faille logique, qui fait qu'une image non conforme peut passer certains tests, s'ils sont pris au pied de la lettre.

Exemple: cette image `<svg><desc title="toto"></desc></svg>` passe le test car la condition 3 ("Les balises title et desc sont absentes ou vides") est satisfaite. En effet, `<title>` est absente, et `<desc>` est vide, et le test stipule que l'une des conditions doit être satisfaite. Pourtant l'image a bien une alternative non vide via l'attribut `title` de `<desc>`, et devrait donc échouer à ce test.

Plusieurs tests de ce critère présentent ce problème. Je n'ai pas vérifié pour les autres critères à la formulation similaire.

**Comment by alixraison** [comment]
Le cas pris en exemple n’est pas valide en SVG, car l’élément <desc> ne peut pas avoir d’attribut title  : <svg><desc title="toto"></desc></svg>.

Le test pour SVG dit "vérifie-t-elle ces conditions " et non pas "une de ces conditions".

Le RGAA ne peut considérer l’ensemble des combinatoires possibles, d’autant plus lorsqu’il s’agit de structures non valides ; il suppose la validité des structures analysées, et si ce n’est pas le cas et que la construction non valide pose problème à l’accessibilité, il faudra relever la non validité de la construction ; mais la pertinence du test reste entière.

Aucune modification n’est envisagée.
