### ISSUE TITLE
Note de révision : la définition « Mécanisme qui permet d’afficher le texte avec un rapport de contraste conforme » n'est pas supprimée mais reformulée

### ISSUE THREAD

**Issue by ghost** [DISIC/RGAA#40]
Dans la note de révision, il est indiqué que la définition « Mécanisme qui permet d’afficher le texte avec un rapport de contraste conforme » a été supprimée en raison de la suppression du test 3.3.5. Cependant, la définition n'a pas été supprimée mais reformulée pour devenir :

>Mécanisme qui permet d'afficher un rapport de contraste conforme
>
>Composant d’interface dont l’activation permet de modifier l’apparence du site ou de la page de manière à afficher les contenus avec un ratio de contraste suffisant. Le design de ce composant d’interface devra être conforme au critère 3.2 et au critère 3.3 sans avoir recours lui-même à un mécanisme permettant d’afficher un rapport de contraste conforme.

**Comment by alixraison** [comment]
Merci pour votre signalement.

L’entrée de glossaire sera corrigée :

“Mécanisme qui permet d'afficher un rapport de contraste conforme
Composant d’interface dont l’activation permet de modifier l’apparence du site ou de la page de manière à afficher les contenus avec un ratio de contraste suffisant. Le design de ce composant d’interface devra être conforme au critère 3.2 et au critère 3.3 sans avoir recours lui-même à un mécanisme permettant d’afficher un rapport de contraste conforme.”

**Comment by design-gouv** [comment]
Précision : il ne s'agit pas d'une correction de l'entrée de glossaire, mais d'une correction de la note de révision qui lui est associée.

**Comment by juliemoynat-tanaguru** [comment]
La note de révision n'a pas été mise à jour (cf. https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/notes-revision-rgaa3-rgaa4.0/#contenu ).

**Comment by design-gouv** [comment]
Merci de votre signalement.
La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
