### ISSUE TITLE
Glossaire : contradictions sur les titres de tableau de données dans 2 entrées différentes

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#41]
Je ne comprends pas l'entrée de glossaire "[Passage de texte associé au tableau de données](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#passage-de-texte-associe-au-tableau-de-donnees)" dont la définition est la suivante : 

>Texte dans une balise `<caption>` ou dans une balise associée au tableau de données via l’attribut WAI-ARIA `aria-labelledby`.

En effet, cette définition est associée au [critère 5.4](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-5-4) qui parle bien de "titre correctement associé au tableau de données".

Aussi, il me semble donc que l'entrée de glossaire devrait s'appeler "Titre associé au tableau de données".

Mais, par ailleurs, je me rends compte qu'il existe aussi la définition "[Tableau de données ayant un titre ](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#tableau-de-donnees-ayant-un-titre)" dans laquelle il est dit qu'un titre de tableau associé peut être :

> - Dans une balise `<caption>`;
> - Dans un attribut `title`;
> - Dans un attribut WAI-ARIA `aria-label`;
> - Dans une balise associée au tableau de données via un attribut WAI-ARIA `aria-labelledby` sur le tableau.

Ces deux définitions sont donc contradictoires. Il me semble qu'il ne devrait y en avoir qu'une seule, non ?

**Comment by alixraison** [comment]
Merci pour votre signalement.

Suppression de l’entrée de glossaire "Passage de texte associé au tableau de données".

**Comment by juliemoynat-tanaguru** [comment]
Bien pris en compte dans RGAA 4.1
