### ISSUE TITLE
Glossaire : "Indication de format obligatoire" au lieu de "Indication de champ obligatoire" ?

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#42]
Dans le glossaire, l'intitulé de l'entrée "[Indication de format obligatoire](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#indication-de-format-obligatoire)" ne me semble pas correcte.

En effet, il ne s'agit pas de la définition d'une indication d'un format obligatoire pour un champ (par exemple, un format JJ/MM/AAAA à respecter obligatoirement) mais d'une indication qu'un champ est obligatoire.

Il me semblerait donc plus juste et plus compréhensible d'appeler cette entrée "Indication de champ obligatoire". Il s'agit d'ailleurs de ce qui était prévu lors de la [consultation](https://web.archive.org/web/20191024102113/https://evolution-rgaa.numerique.gouv.fr/participer/glossaire/nouvelle-entree-indication-de-champ-obligatoire-2204).

À noter par ailleurs, qu'il est bien question d'"indication de champ obligatoire" dans le critère 11.10. Il s'agit peut-être donc juste d'une coquille dans le glossaire.

**Comment by innoticFR** [comment]
Il y a effectivement un mélange entre le titre qui correspond au test 11.10.5, et le contenu qui s'accorderait davantage avec le 11.10.2. L'entrée suivante du glossaire "Indication du type de données et/ou de format" traite déjà du 11.10.5.

Dans cette entrée, il faudrait, à mon sens, enlever le "!" des exemples de "manière textuelle explicite", car ce n'est pas un usage répandu.

Je pense que rappeler que la couleur n'est pas un moyen suffisant d'indiquer les champs obligatoires aurait toute son importance ici, en note, afin que l"indication graphique" ne soit pas une simple pastille rouge à côté du champ, par exemple.

Il faut aussi remplacer "dans l'ordre du code source" par "dans l'ordre de lecture"

**Comment by juliemoynat-tanaguru** [comment]
Je ne suis pas d'accord avec l'idée de remplacer "dans l'ordre du code source" par "dans l'ordre de lecture" puisque cela pourrait laisser croire qu'avec une légende après, dans le code source, on pourrait la replacer visuellement via CSS en haut du formulaire alors que ce ne serait pas correct.

Il faut donc que cette légende se situe, visuellement et dans l'ordre du code source, avant la première utilisation de l'indication.

**Comment by innoticFR** [comment]
Exact, j'ai été ambigu. Ma remarque allait dans le même sens.

Je pensais que le critère [1.3.2 Meaningful Sequence](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-sequence.html) du WCAG était déjà couvert dans le RGAA, mais effectivement, il n'est couvert que partiellement dans les critères 5.3 et 10.3, et cité (avec plus ou moins de raison) dans les critères 8.10, 10.1, 10.8, 13.3 et 13.4

L'ordre du code source n'a rien de fiable, par rapport au positionnement, il faudrait effectivement une formulation comme "dans l'ordre de lecture (et du code source généré)".

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de l’entrée de glossaire par “Indication de champ obligatoire” ;

Remplacement dans la note : 
“Note : Dans le cas où cette indication n'est pas réalisée de manière textuelle explicite (icône, *, !,...) l'explication de la signification de cette indication doit se situer, visuellement et dans l'ordre du code source, avant la première utilisation de l'indication.”

**Comment by juliemoynat-tanaguru** [comment]
Pris en compte en version 4.1
