### ISSUE TITLE
Glossaire : l'entrée "Correctement restitué (par les technologies d'assistance)" devrait renvoyer vers la page "Environnement de tests"

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#43]
Dans le glossaire, à la définition "[Correctement restitué (par les technologies d'assistance)](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#correctement-restitue-par-les-technologies-d-assistance)", il est donné un environnement de tests qui ne correspond plus tout à fait à celui du RGAA 4. Je cite :

>On procède alors à un test avec NVDA (dernière version) et Firefox, JAWS (version précédente) et IE9+, et Voice Over (dernière version) et Safari.

Il me semble que l'on devrait plutôt dire : 

>On procède alors à un test selon [l'environnement de tests](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/environnement/) défini pour le site.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Une référence vers l’environnement de test règle le problème.

Modification du quatrième paragraphe :
“On procède alors à un test avec les outils de l'environnement de tests défini pour le site.”

**Comment by juliemoynat-tanaguru** [comment]
Pris en compte en version 4.1
