### ISSUE TITLE
Glossaire : "Titre de cadre" et statut "non applicable"

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#44]
Dans la définition de "[Titre de cadre](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#titre-de-cadre)", il est dit :

>Note 2 : Si cela ne gêne pas le fonctionnement de ce type de cadre, il est possible de les rendre indisponibles aux technologies d’assistance en utilisant l’attribut WAI-ARIA `aria-hidden="true"`. Dans ce cas le critère 2.2 sera non applicable.

Dans ce cas, est-ce que le critère 2.1 ne serait pas, lui aussi, non applicable ? En effet, s'il y a un attribut `aria-hidden="true"` sur un cadre sans intérêt, l'attribut `title` n'est pas nécessaire donc si on peut ne pas en juger sa pertinence (critère 2.2), autant ne pas en juger sa présence non plus (critère 2.1), non ?

**Comment by alixraison** [comment]
Merci pour votre signalement.

Un cadre masqué pour une assistance technique n’a pas besoin d’un titre.

Modification de la note 2 : 
“Note 2 : Si cela ne gêne pas le fonctionnement de ce type de cadre, il est possible de les rendre indisponibles aux technologies d’assistance en utilisant l’attribut WAI-ARIA aria-hidden="true". Dans ce cas les critères 2.1 et 2.2 seront non applicables.”

**Comment by juliemoynat-tanaguru** [comment]
Non corrigé dans la version 4.1 : https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#titre-de-cadre

**Comment by acaodinsic** [comment]
Le ticket concerne le glossaire de la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans le glossaire de la version RGAA 4.1

Je ferme donc ce ticket qui concerne le glossaire de la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
