### ISSUE TITLE
Test 1.1.6 Balise <object>

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#45]
Comme la balise `<object>` n'a [pas de rôle ARIA par défaut](https://www.w3.org/TR/html-aria/#el-object), il faudrait compléter le test pour vérifier que l'attribut `role="img"` a été ajouté.

**Comment by innoticFR** [comment]
(valable également pour `embed` et `canvas`)

**Comment by alixraison** [comment]
Merci pour votre signalement.

Voir la réponse faite à l’issue #56 qui englobe cette remarque.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modifications dans l’entrée de glossaire Contraste :

- “Le caractère « ^ » est l’opérateur de puissance” ;
- les occurrences de “luminosité relative” remplacées par “luminance relative”.

**Comment by innoticFR** [comment]
Statut suite à la version du RGAA 4.1

Les réponses apportées répondent à la problématique soulevée dans ce ticket
