### ISSUE TITLE
Calcul du contraste

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#46]
Deux petits correctifs à faire dans le texte descriptif [calcul du contraste
](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#contraste)

Je m'aperçois que ces deux erreurs sont également présentes dans [la traduction officielle du WCAG](https://www.w3.org/Translations/WCAG20-fr/)

### "opérateur exponentiel"

>Le caractère « ^ » est l’opérateur exponentiel.

Il ne s'agit pas de [l'opérateur exponentiel](https://fr.wikipedia.org/wiki/Fonction_exponentielle)  e<sup>x</sup> ("exponential function" en anglais), mais de [l'opération puissance / exposant](https://fr.wikipedia.org/wiki/Exposant_(math%C3%A9matiques)) a<sup>n</sup> ("exponentiation operator" [dans le texte du WCAG](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#relativeluminancedef)).

### "luminosité relative"

Il s'agit en anglais de la [luminance relative](https://en.wikipedia.org/wiki/Relative_luminance). C'est le terme "Relative luminance" qui est utilisé également [dans le WCAG](https://www.w3.org/WAI/GL/wiki/Relative_luminance) par opposition à la luminosité (=brightness).

Je mentirais si je disais que je pourrais définir clairement la différence entre brightness, luminosity, luminance, lightness, luma mais [la discussion au sein du github du WCAG](https://github.com/w3c/wcag/issues/360#issuecomment-482918892) donne des explications assez détaillées pour expliquer l'utilisation du terme "luminance".

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modifications dans l’entrée de glossaire Contraste :

- “Le caractère « ^ » est l’opérateur de puissance” ;
- les occurrences de “luminosité relative” remplacées par “luminance relative”.

**Comment by innoticFR** [comment]
Il faudrait également modifier le seuil qui a été modifié de 0.03928 à 0.04045

voir https://github.com/w3c/wcag/issues/1213

**Comment by innoticFR** [comment]
Statut suite au passage du RGAA 4.1

- La mise à jour des traductions erronées est faite.
- Conserver ce ticket ouvert en attendant l'application du nouveau seuil pour le calcul du contraste (modification déjà actée au niveau du WCAG)

**Comment by acaodinsic** [comment]
Le ticket concerne le glossaire de la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans le glossaire de la version RGAA 4.1

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
