### ISSUE TITLE
Formulation : Critère 8.9 :  Uniquement à des fins de présentation

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#47]
> Critère 8.9. Dans chaque page web, les balises ne doivent pas être utilisées uniquement à des fins de présentation. Cette règle est-elle respectée ?
Test 8.9.1 : Dans chaque page web les balises (à l’exception de `<div>`, `<span>` et `<table>`) ne doivent pas être utilisées uniquement à des fins de présentation. Cette règle est-elle respectée ?

Le terme ["uniquement à des fins de présentation"](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#uniquement-a-des-fins-de-presentation) même s'il est détaillé dans le glossaire pourrait sembler complexe à cerner.

Par exemple la balise `<blockquote>` n'a pas de [sémantique par défaut ](https://www.w3.org/TR/html-aria/#el-blockquote) (= pas de rôle ARIA). Le glossaire indique pourtant :
> par exemple `<blockquote role="presentation">` aura le même effet qu’une absence d’élément `<blockquote>`.

Ce n'est pas faux, mais ajouter un rôle "presentation" à la balise ne modifie rien puisque c'est son rôle par défaut. On sait que `<blockquote>` a une sémantique HTML particulière (un bloc de citation) et c'est cela qui parait important.

La formulation du critère pourrait être revue pour ainsi insister davantage sur l'objectif (à voir d'ailleurs s'il ne mériterait pas de rejoindre le point 9). Par exemple:
> Proposition de formulation : Dans chaque page web, des balises sémantiques sont utilisées correctement pour structure le contenu

Et les tests 8.9.1 et suivants. pourraient ainsi reprendre les obligations et/ou interdictions, notamment relatives aux [fondamentaux ARIA](https://www.w3.org/TR/using-aria/#notes2)

Le test actuel 8.9.1 qui reprend la seconde règle ARIA (ne pas changer la sémantique d'un élément pour la mise en forme) en deviendrait ainsi plus clair quant à son objectif, en précisant que la liste des exceptions n'est pas limitative.

On connait par exemple la subtile différence entre la balise `<b>` (qui relève du simple formatage) et la balise `<strong>` (qui ajoute de l'importance sémantique) qui peut influer sur la restitution par un lecteur d'écran. Au contraire la mention de la balise `<table>`, parmi les exceptions, mériterait de faire référence au point 5.3 pour l'ajout du rôle "presentation".

Il existe d'autres balises HTML dédiées au formatage pur : `small`, la balise `u` pour par exemple marquer d'un souligné un nom de famille en chinois, ... `sub` et `sup` qui sont des conventions typographiques pour par exemple indiquer des notes de bas de page (ce qui relève donc de la pure présentation).

**Comment by innoticFR** [comment]
A noter que la note du glossaire contredit l'intitulé du test
> Test 8.9.1 : Dans chaque page web les balises (à l’exception de `<div>`, `<span>` et `<table>`) 

Puis dans le glossaire

> Note 1 : l’utilisation d’éléments `<div>` ou `<span>` ou plusieurs `<br>` pour créer visuellement un paragraphe est considérée comme non conforme et invalide le critère.

Si cette note part d'une bonne intention, elle ne correspond pas à une exigence du WCAG, et parait peu réaliste.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Le fait que la sémantique d’un élément HTML (comme `<blockquote>, par exemple) n’ait pas de correspondance WAI-ARIA ne veut pas dire que :
1.	L’élément n’a pas de sémantique par défaut, puisqu’il dispose de sa sémantique HTML ; et cette sémantique fait l’objet d’une correspondance au sein de l’API d’accessibilité utilisée (voir https://w3c.github.io/core-aam/#details-id-5 pour l’élément `<blockquote>`). En effet, la qualification “No corresponding role” est clairement définie : “The elements marked with No corresponding role, in the second column of the table do not have any implicit ARIA semantics, but they do have meaning and this meaning may be represented in roles, states and properties not provided by ARIA, and exposed to users of assistive technology via accessibility APIs” (https://w3c.github.io/html-aria/#dfn-no-corresponding-role).
2.	Lui adjoindre un rôle “presentation” ne modifie pas sa sémantique par défaut puisque ce rôle WAI-ARIA vient surcharger la sémantique HTML par défaut ; et cette nouvelle sémantique (qui est en l’occurrence une négation de la sémantique par défaut) va indiquer à l’API d'accessibilité de ne pas restituer la sémantique par défaut de l’élément.
Il est à noter que la version WAI-ARIA 1.2 prévoit l’introduction d’un rôle “blockquote” (https://w3c.github.io/aria/#blockquote).

Les tests du critère à partir des règles d’utilisation des éléments de spécification WAI-ARIA en HTML reposent sur un ensemble de bonnes pratiques qui sont encouragées mais dont l’absence n’est pas a priori sanctionnée (tant qu’un mésusage ne porte pas à induire en erreur l’utilisateur).

Le fait qu’il existe “des balises HTML dédiées au formatage pur” reste un point de vue. Il faut s’entendre sur la version de HTML dont il est question, si on considère la dernière version (HTML 5), l’ensemble des éléments de type contenu phrasé sont tous considérés comme ayant un rôle sémantique. (https://html.spec.whatwg.org/multipage/text-level-semantics.html#usage-summary

A propos de la note 1, son propos est plus qu’une bonne intention et se justifie par certaines assistances techniques permettant de naviguer de paragraphe en paragraphe, ce qui fait de l'élément `<p>` un élément de structure “programmatically determined” au sens du SC 1.3.1 (Infos and Relationships).

Aucune modification n’est envisagée.

L’usage présentationnel des éléments, traité actuellement à différents endroits, pourra être revu ultérieurement lors d’une évolution majeure du RGAA.

**Comment by innoticFR** [comment]
En effet, les évolutions rendent caduques une partie de mes remarques. 

Pour référence, l'ajout d'un rôle ARIA permet effectivement de surcharger le rôle natif par défaut :
[5.2 Conflicts between native markup semantics and WAI-ARIA ](https://www.w3.org/TR/core-aam-1.1/#mapping_conflicts)

**Comment by innoticFR** [comment]
Après relecture, il me semble que la réponse n'adresse pas le cœur du problème : La formulation actuelle rend inutilement ardue la compréhension de cette problématique pourtant aisée.

**Autant poser les choses clairement et formuler la problématique pour montrer que l'on s'intéresse ici au respect de la sémantique, et non à la présentation.**

> *"l’ensemble des éléments de type contenu phrasé sont tous considérés comme ayant un rôle sémantique"*

Oui. Exactement! Et c'est ce qu'il faut qu'il ressorte de ce critère : la sémantique.

---

Le critère pose la question:
> Dans chaque page web, les balises ne doivent pas être utilisées **uniquement à des fins de présentation**.

Dans le glossaire, on nous explique ensuite qu'il n'y a aucun problème à utiliser une balise **uniquement à des fins de présentation** dès lors que l'on respecte la sémantique (en la surchargeant si besoin):

> Le rôle WAI-ARIA `presentation` peut être également utilisé pour supprimer la sémantique d’un élément lorsque ce dernier est utilisé **uniquement à des fins de présentation**

Le cas du `blockquote` n'est qu'un exemple, et la même remarque est valable avec la balise `<u>` utilisée pour marquer d'un souligné un nom de famille en chinois, cas d'utilisation tout à fait valide au regard de sa définition, sans n'apporter aucun rôle dans l'API d'accessibilité (ni HTML, ni ARIA)
> Valid use cases for the `<u>` element include annotating spelling errors, applying a proper name mark to denote proper names in Chinese text, and other forms of annotation.

---

Concernant la note 1, elle contredit toujours l'intitulé du test puisque ce test ne s'applique pas aux balises `div` et `span`. Il est donc impossible d'invalider un critère lorsqu'il ne s'applique pas.

Cette note ne fait nullement mention de la balise `p`, et si telle était l'intention de cette note, il conviendrait de le signaler dans la note directement. Pour le reste, c'est effectivement une bonne pratique mais elle ne fait effectivement pas partie des recommandations du WCAG. Pour l'utilisation de multiples `<br />` ou de la balise `<span>` c'est en effet problématique. Concernant la balise `<div>` je n'ai pas connaissance d'une telle distinction opérée par les lecteurs d'écran.

**Comment by innoticFR** [comment]
Statut suite passage au RGAA 4.1

Aucune réponse n'a été apportée à la problématique soulevée dans ce ticket.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans la version RGAA 4.1 et précise : "_pourra être revu ultérieurement lors d’une évolution_"

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées ultérieurement. Cela semble être l'objet de l'issue #93
