### ISSUE TITLE
Formulation : Critère 10.2 (et 10.3) : Feuilles de styles désactivées

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#48]
> Critère 10.2. Dans chaque page web, le contenu visible reste-t-il présent lorsque les feuilles de styles sont désactivées ?

Ce critère vise normalement à déterminer qu'aucun élément porteur d'information ne soit inclus via CSS (ex: contenu textuel sous forme d'image, insertion de texte porteur de sens via la propriété `@content`).

En lisant le critère tel quel, il pourrait donner l'impression de rendre obligatoire la possibilité de pouvoir naviguer et visualiser le site en désactivant les feuilles de style, ce qui n'est pas la volonté du WCAG ([voir réponse de Christophe Strobbe](https://lists.w3.org/Archives/Public/w3c-wai-ig/2019AprJun/0067.html)), et qui rendrait quasi improbable la consultation de sites interactifs (javascript chargés de faire un toggle sur une propriété CSS pour afficher/masquer des éléments).

Il faudrait peut-être privilégier une formulation comme "les feuilles de styles ne sont pas utilisées pour inclure des éléments importants ou porteurs d'informations"

A mon sens, rendre possible la navigation sans CSS, même si c'est une best-practice, ce n'est pas vraiment applicable.

Exemple de code:
```
<style>
   [aria-hidden="true"] {display: none}
</style>
<label> Prénom: <input type="textbox" required id="firstname" name="firstname"></label>
<div id="firstname_error" aria-hidden="true">Vous devez saisir votre prénom</div> 
```

Si [la technique F87](https://www.w3.org/WAI/WCAG21/Techniques/failures/F87.html) indique la possibilité de désactiver CSS comme un moyen de tester la validité du critère, elle n'en fait pas un objectif
> A common way to test this critieria is to disable CSS styles to view whether content added using pseudo-elements remains visible.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de l’intitulé du critère 10.2:
“Critère 10.2 Dans chaque page web, le contenu visible porteur d’information reste-t-il présent lorsque les feuilles de styles sont désactivées ?”

Aucune modification n’est envisagée pour le critère 10.3

S’agissant du critère 10.3, il concerne la préservation de la compréhension de ces contenus, c’est-à-dire de la préservation de leur lisibilité (l'ordre des éléments est logique) et de leur cohérence (l'enchaînement de la lecture est cohérent), au-delà de leur agencement CSS. Cela n’implique pas de “rendre obligatoire la possibilité de pouvoir naviguer et visualiser le site en désactivant les feuilles de style”. Selon le SC 1.3.2, Meaningful Sequence, on doit pouvoir disposer d’un ordre de lecture correct qui peut être programmatiquement déterminé, c’est-à-dire en HTML disposer de séquences de données correctement structurées. La désactivation des feuilles de style permet de s’en assurer. Cependant, il reste tout à fait possible de vérifier la présence de séquences de données correctement structurées par une revue directe du code source généré de la page.

**Comment by innoticFR** [comment]
Même si je n'ai pas vraiment adressé le critère 10.3, je pense, de manière générale,  que lorsque vous pensez que des précisions doivent être apportées, il faut qu'elles le soient dans le RGAA afin qu'elles profitent à ceux qui en ont besoin.

Autant qu'il soit clairement dit que *“Cela n’implique pas de rendre obligatoire la possibilité de pouvoir naviguer et visualiser le site en désactivant les feuilles de style”*, et de préciser que la désactivation de javascript n'est qu'un moyen et pas une finalité.

L'exemple que je donnais d'éléments masqués qui viendraient perturber la compréhension reste valable également pour ce critère.

**Comment by innoticFR** [comment]
J'ajoute ici la réponse à une contribution pertinente sur la question émise sur la liste du RGAA afin de centraliser les échanges sur la question.

>* WCAG ne demande pas à ce *« qu'aucun élément porteur d'information ne soit inséré via CSS »*, mais demande - si c’est le cas  - **à ce que cette information soit disponible en l’absence de CSS** comme c’est le propos de la technique F87 (*F87: Failure of Success Criterion 1.3.1 due to inserting non-decorative content by using `:before` and `:after` pseudo-elements and the 'content' property in CSS) : «  Check that non-decorative information presented by the generated content is available when styles are overridden. »*;

Au niveau du WCAG, CSS est une technologie [compatible avec l'accessibilité](https://www.w3.org/WAI/WCAG21/Understanding/conformance#dfn-accessibility-supported) qui peut donc être une "[exigence technique](https://www.w3.org/WAI/WCAG21/Understanding/conformance#dfn-relied-upon)" . Ainsi, suite à [cette décision du WCAG ](https://www.w3.org/2018/09/25-ag-minutes.html#item05) la mention "turn off CSS" de la [technique informative F87 du WCAG 2.0 ](https://www.w3.org/WAI/GL/WCAG20-TECHS/F87.html) a été retirée dans la [technique équivalente du WCAG 2.2](https://www.w3.org/WAI/WCAG22/Techniques/failures/F87) (et 2.1). **F87 n'exige pas que CSS puisse être désactivé mais simplement surchargé ("overriden")**.

>* Ensuite, il est signalé que WCAG permettrait « de fournir une alternative à une image CSS porteuse d'information via l'attribut aria-label sans que celui-ci ne soit "visible" lorsque les CSS sont désactivées. ». En l'absence d'une source, je supposerai que vous faites référence à la technique ARIA 24 (ARIA24: Semantically identifying **a font icon** with role="img") qui effectivement propose des exemples tel que le vôtre. Ce sont justement ces exemples qui valent à cette technique d’être critiquée (https://github.com/w3c/wcag/issues/1007) et pour laquelle une pull request (https://github.com/w3c/wcag/pull/1016) propose notamment de corriger ce point : « **alternative text of the icons** in the source code as text (class=sr-only), so that the text is also visible without CSS (see F87) »,  en référence bien entendu à la technique F87 précédemment citée.

La question de l'alternative aux images ne regarde pas directement le ticket actuel.

Les polices d'icône (ARIA24) que je n'ai pas abordées sont un cas très particulier, dont l'emploi est comme vous le signalez plus que problématique. Lire notamment [ce ticket du WCAG](https://github.com/w3c/wcag/issues/1185).

Les objets non-natifs de type "image" [(`role="img"`)](https://www.w3.org/WAI/PF/aria/roles#img) doivent nécessairement posséder un nom accessible explicite (donc utilisation de `aria-label` ou `aria-labelledby`), cela est abordé dans la technique informative [ARIA 6](https://www.w3.org/WAI/WCAG22/Techniques/aria/ARIA6) par exemple. Cela est adressé par le point 1.3.1 du RGAA (et non par les critères dont il est question ici). 

> Le contenu des WCAG n'est pas exempt d’imprécisions, et parfois les exemples proposés n’illustrent que le point en question (la présence d’un rôle `img` dans ce cas) sans se soucier de la conformité globale du code proposé, et ici manifestement un texte visuellement caché est manquant pour assurer cette conformité globale ;

En se focalisant sur un exemple isolé contenant une image, on risque de se détourner de la question qui concerne la **demande d'ajout d'une simple phrase courte visant à clarifier la question de la désactivation de CSS**. L'exemple dans le premier message de ce ticket n'est pas lié aux images et illustre de façon similaire ce pour quoi il est illusoire d'exiger qu'un site soit compréhensible sans CSS.

Pour l'anecdote, le but de la  [technique d'échec (informative) F3 ](https://www.w3.org/WAI/WCAG21/Techniques/failures/F3) (qui intéresse davantage la question que vous soulevez sur les images) était notamment de permettre lors de l'activation sous Windows du mode contraste élevé d'accéder à l'information portée par les images CSS (car à l'époque elles étaient désactivées sous IE et Firefox dans ce mode). La discussion sur le Github du WCAG "[Clarify the meaning of "is also available" in step #3 of F3 test](https://github.com/w3c/wcag/issues/80#issuecomment-501284004) " illustre que la problématique liée à cette technique informative a depuis évolué (voir [pull request](https://github.com/w3c/wcag/pull/120/files#diff-e53b5d341a0bd99fdf2208e9ab7c9475) à ce sujet notamment et les contributions d'Alastair Campbell dans le thread). A noter que **l'activation de ce mode n'étant pas corrélée avec la désactivation complète de CSS, mais uniquement des images CSS**, il est nécessaire de prendre un certain recul sur toute solution se basant sur la désactivation totale de CSS pour tenter de satisfaire cette technique ou une autre.

>* Le RGAA se veut effectivement le plus conforme possible aux WCAG, mais s'autorise à ne pas en reproduire les erreurs ; il n'y a donc pas lieu de modifier le RGAA dans ce sens.

Ce ticket porte le terme "Formulation" dans le titre; le but étant d'ajouter une phrase explicative d'une vingtaine de mots, ce sera vite fait et profitable à tous.

**Comment by innoticFR** [comment]
Proposition pertinente reçue sur la liste du RGAA (Steven M):
> Pour en revenir au RGAA, dans le critère 10.3 ne faudrait-il pas :
>* ajouter la technique C27 
>* supprimer la technique G59 qui est déjà dans le critère 12.8.

La référence à la technique [C27](https://www.w3.org/TR/WCAG20-TECHS/C27.html) est effectivement la notion importante ici

**Comment by innoticFR** [comment]
Statut suite passage au RGAA 4.1

Aucune réponse n'a été apportée à la problématique soulevée dans ce ticket.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans la version RGAA 4.1

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d’une évolution.

Le ticket serait relatif au critère 10.2 (et 10.3 ?)  et pourrait proposer l'ajout d'une Note (texte rédigé à proposer) et de la référence technique C27 ?
