### ISSUE TITLE
Disparition des critères concernant les sous-titrages de médias en direct 

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#49]
Les [exigences européennes](http://mandate376.standards.eu/standard/technical-requirements/captions-live) et [le WCAG ](https://www.w3.org/WAI/WCAG21/Understanding/captions-live.html) rendent obligatoires la présence de sous-titres pour les vidéos en direct au niveau AA. Il s'agissait du [critère 4.5 du RGAA 3.0](http://references.modernisation.gouv.fr/referentiel-technique-0#critre-45-aa-chaque-mdia-temporel-en-direct-a-t-il-si-ncessaire-des-sous-titres-synchroniss-ou-une-transcription-textuelle-hors-cas-particuliers-) et celui-ci a visiblement été retiré de la nouvelle version.

Je comprends ce pragmatisme, car c'est quelque chose qui demande un certain investissement humain et/ou financier. Toutefois, il y aurait pu y avoir des recommandations / exigences / précisions afin de montrer que cela a été pris en compte, et ainsi ne pas oublier les plus de 6% de déficients auditifs en France (personnes âgées, malentendants, sourds, ...) auxquelles s'ajoutent les personnes dont le français n'est pas la langue maternelle, ou certains troubles du langage oral (aphasies par ex.) ou de l'attention.

Aujourd'hui, beaucoup de retransmissions "live" ont déjà un replay. Je ne parle pas que de télévision, mais également de conférences, d'événements sportifs / politiques (ex: conseil municipal, ...). Cela pourrait donc être proposé comme solution modérée (outre celles recommandées par le W3C) : à savoir, que, en dernier recours, toute transmission "en direct" non accessible donne lieu à une retransmission différée accessible dans un délai adapté (ce qui serait donc couvert ensuite par le point 4.1.1).

A défaut d'adresser ce point au sein du RGAA, il risquerait d'y avoir deux sortes de comportements :
- les premiers qui vont penser que s'agissant d'une vidéo captée en direct, sa rediffusion en l'état ne serait pas soumise aux autres obligations du RGAA,
- et les autres qui ne vont simplement plus proposer de retransmission différée.

Etant entendu qu'il est possible d'invoquer la [dérogation pour charge disproproportionnée](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/obligations/#d%C3%A9rogation-pour-charge-disproportionn%C3%A9e) si nécessaire, le RGAA doit pouvoir faire les recommandations suffisantes pour satisfaire les exigences légales.

**Comment by alixraison** [comment]
Le RGAA est en cohérence avec la Directive (UE) 2016/2102 qui exclut “les médias temporels en direct” dans l’article 1-4(c).
https://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:32016L2102#d1e652-1-1 

Aucune modification n’est envisagée.

**Comment by innoticFR** [comment]
Il semble y avoir un malentendu malheureux sur la nature de mon ticket. Je (re-)précise qu'il n'est nullement question de rendre obligatoire aveuglément la retranscription des médias en directs, mais j'insiste sur la nécessité d'apporter des recommandations ou précisions supplémentaires pour leur rediffusion.

Ma remarque va parfaitement dans le sens de ce qui est indiqué au point (27)
> Les médias temporels en direct qui sont conservés en ligne ou republiés après leur radiodiffusion en direct devraient être considérés comme des médias temporels préenregistrés, et ce, sans délai indu à compter de la date de la radiodiffusion initiale ou de la republication du média temporel, le délai n'excédant pas le temps strictement nécessaire pour rendre accessibles des médias temporels, la priorité étant donnée aux informations essentielles ayant trait à la santé, au bien-être et à la sécurité du public. Cette durée nécessaire ne devrait pas en principe dépasser quatorze jours. Dans des cas justifiés, notamment lorsqu'il est impossible de fournir les services pertinents en temps utile, ce délai peut exceptionnellement être prorogé jusqu'au délai minimal nécessaire pour rendre le contenu accessible.

**Il est donc, comme je le disais, compréhensible que le RGAA ne fasse pas aujourd'hui mention dans les critères des vidéos en direct, mais il semblerait nécessaire d'apporter des précisions sur ce qu'il advient de leur retransmission.**

Je ne suis pas là pour lever la confusion née dans le décret de 2019. Le fait que la directive 2016/102 ne s'applique pas aux médias en direct s'explique par l'existence de la directive [directive 2010/13/UE](https://eur-lex.europa.eu/legal-content/FR/ALL/?uri=CELEX%3A32010L0013) relative aux médias audiovisuels. Cela n'a jamais signifié du point de vue de la directive 2016/102 une exemption inconditionnelle d'accessibilité, mais simplement la nécessite de se référer à toute autre législation ou réglementation et notamment l'article 7 de la directive 2010/13. Ceci dit, c'est une toute autre question.

**Comment by innoticFR** [comment]
<details>
<summary>Deux autres directives pour simple référence également (cliquer pour afficher)</summary>

* [Directive (UE) 2018/1972 du Parlement européen et du Conseil du 11 décembre 2018 établissant le code des communications électroniques européen](https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:32018L1972&) 
* [Directive (UE) 2019/882 du Parlement européen et du Conseil du 17 avril 2019 relative aux exigences en matière d’accessibilité applicables aux produits et services](https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX%3A32019L0882)

Les points 31 et 46 ainsi que la liste des exemptions sont intéressants (mais je ne m'étends pas dessus, car ce n'est pas le sujet)
</details>

**Comment by innoticFR** [comment]
Statut suite passage au RGAA 4.1

Aucune réponse n'a été apportée à la problématique soulevée dans ce ticket.

**Comment by acaodinsic** [comment]
La réponse de **design-gouv** est correcte et tout à fait justifiée.

Le RGAA doit permettre de déterminer la conformité règlementaire en cohérence avec la Directive (UE) 2016/2102 et nos lois en application de la mise en oeuvre des exigences d'accessibilité. Son périmètre est précisé par le chapitre II, articles 5 à 7, du décret n°2019-768 du 24 juillet 2019.

Le critère à succès WCAG 1.2.4 relatif au sous-titrage des médias en direct n'est pas exigé par la Directive, (UE) 2016/2102 et se trouve donc hors du champ d'application du RGAA. De manière générale, le RGAA n'a pas à traiter des critères non exigés, ni à apporter de précision ou de préconisation sur les objets numériques concernés par ceux-ci. 

Le ticket concerne le critère WCAG 1.2.4 qui ne fait pas partie du périmètre du RGAA. **Je ferme ce ticket**.

_Néanmoins, le problème de rediffusion de médias enregistrés en direct qui n'est pas un sujet RGAA, mais, plutôt un sujet d'accessibilité, pourrait être discuté ailleurs que dans ce dépôt._

**Comment by innoticFR** [comment]
Bonjour,

Il vous aurait fallu une ligne informative à rajouter dans le RGAA, et vous consacrez 15 lignes pour fermer ce ticket en plein milieu de la nuit. Le but n'est pas de "discuter" mais d'informer les professionnels dans le but d'aider le plus grand nombre.

La loi du 2019 précise en son article 1 :
>  En l'absence de telles normes harmonisées applicables à certains types de services de communication au public en ligne, les personnes précitées se réfèrent aux normes internationales ou, à défaut, aux standards internationaux applicables.
