### ISSUE TITLE
Coquilles typographiques ou de balisage dans les critères

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#5]
Bonjour,

J'ai trouvé plusieurs coquilles typographiques ou de balisage dans les critères sur le [site du RGAA 4](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#contenu).

1. À plusieurs endroits, on retrouve l'écriture "est-t-elle". Le "-t" n'est pas nécessaire car la liaison se fait directement avec "est".

2. Dans la version HTML, de nombreux éléments de code sont cités (éléments HTML ou attributs) et ne sont pas encapsulés dans un élément `<code></code>`. Exemples : 

    1. Éléments `<optgroup>` et attributs `label` dans le critère 11.8 ;

    2. Attributs `value`, `alt`, valeurs d’attributs `submit`, `reset`, `button`, `image` dans le critère 11.9 ;

    3. Attributs `aria-required="true"`, `required`, `aria-invalid="true"` dans le critère 11.10 ;

    4. Etc.

3. **Critère 1.4 :** dans le test 1.4.6, il est écrit « Pour chaque image vectorielle […] utilisé » au lieu de « utilisé**e** ».

4. **Critère 1.6 (et d’autres) :** Il est écrit « url » au lieu de « URL ».

5. **Critère 3.1 :** 

    1. Pour le **test 3.1.1** « porteuse d’information » renvoie vers le glossaire « Image porteuse d’information » alors qu’on parle ici de « mise en couleur porteuse d’information ».
    2. **Tests 3.2.3 et 3.2.4** : il est écrit « d’un taille » au lieu de « d'un**e** taille »

6. **Critère 3.2 :** dans le test 3.2.1, un point d’interrogation est présent à la fin de la ligne du deuxième élément de liste.

7. **Critère 4.1 :** Dans le cas particulier, il est écrit « leurs établissement » au lieu de « leurs établissement**s** ».

8. **Critère 4.12 :** Dans la phrase (test 4.12.2) « La fonctionnalité est activable par le clavier et la souris. », il semble qu’on ait oublié de remplacer « souris » par « tout dispositif de pointage ».

9. Des liens vers le glossaire ne sont pas fonctionnels (exemple : « résumé » au critère 5.1)

10. **Critère 6.1 :** dans le cas particulier, il manque le lien vers la définition « ambigu pour tout le monde ».

11. **Critère 6.2 :** dans le test 6.2.1, les balises `<a>` et `</a>` ne sont pas visibles et ont créé une ancre sur le mot « et » qui les sépare.

12. **Critère 8.3 :** Sur le site, le cas particulier du critère 8.2 est placé sous le critère 8.3

13. **Critère 10.1 :** « espace » en tant que caractère est un nom féminin ([https://larousse.fr/dictionnaires/francais/espace/31014?q=espace#30933](https://larousse.fr/dictionnaires/francais/espace/31014?q=espace#30933)). On devrait donc écrire « Les espaces ne sont utilisé**e**s… »

14. **Critère 10.8** : dans le deuxième point du test 10.8.1, il est écrit « technologies d’assistanc**es** » au lieu de « technologies d’assistanc**e** »

15. **Critère 11.2 :** Test 11.2.4 « il est associé**e** » au lieu de « il est associ**é** »

16. **Critère 11.5 :** dans le test 11.5.1, l’élément `<input type="radio">` s’affiche comme un champ radio au lieu de s’écrire comme du code.

17. **Critère 11.8 :** « sont-ils regroup**ées** » au lieu de « sont-ils regroup**és** »

18. **Critère 11.10 :** dans le test 11.10.7, dans la version HTML, il est écrit « une instructio**ns** » au lieu de « une instructio**n** ».

19. **Critère 12.2 :** 

    1. « Le menu ou **de** barres de navigation est toujours » au lieu de « Le menu ou **les** barres de navigation sont toujours »

    2. « Le menu ou **de** barres de navigation se présent**e** » au lieu de « Le menu ou **les** barres de navigation se présent**ent** »

20. **Critère 13.4 :** Le cas particulier présent sous le critère ne devrait pas être présent car il concerne le critère 13.3. Le critère 13.4 ne mentionne pas de cas particulier.

21. **Critère 13.17 :** tests 13.17.2 et 13.17.3 : « qui provoque un changemen**ts** brusqu**es** de luminosité ou **les** effe**ts** de flash » au lieu de « qui provoque un changemen**t** brusqu**e** de luminosité ou **un** effe**t** de flash »

**Comment by innoticFR** [comment]
J'en ajoute 2
* Critère 9.2 : « A noter cependant que **l’utilisation** d’un style seul restera **insuffisant** », il manque le "e" final.

* Critère 11.13 : « la spécifications WCAG 2.1 », retirer le "s"

Il existe également des coquilles dans le guide : https://numerique.gouv.fr/publications/rgaa-accessibilite/obligations/#contenu (*ex: "tel que définit", "des éléments multimédia", "les évaluations (ou audits) de conformité prévus"*)

**Comment by OlivierNourry** [comment]
> Critère 11.3. Dans chaque formulaire, chaque étiquette associée à un champ de formulaire ayant la même fonction et répété plusieurs fois dans une même page ou dans un ensemble de pages est-elle cohérente ?

"répété" à mettre au féminin.

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.

**Comment by juliemoynat-tanaguru** [comment]
Coquilles dans les critères corrigées en RGAA 4.1

@innoticFR les coquilles dans le guide "Obligations d'accessibilité numérique" n'ont pas été corrigées. Je te laisse faire un ticket dédié sur ce point et je ferme ce ticket-là comme ce n'était pas le sujet initial ;)
