### ISSUE TITLE
Formulation Tests 10.11.1 et 10.11.2

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#50]
> Test 10.11.1 : Pour chaque page web, lorsque le contenu dont le sens de lecture est horizontal est affiché dans une fenêtre réduite à une largeur de 320px, l’ensemble des informations et des fonctionnalités sont-elles disponibles sans aucun défilement horizontal (hors cas particuliers) ?
> Test 10.11.2 : Pour chaque page web, lorsque le contenu dont le sens de lecture est vertical est affiché dans une fenêtre réduite à une hauteur de 256px, l’ensemble des informations et des fonctionnalités sont-elles disponibles sans aucun défilement vertical (hors cas particuliers) ?

### "pixels" 

Il vaudrait mieux reprendre la formulation initiale du WCAG, et bien préciser que l'on parle ici de pixels CSS afin de prendre en compte l'impact du zoom logiciel.

A défaut de précision, il serait possible de penser valider le test, en réduisant le niveau de zoom à 25%.

Voir également les discussions en cours : https://github.com/w3c/wcag/issues/698 à savoir que 320px CSS doit être considéré comme la limite inférieure.

### "sens de lecture"

Le document non-normatif ["Understanding" propre au critère 1.4.10](https://www.w3.org/WAI/WCAG21/Understanding/reflow.htm) du WCAG dont il s'agit se contente d'adresser le sujet dans deux exemples:

> Zooming the page for horizontally written languages where pages scroll vertically **by default** (e.g. English) **should** not require horizontal scrolling. Zooming the page for vertically written languages which scroll horizontally **by default** **should** not require vertical scrolling.

C'est un contresens que de penser que le sens de défilement par défaut dépende systématiquement de l'orientation de l'écriture et ne puisse être changé. Les termes "*by default*" et "*should*" montrent que le WCAG autorise cette possibilité. La formulation serait différente si elle était la suivante:
> Zooming the page for vertically written languages which **must** scroll horizontally **must** not require vertical scrolling.

La discussion [SC 1.4.10 Zoom content](https://github.com/w3c/wcag21/issues/335) donne des remarques pertinentes sur l'évaluation du critère [1.4.10 du WCAG](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) : la possibilité dans un même langage (chinois, par exemple) d'avoir des textes horizontaux et verticaux, le fait que [beaucoup de langages écrits verticalement utilisent le défilement vertical](http://tategaki.github.io/awards/). Le choix du mode de défilement horizontal est donc un choix éditorial et le défilement vertical reste conventionnel y compris dans ces langues.

La formulation du critère (normatif) du WCAG s'abstient de s'éterniser sur la question en exigeant simplement que le défilement ne se fasse que dans un seul sens.

Remarque: la notion de "sens de lecture verticale" est ambiguë, il faudrait lui préférer un terme plus proche de l'original "système d'écriture vertical", "langue à écriture verticale".

**Comment by innoticFR** [comment]
Ticket lié : https://github.com/DISIC/RGAA/issues/78

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de la note technique au critère 10.11 : 
"Note technique
Lorsqu'il est ici question de pixel, il s'agit du pixel CSS tel que définit par le W3C (https://www.w3.org/TR/css3-values/#reference-pixel)."

**Comment by innoticFR** [comment]
Je vous laisse revenir vers moi sur les autres points qui sont tout aussi importants :
- le WCAG avance de son côté pour expliciter qu'il s'agit de limites inférieures, et non de tailles exactes;
- notion de "sens de lecture" ambiguë là où le WCAG n'adresse que le "sens de défilement"

**Comment by innoticFR** [comment]
Statut suite passage au RGAA 4.1

Prise en compte partielle de la problématique soulevée dans ce ticket.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans la version RGAA 4.1 

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d’une évolution ultérieure. Par exemple, en proposant une formulation plus adaptée pour les notion évoquées.
