### ISSUE TITLE
Formulation : Glossaire : Titre

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#51]
L'entrée [titre](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#titre) du Glossaire indique :

> Note : les titres cachés via CSS sont considérés comme présents et valident le critère 9.1.

Cette affirmation mérite des précisions. Il s'agit ici a priori de titres cachés "visuellement", avec une méthode de masquage CSS, mais qui conserve toujours le titre dans le flux de la page (par opposition à ce que fait `display: none`). On conserve donc la possibilité de "focus". 

> Par contre, la hiérarchie ne doit pas obligatoirement débuter par un `h1`.

En lisant cette phrase, sans lire [la page du W3C à ce sujet](https://www.w3.org/WAI/tutorials/page-structure/headings/), on ne perçoit pas l'intention.

Il n'est pas question de supprimer totalement l'élément `h1` de la page mais de permettre que la page débute par un autre niveau de titre, et que le `h1` se retrouve plus loin.

il faudrait plutôt écrire "*Par contre, le titre principal (`h1`) ne doit pas nécessairement être le premier niveau de titre de la page (ex: titre principal après la navigation)*"

Remarque moins importante :
>  les degrés de titre ne peuvent pas être sautés

Je suis personnellement d'accord avec ça, mais je dois reconnaître que la phrase du WCAG porte du conditionnel :

> Skipping heading ranks can be confusing and **should be avoided where possible**: Make sure that a `<h2>` is not followed directly by an `<h4>`, for example.

Cela pourrait avoir du sens dans certaines hiérarchies, où l'on souhaite donner aux feuilles le même niveau, en sautant parfois un rang intermédiaire, afin de permettre la navigation de feuille en feuille facilement opérable au clavier depuis les technologies d'assistance.

- h1: Direction régionale
  - h2: Service des affaires internes
    - h3: Cellule 1
       - h4: John
       - h4: Paul
       - h4: George
       - h4: Ringo
    - h3: Cellule 2
       - h4: Dewey
       - h4: Louie
       - h4: Huey
  - h2: Service comptabilité
    - ...
       - h4: Stone
       - h4: Charden

Toutefois, il est bien plus probable qu'un saut dans la hiérarchie résulte d'une erreur d'appréciation plutôt que d'un choix délibéré.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de la note de l’entrée de glossaire
“Note : les titres visuellement cachés via CSS sont considérés comme présents et valident le critère 9.1.”

Les deux points suivants ne sont plus requis :

- La présence nécessaire d’un titre `<h1>` même si une hiérarchie de titres est présente ;
- L’absence de sauts hiérarchiques entre niveaux de titre.

Modification du second paragraphe de l’entrée du glossaire :
“Assurer une stricte hiérarchie entre les titres d’une page web est une bonne pratique, mais la présence de sauts hiérarchiques n’invalide pas le critère tant que cette hiérarchie plus lâche reste cohérente (un titre h3 peut ainsi venir directement après un titre h1, par exemple). La hiérarchie de titres ne doit pas obligatoirement contenir un titre h1. 
Même si ces pratiques ne sont pas encouragées, elles n’invalident pas le critère.”

**Comment by innoticFR** [comment]
Statut suite passage au RGAA 4.1

- Les réponses apportées correspondent partiellement à la problématique adressée dans le ticket. 

La phrase _"La hiérarchie de titres ne doit pas obligatoirement contenir un titre h1."_ va à l'encontre de la problématique abordée. Ce qu'il était important de faire comprendre est qu'il est possible d'avoir un h2 avant le premier h1.

Même s'il est vrai que l'absence d'un h1 n'est pas "fautive", je n'encouragerais pas le RGAA à le dire. Il faut ici montrer que le premier h1 de la page peut se retrouver après un h2, car il importe plus d'avoir un h1 au début du contenu qu'un h1 inutile au début d'un menu.

**Comment by acaodinsic** [comment]
Le ticket concerne le glossaire de  la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans le glossaire de la version RGAA 4.1

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans le glossaire de la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
