### ISSUE TITLE
Formulation : Glossaire : Contexte du lien

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#52]
> Note 2: RGAA considère que des liens particuliers comme des liens de type mailto (qui génère un lien sous la forme d’une adresse email cliquable) sont suffisamment explicites et ne requièrent pas de signaler que l’action consiste à envoyer un email.

Cette phrase mériterait une réécriture afin de préciser d'emblée que l'on s'intéresse uniquement aux liens dont le texte contient une adresse e-mail cliquable, et non pas réellement aux liens de type `mailto:` *(la suite de la note actuelle donnant la possibilité de renvoyer vers un formulaire, par exemple)*.

Exemple d'échec : Un lien `mailto:` contient une alternative non pertinente

    <a href="mailto:martin.dupont@example.com">Je</a> m'appelle Martin Dupont

Exemple de réussite : Le lien renvoie vers un formulaire de contact,

    <a href="#contact_form">martin.dupont@example.com</a>

(utile quand on ne possède pas de client de messagerie logiciel et que les liens `mailto:` sont inopérants).

Ce n'est pas tant le type du lien qui doit être visé ici par cette note, mais le contenu du lien, et donc considérer qu'une adresse e-mail est un texte de lien suffisant pour comprendre la fonction du lien.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de la note 2 :
« Note 2 : RGAA considére qu'une adresse e-mail  de type xxx@xxx.yyy est un texte de lien suffisant pour comprendre la fonction du lien et ne requiert pas de signaler plus explicitement l’action. ».

**Comment by innoticFR** [comment]
Statut suite au passage au RGAA 4.1

La modification apportée répond à la problématique
