### ISSUE TITLE
Formulation : Glossaire : Sous-titres synchronisés (objet multimédia)

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#53]
>  Note 2 : il ne faut pas confondre le sous-titrage pour la traduction (attribut `kind="subtitles"` de la balise `<track>` en HTML5, par exemple) et le sous-titrage pour sourds et malentendants (attribut `kind="captions"` de la balise `<track>` en HTML5, par exemple). Ces deux types de sous-titrage poursuivent des buts différents. **Seule la présence et la pertinence d’un sous-titrage pour sourds et malentendants permet d’être conforme.**

[La note 2](sous-titres-synchronises-objet-multimedia) semble contredire le texte du WCAG qui indique explicitement dans [la technique H95](https://www.w3.org/WAI/WCAG21/Techniques/html/H95.html) que l'utilisation de `kind=subtitles` n'était pas invalide (sans être la meilleure option).

> An author may mark up a timed text track in the language of the audio track as `kind=subtitles`, instead of `kind=captions`, and may include additional relevant audio information. It is not best practice to use subtitles in this situation, since it may confuse users who are trying to find captions, **but such a timed text track would meet the requirements of Success Criterion 1.2.2.**

Dans le cas d'un discours, par exemple, cela reste tout à fait une solution légitime.

Dans la mesure où il n'y a aucune différence technique entre `subtitles` et `captions`, que le format de fichier et son rendu, tant à l'écran que par les lecteurs d'écran, est le même, il paraitrait un peu excessif de ne pas valider ce point en cas d'utilisation de l'attribut `kind="subtitles"`, et la formulation du WCAG parait plus modérée.

**Comment by alixraison** [comment]
Il est encouragé d’éviter la confusion entre les valeurs “subtitles” et “captions” lorsque le lecteur vidéo fait la différence entre ces deux types de sous-titrages, en le signalant par des pictogrammes et/ou un intitulé de menu différent.

Aucune modification n’est envisagée.

**Comment by innoticFR** [comment]
> Il est encouragé d’éviter la confusion entre les valeurs “subtitles” et “captions” lorsque le lecteur vidéo fait la différence entre ces deux types de sous-titrages, en le signalant par des pictogrammes et/ou un intitulé de menu différent.

Cette formulation est effectivement bien meilleure que la formulation actuelle et mériterait de remplacer la note 2.

**Comment by innoticFR** [comment]
Statut suite au passage au RGAA 4.1

Aucune modification n'a encore été apportée pour répondre à la problématique.

Action à entreprendre : reprendre la formulation proposée 
>Il est encouragé d’éviter la confusion entre les valeurs “subtitles” et “captions” lorsque le lecteur vidéo fait la différence entre ces deux types de sous-titrages, en le signalant par des pictogrammes et/ou un intitulé de menu différent.

**Comment by acaodinsic** [comment]
Le ticket concerne le glossaire de la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans le glossaire de la version RGAA 4.1

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
