### ISSUE TITLE
Formulation : Critère 6.2/Glossaire : Ancre

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#54]
**Il faut supprimer la mention "à l'exception des ancres" du critère 6.2, et la définition de "ancre" du glossaire**

Ne peuvent recevoir le focus que les éléments interactifs, et ceux-ci sont nécessairement dotés d'une alternative accessible.

A noter que:
- au niveau terminologie, un lien (`a[href]`) est une *ancre* (*"anchor"*),
- les *ancres nommées* (`a[name]` [en HTML 4](https://www.w3.org/TR/html4/struct/links.html#adef-name-A)) n'existent plus en HTML 5,

On ne peut réaliser des liens internes à la page vers tout élément muni d'un attribut `id`, qu'à la condition qu'il soit accessible au focus (afin qu'il soit compatible avec les technologies d'assistance).

- [les éléments accessibles au focus sont les éléments interactifs](https://www.w3.org/TR/wai-aria/#x7-3-focus-navigation) y compris [ceux munis de l'attribut `tabindex`](https://html.spec.whatwg.org/multipage/interaction.html#the-tabindex-attribute)
> An element with the tabindex attribute specified is interactive content.

---
Précision:
En HTML 5, une balise `<a>` non munie d'un attribut `href` [représente un indicateur pour marquer l'emplacement d'un lien inactivable ](https://www.w3.org/TR/html51/textlevel-semantics.html#the-a-element)(par exemple, la page en cours dans un menu):
> If the `a` element has no href attribute, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant, consisting of just the element’s contents.

Il n'existe pas de raison sémantique valide pour qu'une telle balise soit vide.

Cette balise, non munie de l'attribut `href` ne possède [aucun rôle ARIA par défaut](https://www.w3.org/TR/html-aria/#el-a-no-href) et n'est donc pas, en principe, un élément interactif susceptible de recevoir le focus.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de l’intitulé du critère 6.2 : 
“Critère 6.2 Dans chaque page web, chaque lien a-t-il un intitulé ?” ;

Ajout d’une note technique au critère 6.2 : 
“Note : une ancre n’est pas un lien même si pendant longtemps l’élément `<a>` a servi de support à cette technique. Elle n’est donc pas concernée par le présent critère.”

Suppression de l’entrée de glossaire “Ancre”

Suppression de la mention “(à l'exception des ancres)“ dans la note 4 de l’entrée de glossaire “Intitulé (ou nom accessible) de lien”

**Comment by sebastiendelorme** [comment]
À noter que la présence des ancres nommées dans le RGAA 4 permet éventuellement d'évaluer des interfaces qui sont encore codées en HTML4 (bien qu'elles se fassent rares et les cas des ancres nommées davatange).

<blockquote cite="https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/">
La méthode technique du RGAA permet de vérifier qu’une page web – c’est-à-dire tout contenu HTML (HTML4, XHTML1 et HTML5).
</blockquote>
Source : https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/

Toutefois, j'adhère tout à fait à la proposition en vue de simplifier le critère.

Quitte, à éventuellement garder une mention dans le glossaire ou dans une note de cas particulier comme c'est le cas de plusieurs critères propres à HTML5 dans le RGAA actuel.

**Comment by innoticFR** [comment]
Les spécifications HTML4 et XHTML1 apparaissent comme "superseded" par le W3C depuis le 27 mars 2018, donc après l'écriture des lignes présentes dans la méthode du RGAA. A noter que [le WCAG n'est pas plus à jour]( https://www.w3.org/WAI/WCAG21/Techniques/html/H88) :
> At the time this technique was published, the appropriate versions of these technologies is HTML 4.01 and XHTML 1.0. HTML 4.01 is the latest mature version of HTML, which provides specific accessibility features and is widely supported by user agents.

Je pense que HTML Living standard a mis fin à la nécessité de numéroter les versions et que la seule référence à la norme HTML est suffisante pour le RGAA.

**Comment by innoticFR** [comment]
Statut suite au passage au RGAA 4.1

Les modifications apportées répondent à la problématique soulevée ici

**Comment by juliemoynat-tanaguru** [comment]
Je remarque un problème : la note technique ajoutée fait mention du mot "ancre" sans en expliquer la signification. La définition du glossaire a été supprimée et n'aurait pas dû, finalement…
