### ISSUE TITLE
Formulation : Critère 1.3 & test : Images

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#56]
* Les éléments `object`, `embed`, `SVG`, `canvas` n'ont [pas de rôle implicite](https://www.w3.org/TR/html-aria/#docconformance) et sont donc considérés par défaut comme ayant le rôle `none` ou `presentation`

Les solutions proposées ne fonctionneront qu'à condition de définir un rôle approprié, par ex: `img`.

* Les différents tests gagneraient en clarté à être rassemblés différemment
  - 1er test : vérifier qu'une image porteuse d'information est marquée comme telle : présence d'un rôle ARIA implicite ou explicite,
  - 2e test : vérifier qu'elle possède une alternative textuelle native quand la technologie le permet (attribut `alt` pour les images, balises `title` pour le SVG
  - 3e test : vérifier qu'elle possède une alternative textuelle avec les attributs ARIA quand la technologie native ne le permet pas (`aria-label` ou `aria-labelledby`), ou en complément de l'alternative native si la restitution aux technologies d'assistance en a besoin,
  - 4e test : vérifier que lorsque les lecteurs d'écran supportent mal la technologie native (ex: balise `title` pour le SVG) les attributs `aria-label` et `aria-labelledby` sont utilisés en complément

* Plusieurs erreurs :
  - Test 1.3.6 SVG "le contenu de l'**attribut `title`** alors qu'on attend ici l'emploi de la **balise** `<title>`
  - Pour les autres tests, aucune technique du WCAG ne suggère d'utiliser l'attribut `title` pour la description des images. Au contraire (voir [The `title` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#The_title_attribute) ou [article de Steve Faulkner](https://developer.paciellogroup.com/blog/2016/02/short-note-on-use-of-alt-and-the-title-attribute/)) même s'il est présent dans l'algorithme de calcul du nom accessible, en dernier recours. Celui-ci viendra toujours en complément d'un attribut `alt` non vide.

---

A noter que l'algorithme de calcul du nom accessible est un algorithme de restitution pour les technologies d'assistance, supportant notamment ARIA.
Son rôle n'est pas de déterminer les techniques accessibles "pour tous les utilisateurs". C'est pour quoi il faut utiliser les fonctionnalités natives du langage en premier lieu dès lors que la technologie le permet (ex: balise `<title>` pour le SVG, ou attribut `alt` pour les images), quitte à devoir les renforcer avec ARIA si nécessaire.

La [technique ARIA10](https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA10) indique ainsi :
> Examine each element where the `aria-labelledby` attribute is present **and the element does not support the `alt` attribute**.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Il est inexact de dire que parce que “les éléments object, embed, SVG, canvas n'ont pas de rôle implicite”, ils “sont donc considérés par défaut comme ayant le rôle none ou presentation”.

La qualification de “No corresponding role” est définie de la manière suivante : “The elements marked with No corresponding role, in the second column of the table do not have any implicit ARIA semantics, but they do have meaning and this meaning may be represented in roles, states and properties not provided by ARIA, and exposed to users of assistive technology via accessibility APIs” (https://w3c.github.io/html-aria/#dfn-no-corresponding-role). Un élément qui n’a pas de rôle WAI-ARIA implicite ne dispose donc d’aucun rôle WAI-ARIA.

Modification de la première condition du test 1.1.6 :
“La balise `<object>` possède une alternative textuelle et un attribut `role=”img”`” ;

Modification de la première condition du test 1.1.7 :
“La balise `<embed>` possède une alternative textuelle et un attribut `role=”img”`” ;

Modification de la première condition du test 1.1.8 :
“La balise `<canvas>` possède une alternative textuelle et un attribut `role=”img”`” ;

Modification de la première condition du test 1.3.6 :
“S'il est présent, le contenu de l’élément `<title>` est pertinent” ;

Ajout d’une sixième note technique à l’entrée de glossaire “Alternative textuelle”: 
“Note technique 6 : Bien que l’attribut `title` soit considéré comme une possibilité d’alternative textuelle à une image, son usage peut poser problème, notamment du fait qu’une image avec un attribut `alt` absent ou vide est considérée comme une image pourvu d’un rôle “présentation” par WAI-ARIA : https://www.w3.org/TR/html-aam-1.0/#details-id-54. Il faut s’assurer que les assistances techniques présentes dans l’environnement de test retenu restituent correctement l’alternative proposée par l’attribut `title`.”

**Comment by innoticFR** [comment]
Effectivement, sans être inexact puisque je parlais du comportement "par défaut", c'était incomplet, et je vous remercie d'avoir attiré mon attention sur ce point. 

Toutefois, la documentation du W3C porte sur la possibilité ("MAY") que des éléments puissent avoir un rôle transmis par le navigateur à l'API d'accessibilité, même en l'absence de rôle ARIA. Cela ne signifie ni que tous les navigateurs doivent ("MUST") le faire, ni que les technologies d'assistance non basées sur l'API d'accessibilité puissent bénéficier des mêmes informations, ni que les technologies d'assistance de manière générale doivent nécessairement comprendre ou retransmettre ce rôle.

Le rôle non-ARIA  `SVGRoot`, par exemple, affecté par Chrome à la balise SVG sous Windows [correspond au rôle `NSAccessibilityGroupRole`](https://bitbucket.org/chromiumembedded/cef/src/816f700d3ea42bedc5ca5a2314c27b761b69abc5/tests/cefclient/browser/osr_accessibility_node_mac.mm#lines-190) sous environnement Apple et non au rôle `NSAccessibilityImageRole`

Ceci est a priori un choix volontaire comme l'indique le document [SVG Accessibility/ARIA roles for graphics](https://www.w3.org/wiki/SVG_Accessibility/ARIA_roles_for_graphics) du W3C:
> Structured graphical content (such as SVG) currently must be mapped to a non-graphical role, such as group

Par ailleurs, alors que l'API d'accessibilité ne bénéficie majoritairement qu'à une certaine partie des lecteurs d'écran, celle-ci n'est pas utilisées par les autres technologies d'assistance qui se basent sur le DOM de la page, notamment beaucoup d'outils liés aux troubles "dys" souvent disponibles sous forme de plugins navigateurs. Ceux-ci se baseront donc sur les rôles implicites ou explicites exposés dans le DOM de la page et les documents de références, et n'auront aucun accès à l'API d'accessibilité, ni aux choix faits ou non au niveau du navigateur qui ne seraient pas présents dans le DOM.

**Comment by innoticFR** [comment]
Statut suite au passage au RGAA 4.1

Les modifications apportées sont suffisantes à répondre a minima à la problématique dans le cadre de cette version mineure du RGAA. Dans le cadre d'une version majeure, une réécriture plus approfondie permettrait une meilleure lecture.
