### ISSUE TITLE
Formulation : Test 13.5.1 : contenu cryptique

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#57]
Problèmes recensés
---
* Absence de préconisations/contrôles sur les balises à utiliser,
* Attribut `title` devrait être évité,
* La référence à la [technique G160](https://www.w3.org/WAI/WCAG21/Techniques/general/G160) ne semble pas couvrir ce test.

Balises à utiliser
---
Il faudrait distinguer différents cas:

1. Cas où le contenu cryptique est assimilable à du contenu textuel (ex: *"leet speak"*, ...) 

    Le test actuel demande la vérification de l'attribut `title` mais n'indique pas le nom de la balise, offrant la possibilité de solutions non accessibles aux technologies d'assistance telles que `<div title="exemple">`.

    Lire au sujet de cet attribut : [Steve Faulkner : HTML5 Accessibility Chops: title attribute use and abuse](https://developer.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/)

    Dans la technique dont il est question ici ([Providing text alternatives for ASCII art, emoticons, and leetspeak](https://www.w3.org/WAI/WCAG21/Techniques/html/H86)), la note du WCAG est toutefois importante:

    > Because support for this technique is limited, it is recommended that authors provide the text alternative in text.

    Si cette technique cite des exemples avec la balise `<abbr>`, la procédure de tests précise :
    > Check that there is a **text alternative immediately before or after** all ASCII art, emoticons and/or Leetspeak.

    Dans l'exemple suivant, on restitue correctement ce qu'aurait dit la personne à l'oral, sans recours à la balise `<abbr>`, tout en permettant une compréhension visuelle de la phrase:

    > Au bac, j'ai pris `<div aria-hidden="true">1337 5|*34|</div>` (leet speak) en LV2

    **L'ajout de l'attribut `aria-hidden` au contenu que l'on ne souhaite pas restituer via la synthèse vocale est primordial dans ce test.**

2. Cas où le contenu cryptique est assimilable à une image significative (ex: émoticone, ascii ART, ...).

    Dans ce cas précis, il existe deux sous-catégories :
    * Un texte adjacent est présent (ex: ascii art)
    * Aucun texte adjacent n'est nécessaire (ex: émoticone UTF-8 visuellement explicite: "‎😃")

    Dans les deux cas, **il faudrait assimiler ce contenu à une image `role="img"` et fournir l'alternative via les attributs `aria-labelledby` pour le premier cas, et `aria-label` pour le second. Ainsi, on s'assure que le contenu cryptique n'est pas restitué en l'état aux technologies d'assistance tout en fournissant une alternative textuelle.** 

Problèmes de l'utilisation de la balise `<abbr>`
--
Le support de l'attribut `title` sur la balise `abbr` par les lecteurs d'écran nécessite une opération de la part de l'utilisateur (soit au niveau de la configuration, soit lors de la consultation de l'élément), afin de fournir une expérience similaire à tous les utilisateurs ([NVDA](https://github.com/nvaccess/nvda/issues/3828), Jaws, ...).

*A noter que l'attribut `title` de la balise `<abbr>` est souvent utilisé à tort dans des cas inutiles (SNCF, CAF, ...) ou au contraire dans des cas où l'abréviations mériterait d'être développée visuellement pour éviter toute confusion (J.O., S.A.S.) ou qu'elle fait partie d'un jargon inadapté ("15 A.C.N.").*

**Comment by alixraison** [comment]
Merci pour votre signalement.

Pour la remarque initiale :
Suppression du critère 13.5 la référence à la technique G160;

Le reste des remarques devrait plutôt être adressé directement au WCAG en charge de l’évolution des techniques.

A noter que les symboles ou émoticônes UTF-8 sont restitués par les lecteurs d’écran qui supportent UTF-8.

**Comment by innoticFR** [comment]
La référence faite au WCAG est là pour introduire de manière sourcée les éléments du RGAA qui pourraient être approfondis en se basant notamment sur une lecture plus approfondie de la technique existante : [H86](https://www.w3.org/WAI/WCAG21/Techniques/html/H86).

Pour le second point, il vise explicitement le cas où on ne souhaite pas reproduire le contenu "en l'état" (par exemple: l'alternative native de certaines émoticônes UTF-8 qui pourrait justement ne pas retranscrire le message porté)

**Comment by innoticFR** [comment]
Statut suite au passage au RGAA 4.1

Aucune réponse n'a été apportée à la problématique abordée.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse qui est prise en compte dans la version RGAA 4.1

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure. Le ticket pourrait, par exemple, proposer un texte à insérer dans une note technique à ajouter, qui serait associée au test.
