### ISSUE TITLE
Formulation : Critère 10.1 : Feuilles de style

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#58]
La formulation des tests 10.1.1 et 10.1.2 est ambiguë
> Test 10.1.1 : Dans chaque page web, les balises servant à la présentation de l’information ne doivent pas être présentes dans le code source généré des pages. Cette règle est-elle respectée ?

La notion de *"balise servant à la présentation de l'information"* est très vague, pouvant s'appliquer selon les interprétations aux balises `<div>`, `<span>`, ou encore  `<table>` qui sert à présenter des informations de manière tabulaire, par exemple, ou toute balise ayant pour rôle ARIA `presentation` (ce qui inclut celles n'ayant pas de rôle implicite comme `<svg>`).

Il faudrait ici parler de *"balises de présentations dépréciées de la norme HTML 5"*. La (quasi?) totalité des balises HTML 5 étant sémantiques, sauf `div` et `span`.

A noter que l'intention du [critère G140](https://www.w3.org/WAI/WCAG21/Techniques/general/G140) s'attarde davantage sur la structuration de l'information via des balises sémantiques, ce qui l'oppose, par exemple, à l'utilisation exclusive de `div` et `span`, ce qui n'est pas abordé non plus par le point 9 du RGAA. Le WCAG n'aborde pas l'utilisation des balises dépréciées.

Un exemple d'échec est le [F2 : Failure of Success Criterion 1.3.1 due to using changes in text presentation to convey information without using the appropriate markup or text](https://www.w3.org/WAI/WCAG21/Techniques/failures/F2) bien qu'il repose sur CSS

> Test 10.1.2 : Dans chaque page web, les attributs servant à la présentation de l’information ne doivent pas être présents dans le code source généré des pages. Cette règle est-elle respectée ?

Le notion d'"*attributs servant à la présentation de l’information*" s'applique tout aussi bien aux attributs `class` et `style` (ce dernier pouvant apparaître défini notamment via des interactions JS dans le code généré) 

Il faudrait ici plutôt interdire les '"attributs dépréciés" listés dans le glossaire au profit de leur équivalent CSS.

**Comment by alixraison** [comment]
Les éléments et les attributs “servant à la présentation de l'information” sont listées dans l'entrée de glossaire “Présentation de l’information”. Ils correspondent aux éléments (et attributs) dépréciés en HTML 4 et retirés de HTML 5.

Le RGAA 4 n’adresse pas seulement la dernière version de HTML, mais également les versions antérieures (HTML 4 et XHTML) qui pourraient encore être utilisées par des sites à auditer.

Aucune modification n’est envisagée.

**Comment by innoticFR** [comment]
>  Les éléments et les attributs “servant à la présentation de l'information” sont listées dans l'entrée de glossaire “Présentation de l’information”. Ils correspondent aux éléments (et attributs) dépréciés en HTML 4 et retirés de HTML 5.

Oui exactement. Cela va parfaitement dans le sens de mes remarques : *"Il faudrait ici parler de "balises de présentations dépréciées de la norme HTML 5"* / *Il faudrait ici plutôt interdire les '"attributs dépréciés" listés dans le glossaire au profit de leur équivalent CSS*.

Votre formulation est tout aussi valable et aiderait à la compréhension.

Je partage également votre avis sur la nécessité que le RGAA reste compatible avec les versions antérieures. Il ne me semble pas y avoir d’ambiguïté à ce sujet dans mon message.

Malgré tout, cela ne répond malheureusement pas au thème principal de ce ticket à savoir que ce critère est censé s'intéresser au balisage sémantique de la page (technique G140 par exemple), et que donc la question des balises ou attributs dépréciés me semble bien secondaire lorsqu'on devrait plutôt s'intéresser à l'utilisation abusive de `div` et de `span` avec CSS pour imiter les rôles natifs par exemple au lieu d'un heading par exemple, chose que ce critère n'aborde pas.

**Comment by innoticFR** [comment]
Statut suite au passage à RGAA 4.1

Aucune réponse n'a été apportée pour répondre à la problématique

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse et n'envisage pas de modification.

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure. Le ticket pourrait, par exemple, proposer une formulation plus adaptée.
