### ISSUE TITLE
Formulation : Critère 10.6 + Glossaire : Lien dont la nature n'est pas évidente

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#59]
Le glossaire indique :
>  En revanche, dans ce texte “Nouvelle grève à la SNCF, lire la suite” si “lire la suite” est un lien, un utilisateur ne percevant pas les couleurs n’aura pas de problème pour en comprendre la nature.

Cela contredit malheureusement l'intention portée à la technique [G183 : Using a contrast ratio of 3:1 with surrounding text and providing additional visual cues on focus for links or controls where color alone is used to identify them](https://www.w3.org/WAI/WCAG21/Techniques/general/G183). 

Il conviendrait de reprendre la définition originale du WCAG : *"Colored text when color alone is used to convey information such as words that are links in a paragraph"*

Cette technique est par ailleurs [contestée au sein du WCAG](https://github.com/w3c/wcag/issues/201) pour son non-support des écrans tactiles qui étaient rares à l'époque où elle a été introduite. Il est donc nécessaire d'avancer avec prudence quant à sa formulation. Celle-ci était vue il y a plus de 10 ans comme un "compromis" imparfait. Elle est maintenant inaccessible pour plus de 50% d'internautes, qui accèdent à internet avec leur mobile ou tablette.

---

*A ce sujet, j'en profite pour signaler, puisqu'ils sont concernés, que les [liens de la page Critères](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-10-6) du RGAA ont un [niveau correct de contraste de 3.07](https://webaim.org/resources/linkcontrastchecker/?fcolor=0A0A0A&bcolor=F5F5F5&lcolor=006A67) (#006a67 / #0a0a0a)  par rapport au texte mais ils sont vraiment très peu discernables du texte. Les souligner aiderait beaucoup. Ceux de Github, ici-même, par exemple, correspondent également à cette définition mais sont plus facilement discernables (avec un contraste à peine plus élevé).*

**Comment by juliemoynat-tanaguru** [comment]
Cette interprétation dans le glossaire me pose également question. On pourrait très bien avoir un texte "lire la suite" qui suggèrerait un lien alors qu'il n'y en a pas car il s'agirait juste de lire la suite du texte qui vient juste après.
L'intitulé du lien ne devrait pas avoir de rapport avec cette règle.

**Comment by alixraison** [comment]
Merci pour votre signalement.

La technique G183 fait effectivement polémique. Les discussions à son sujet ont repris depuis peu : https://github.com/w3c/wcag/issues/1118. L’issue de cette discussion pourra être analysée ultérieurement lors d’une évolution du RGAA.

Suppression du paragraphe dans le glossaire :
“En revanche, dans ce texte " Nouvelle grève à la SNCF, lire la suite" si "lire la suite" est un lien, un utilisateur ne percevant pas les couleurs n'aura pas de problème pour en comprendre la nature.”

**Comment by innoticFR** [comment]
Statut suite au passage au RGAA 4.1

La suppression du paragraphe répond à la problématique abordée.
