### ISSUE TITLE
Coquilles dans le glossaire

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#6]
Bonjour,

J'ai trouvé quelques coquilles dans le glossaire sur le [site du RGAA 4](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#contenu).

1. **« Contenu caché » :** la référence au critère 10.13 est erronée. Il s’agit du critère 10.8.
2. **« Intitulé visible » :** il faudrait un lien vers la définition « étiquette » pour bien comprendre que le `placeholder` ne peut pas être considéré comme intitulé visible, notamment. À moins que le `placeholder` puisse être considéré comme intitulé visible ?
3. **« Prise de focus » :** dans la note 2, il est écrit « ne doit pas être **pas** supprimée ». Il faut supprimer le deuxième « pas ».
4. À la lettre I, les mots ne sont pas tous dans l’ordre alphabétique. Il y a deux « Indication… » avant les « Images… »
5. **En-tête de colonne ou de ligne** : dans la phrase "Dans le cas contraire seul une balise `<th>` peut être utilisée." : il manque une virgule après "contraire" et un "e" à "seul".
6. **Légende** : dans la phrase "Il est également possible de créer des regroupements avec le rôle WAI-ARIA group et un passage de texte, faisant office de légende, liée par l’attribut WAI-ARIA par l’attribut WAI-ARIA aria-labelledby ou implémentée par l’intermédiaire d’un attribut WAI-ARIA aria-label.", les mots "lié" et "implémenté" ne devraient pas prendre de "e" final car le passage de texte est masculin.
7. **Média non temporel** : la note dit que "l’utilisation du paramètre wmode pour un objet Flash avec les valeurs "transparent" et "opaque" invalide de fait le critère 4.12" mais c'est plutôt le critère 4.13 que cela invalide puisque c'est dans le critère 4.13 qu'il est question de compatibilité avec les technologies d'assistance.
8. **Média temporel (type son, vidéo et synchronisé)** : idem que le point sur les média non temporels. Dans la note 1 : "l’utilisation du paramètre wmode pour un objet Flash avec les valeurs "transparent" et "opaque" invalide de fait le critère 4.11.", il s'agit du critère 4.13 et non 4.11.
9. **Raccourci clavier** : référence erronée au critère 12.15. Il s'agit en fait du critère 12.10
10. **Correctement restitué (par les technologies d'assistance)** : il est fait référence au test 1.3.7 pour l'exemple mais celui-ci a été supprimé dans le RGAA 4. On pourrait donc donner comme référence le test 1.3.8 sur canvas mais il faut modifier le texte : "Par exemple : le test **1.3.8** demande de vérifier que l’alternative d’une image **bitmap** porteuse d’information est correctement restituée."

**Comment by innoticFR** [comment]
Je me permets d'ajouter à la suite

11. Intitulé (ou nom accessible) de lien :
    * "x-link:title", à remplacer par "xlink:title"
    * "non conformité" remplacer par "non-conformité"

12. Lien SVG:
    * "x-link:title", à remplacer par  "xlink:title"

13. Liste des valeurs possibles pour l'attribut autocomplete
    * "identité sexuelle", à remplacer par "genre"

14. Règles d'écriture
    * "de valeurs multiple" à remplacer par "de valeurs multiples"

15. Type et format de données:
    * "jj/mm/aaa" à remplacer par "jj/mm/aaaa"

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.

**Comment by juliemoynat-tanaguru** [comment]
- Point 7 de mon premier message non pris en compte sur l'entrée "Média non temporel"
- Point 8 de mon premier message non pris en compte sur l'entrée "Média temporel (type son, vidéo et synchronisé)"
- Point 13 du message d' @innoticFR non pris en compte alors que la documentation WCAG officielle dit bien, par ailleurs, "Gender identity (e.g., Female, Fa’afafine)" pour la valeur "sex" https://www.w3.org/TR/WCAG21/#input-purposes
