### ISSUE TITLE
Précisions : Test 9.3.2 : Listes ordonnées

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#60]
Des précisions pourraient être nécessaires à ce test...

Notamment sur les méthodes acceptées ou non pour la numérotation des listes ordonnées *(ex: cas des listes ordonnées non-numérotées, inclure la numérotation dans le code HTML, via [compteurs CSS,](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters) ...)*

Il faudrait également voir si une liste comme la suivante (ordonnée mais non hiérarchisée correctement) serait considérée valide pour le RGAA.
```
<div role="list">
  <div role="listitem">1. Premier élément</div>
  <div role="listitem">1.1. Premier sous-élément</div>
  <div role="listitem">1.2. Second sous-élément</div>
</div>
```

Un critère WCAG associé avec les listes ordonnées est le [1.3.2 Meaningful sequences](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-sequence.html)
> The semantics of some elements define whether or not their content is a meaningful sequence. For instance, in HTML, text is always a meaningful sequence. Tables and **ordered lists are meaningful sequences**, but unordered lists are not.

Il existe donc un risque associé à l'utilisation des attributs `role="item"` et `role="listitem"` qui pourraient ne pas restituer une liste ordonnée de la même façon qu'une [balise `<ol>`](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ol-element) puisqu'on ne peut pas programmatiquement déterminer que la liste est ordonnée.

**Comment by alixraison** [comment]
L’utilisation des rôles “list” et “listitem” fait effectivement perdre en précision lorsqu’ils sont utilisés pour construire une liste ordonnée, mais c’est la correspondance établie dans le document “Aria in HTML” (https://w3c.github.io/html-aria/#el-ol).

Aucune modification n’est envisagée.

**Comment by innoticFR** [comment]
A noter que ce ticket porte sur les précisions qui pourraient être nécessaires (le conditionnel est ici utilisé) qui permettent notamment de distinguer les tests 9.3.1 et 9.3.2. Le but étant de ne pas utiliser l'un pour l'autre notamment, de permettre à la numérotation, si elle existe, d'être restituée correctement par les technologies d'assistance, et d'en permettre la navigation dans des bonnes conditions.

Sur l'utilisation des rôles `list` et `listitem`, je pense que certains attributs (`aria-posinset`, `aria-setsize`, `aria-level`) mentionnés dans ce document pourraient être une partie de la solution. Il n'a jamais été demandé de supprimer les rôles en question qui sont effectivement parfaitement en correspondance.

Il faut en outre garder à l'esprit qu'une liste ordonnée n'est pas forcément numérotée. L'ensemble de ces remarques pourrait figurer dans une version ultérieure du RGAA, le glossaire ou tout guide extérieur.

**Comment by innoticFR** [comment]
Statut suite au passage au RGAA 4.1

Aucune réponse n'a été apportée à la problématique abordée

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse et n'envisage pas de modification.

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure. Le ticket pourrait, par exemple, proposer un texte à insérer dans la note technique du test, ou dans le glossaire.
