### ISSUE TITLE
Formulation : Glossaire : URL

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#61]
> Note : dans le référentiel RGAA, la notion d’URL est utilisée à la place de URI (chaîne de caractères compacte identifiant une ressource).

Même si une URL est une URI, cette note me semble susceptible d'engendrer plus de questions que de réponses.

Le terme "URL" est utilisée 13 fois uniquement dans le RGAA, et toujours pour y désigner correctement une URL.

Il n'y a guère qu'au point *"Liste des valeurs possibles pour l'attribut autocomplete"*, à la valeur "impp" où le terme est discutable, mais l'erreur (s'il y a) est présente aussi [dans la documentation officielle](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-impp).

Ne serait-il pas plus simple de retirer cette note de la définition d'URL (qui ne parlera qu'aux initiés) et d'utiliser le terme "URI" au niveau d'"impp", si besoin?

**Comment by alixraison** [comment]
Merci pour votre signalement.

- Suppression de l’entrée de glossaire “URL” ;
- Suppression du lien associé dans le cas particulier du critère 13.1 ;
- Suppression du lien associé dans le test 4.8.1.

**Comment by design-gouv** [comment]
Une autre occurrence est également concernée : 
Suppression du lien associé dans le test 1.6.1.

**Comment by innoticFR** [comment]
Statut suite à la version 4.1 du RGAA : 

Les modifications apportées conviennent à répondre au ticket.
