### ISSUE TITLE
Formulation : Critères 6.1 & 6.2 : Texte du lien et nom accessible

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#63]
Les critères sur les liens 6.1, 6.2 ainsi que les notes du glossaire associées ([Intitulé (ou nom accessible) de lien](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#intitule-ou-nom-accessible-de-lien), ["intitulé visible"](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#intitule-visible)) nécessiteraient une reformulation afin de les rendre plus compréhensibles.

La formulation du critère 6.2 qui fait référence aux mêmes critères de succès et techniques WCAG que le 6.1 ne permet pas de comprendre suffisamment comment il répond à une chose différente que les points déjà abordés dans le 6.1 ni pourquoi il se situe logiquement après le 6.1

La rubrique 6 du RGAA s'adresse au Critère WCAG [2.4.4: Link Purpose (In Context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html) et au critère [2.5.3: Label in Name](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html) 

Le 2.4.4 couvre, *selon ma propre reformulation*, deux aspects :
- chaque lien doit nécessairement avoir visuellement une fonction évidente dans le contexte,
- si le rendu visuel apporte une information nécessaire à la compréhension du contexte, il faut fournir en plus des informations supplémentaires pour les technologies d'assistance.

Le critère 2.5.3 permet de couvrir la navigation à la parole en s'assurant que le libellé visuel (ou [la fonction iconique](symbolic-text-characters)) est repris dans le nom accessible dans le cadre de la navigation à la parole (Test 6.1.5 du RGAA).

Dans le cadre de ces critères, il faut donc d'abord se préoccuper du libellé visuel (dans le contexte) puis seulement ensuite du "nom accessible" pour les technologies d'assistance. C'est a priori la distinction faite entre les points 6.2 et 6.1 du RGAA.

Le risque est, en effet, ici d'oublier que ce critère ne concerne pas que les utilisateurs de technologie d'assistance comme les lecteurs d'écran, en ne testant que le nom accessible (qui est référencé sous le terme "[intitulé du lien](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#intitule-ou-nom-accessible-de-lien)" dans les différents tests du RGAA).

C'est d'autant plus important quand le contexte visuel est inexistant

*Exemple d'échec, un lien en haut de page porte la mention "EN", seul le "nom accessible" est fourni, mais le texte du lien n'est pas évident en l'absence de tout contexte :*
```
<a href="/en/" aria-label="Afficher la version anglaise du site">EN</a>
```
Faire précéder ce lien d'un simple texte "Langue" pourrait suffire à valider ce critère, car il donnerait suffisamment de contexte pour comprendre la nature du lien, d'autres améliorations étant possibles *(l'idée n'étant pas forcément de supprimer la mention concise "EN", destinée à un public anglophone)*.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Lorsque cela fait sens, une distinction entre « nom accessible » et « nom visible » d’un élément pourra être prise en compte ultérieurement lors d’une évolution du RGAA.

**Comment by innoticFR** [comment]
Statut suite au passage au RGAA 4.1

Les modifications apportées ne répondent pas à la problématique adressée ici.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse et n'envisage pas de modification. Il précise "une prise en compte ultérieurement lors d’une évolution du RGAA."

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne lieu à des questions dans la version RGAA 4.1, il convient d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d’une évolution ultérieure.
