### ISSUE TITLE
Critère 8.2 : règles d'écriture à respecter trop permissives

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#64]
Dans le [critère 8.2](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-8-2) sur la validité du code source, les règles ont été assouplies par rapport au RGAA 3 et cela me semble poser quelques problèmes. Je n'ai pas d'idée sur tout ce que cela implique mais je suis, par exemple, tombée sur un cas d'attribut `tabindex` utilisé, par erreur, sans valeur.

Ce n'est pas valide selon la [spécification HTML](https://www.w3.org/TR/html52/editing.html#the-tabindex-attribute) mais ce n'est pas non-conforme au RGAA 4 si on se réfère à ce point du test 8.2.1 :

>Les balises, attributs et valeurs d’attributs respectent les règles d’écriture ;

Et à la définition du glossaire "[Règles d'écriture](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#regles-d-ecriture)". Pourtant, il me semble que cela peut avoir une incidence sur la compatibilité avec les technologies d'assistance.

Ne devrions-nous pas ajouter que les valeurs d'attributs doivent être conformes à l'usage prévu par la spécification ?

**Comment by innoticFR** [comment]
il aurait peut-être fallu baser la rédaction de ce test également sur la [technique H88 nécessaire et suffisante](https://www.w3.org/WAI/WCAG21/Techniques/html/H88)...

**Comment by alixraison** [comment]
D’abord, une mise au point sur les changements :

- Le test 8.2.1 a été reformulé et fait apparaître désormais deux précisions supplémentaires par rapport au RGAA 3 : unicité des valeurs d’attributs id et l’absence d’attribut en double sur un même élément ;
- Le test 8.2.2 qui sanctionnait l’utilisation d’éléments obsolètes a été supprimé.

Il n’y a donc eu d’assouplissement que par rapport à ce second point, mais en aucun cas par rapport à une quelconque validité sémantique qui aurait été exigée par le RGAA 3 mais plus par le RGAA 4. 

Une valeur d’attribution erronée concerne la validation sémantique de cet attribut. La validation sémantique n’est pas directement présente dans le SC 4.1.1; elle est abordée dans la technique H88 associée où il est précisé : “Using features in the manner prescribed by the specification. The HTML specification provides specific guidance about how particular elements, attributes, and attribute values are to be processed and understood semantically”.

Aucune modification n’est envisagée.
