### ISSUE TITLE
Erreur dans l'url du SC 1.3.5

### ISSUE THREAD

**Issue by OlivierNourry** [DISIC/RGAA#65]
Les notes techniques du critère 11.13 renvoient vers le SC 1.3.5 via un lien dont l'url est erronée. La bonne URL est https://www.w3.org/TR/WCAG21/#identify-input-purpose

**Comment by innoticFR** [comment]
Il y a également :

RGAA 4.1 -> [1.2.3 Audio Description and Media Alternative (Prerecorded)](https://www.w3.org/TR/WCAG21/#audio-description-or-media-alternative-prerecorded).
RGAA 9.1 -> [2.4.1 Bypass Block](https://www.w3.org/TR/WCAG21/#bypass-blocks)
RGAA 1.2 -> [4.1.2 Name, Role, Value](https://www.w3.org/TR/WCAG21/#name-role-value)

**Comment by alixraison** [comment]
Merci pour votre signalement.
Les corrections signalées seront prises en compte.
