### ISSUE TITLE
Critère 5.8 : l'attribut summary ne devrait pas être présent non plus

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#67]
Dans le [critère 5.8](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-5-8), il est demandé :

>Le tableau de mise en forme (balise `<table>`) ne contient pas de balises `<caption>`, `<th>`, `<thead>`, `<tfoot>`, `<colgroup>` ou de balises ayant un attribut WAI-ARIA `role="rowheader"`, `role="columnheader"`.

Il faudrait ajouter l'attribut `summary` à cette liste.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Ajout de la référence à l'attribut summary dans la première condition du test 5.8.1 : 
“Le tableau de mise en forme (balise `<table>`) n’a pas d’attribut `summary` (sinon vide) et ne contient pas de balises `<caption>`, `<th>`, `<thead>`, `<tfoot>`, `<colgroup>` ou de balises ayant un attribut WAI-ARIA `role="rowheader"`, `role="columnheader"`.”

**Comment by alixraison** [comment]
Le cas envisagé n’est pas pertinent dans la mesure où un contenu cryptique est un contenu qui fait sens. Il n’y a pas de contenus cryptiques décoratifs.

Par exemple, un émoticon devient un contenu cryptique lorsqu’il fait sens dans un contexte donné :

1. “Il est temps de faire la fête [émoticon festif ] !”
2. “Il est temps de faire la [émoticon festif] !”

Dans le premier cas, l'emoticon s’ajoute de manière redondante au texte et n’a pas besoin d’alternative (voire à l’inverse a besoin d’être ignorée par un lecteur d’écran s’il s’agit d’un caractère unicode pris en charge par les technologies d’assistance)

Dans le second cas, l'emoticon complémente le texte et nécessite alors une alternative.

Aucune modification n’est envisagée.

**Comment by juliemoynat-tanaguru** [comment]
Bien pris en compte dans RGAA 4.1
