### ISSUE TITLE
Critère 11.10 - Lien vers le glossaire pour "type de données et/ou de format"

### ISSUE THREAD

**Issue by stevenMouret** [DISIC/RGAA#68]
Tests 11.10.5, 11.10.6, 11.10.7

Il manque le lien vers le glossaire pour les termes "type de données et/ou de format" ce qui est important car le glossaire précise que pour les champs qui proposent un masque de saisie, l'indication de format n'est pas nécessaire.

**Comment by juliemoynat-tanaguru** [comment]
Je pense que ce ticket fait doublon avec le ticket générique suivant : https://github.com/DISIC/RGAA/issues/33

**Comment by stevenMouret** [comment]
Merci Julie, j'avais cherché mais je n'avais pas trouvé.
