### ISSUE TITLE
Critère 13.5 : aucune condition ne permet de dire qu'un contenu cryptique décoratif doit être masqué aux TA

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#69]
Dans le [critère 13.5](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-13-5) sur les contenus cryptiques, le test est le suivant :

>Test 13.5.1 : Dans chaque page web, chaque contenu cryptique (art ASCII, émoticon, syntaxe cryptique) vérifie-t-il une de ces conditions ?
>- Un attribut `title` est disponible.
>- Une définition est donnée par le contexte adjacent.

Hors, il existe des cas où les contenus cryptiques sont décoratifs et ne doivent pas avoir d'alternative mais être masqués aux technologies d'assistance.

Par exemple, quand je trouve ce contenu cryptique dans une page : `<p>----------------------------------</p>`, celui-ci doit pouvoir être invalidé et on doit pouvoir dire de masquer ce contenu aux TA et non pas demander une alternative ; cela n'aurait aucun sens.

**Comment by alixraison** [comment]
Le cas envisagé n’est pas pertinent dans la mesure où un contenu cryptique est un contenu qui fait sens. Il n’y a pas de contenus cryptiques décoratifs.

Par exemple, un émoticon devient un contenu cryptique lorsqu’il fait sens dans un contexte donné :

1. “Il est temps de faire la fête [émoticon festif ] !”
2. “Il est temps de faire la [émoticon festif] !”

Dans le premier cas, l'emoticon s’ajoute de manière redondante au texte et n’a pas besoin d’alternative (voire à l’inverse a besoin d’être ignorée par un lecteur d’écran s’il s’agit d’un caractère unicode pris en charge par les technologies d’assistance)

Dans le second cas, l'emoticon complémente le texte et nécessite alors une alternative.

Aucune modification n’est envisagée.

**Comment by juliemoynat-tanaguru** [comment]
Je ne comprends pas. L'exemple 1 est décoratif selon votre explication. Quel critère permet donc de dire qu'il devrait être mis en place une solution pour que les lecteurs d'écran l'ignore ?

**Comment by sebastiendelorme** [comment]
Bonjour Julie,

L'exemple que tu donnes (`<p>----------------------------------</p>`) est une mise en forme basée sur HTML, effectivement un élément décoratif.

Et je te rejoints dans le fait que je ne trouve pas réellement de critère pour invalider cet usage (ou alors je n'ai pas encore trouvé où le rattacher précisément), 
Je vois deux pistes possibles : 

1/ C'est de la présentation d'information qui pourrait être faite en CSS. 
Aussi, cet exemple pourrait être traité dans le [critère 10.1 : Dans le site web, des feuilles de styles sont-elles utilisées pour contrôler la présentation de l’information ?](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-10-1).

C'est très proche du test 10.1.3 :
> Dans chaque page web, l’utilisation des espaces vérifie-t-elle ces conditions ?
> - Les espaces ne sont pas utilisées pour séparer les lettres d’un mot ;
> - Les espaces ne sont pas utilisées pour simuler des tableaux ;
> - Les espaces ne sont pas utilisées pour simuler des colonnes de texte.

2/ C'est un élément décoratif qui nécessiterait que le [Critère 1.2. Chaque image de décoration est-elle correctement ignorée par les technologies d’assistance ?](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-1-2) soit étendu aux éléments décoratifs qui ne sont pas seulement des images.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse et n'envisage pas de modification.

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
