### ISSUE TITLE
Tests 11.10.3 et 11.10.6 : message d'erreur attaché au champ avec aria-describedby

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#7]
Bonjour,

Pour le [test 11.10.3](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#test-11-10-3), il semble que, si un message d'erreur "Ce champ est obligatoire" se trouve sous un champ en étant attaché au champ via un attribut `aria-describedby`, cela ne soit pas valide.

En effet, il est demandé que le message identifie nommément le champ ou que le champ ait un attribut `aria-invalid="true"`.

Le problème est similaire pour le [test 11.10.6](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#test-11-10-6) pour les champs avec instruction ou indication du type de données et/ou de format obligatoire.

Il me semble pourtant que ce ne serait pas invalide selon WCAG ; fais-je erreur ?

**Comment by alixraison** [comment]
Les références à la possibilité d’associer un message au champ concerné au moyen de l’attribut aria-describedby sont présentes dans les tests 11.10.4 et 11.10.7.

Aucune modification n’est envisagée.

**Comment by stevenMouret** [comment]
@design-gouv cela est vrai uniquement quand le champ possède l'attribut aria-invalid="true". Ne faudrait-il pas rajouter au 11.10.6 :
"Le message d’erreur fournissant une instruction ou une indication du type de données et/ou de format obligatoire est visible et située dans le passage de texte associé au champ."

Cordialement
