### ISSUE TITLE
Critère 12.6: expression "titre de hiérarchie" non définie

### ISSUE THREAD

**Issue by OlivierNourry** [DISIC/RGAA#70]
> La zone possède un **titre de hiérarchie** dont le contenu permet de comprendre la nature du contenu de la zone.

Cette expression n'apparaît qu'à cet endroit du référentiel. Si on connaît l'accessibilité, on se doute qu'il est question des headings (H1..H6 ou role=heading), mais pour quelqu'un qui n'a pas cette connaissance, cette formulation peut prêter à confusion AMHA.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de l’intitulé de la deuxième condition du test 12.6.1 : 
"La zone possède un titre dont le contenu permet de comprendre la nature du contenu de la zone."
