### ISSUE TITLE
Critères 3.2 et 3.3 : manque d'un test : l'activation d'un mécanisme d'amélioration des contrastes ne doit pas créer de perte d'information

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#72]
Dans les critères 3.2 et 3.3, on demande de vérifier que les contrastes sont respectés lorsqu'on active un mécanisme qui permet d'afficher le texte avec un rapport de contraste conforme.

Je suis tombée sur un cas où j'ai de l'information donnée par un élément graphique qui disparaît lorsqu'on active ce mécanisme. J'ai vérifié [la définition pour le mécanisme](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#mecanisme-qui-permet-d-afficher-un-rapport-de-contraste-conforme) dans le glossaire et n'ai rien trouvé à ce sujet.

Pourtant, la [technique G174 des WCAG](https://www.w3.org/WAI/WCAG21/Techniques/general/G174.html) dit justement ceci :

>The new page must contain all the same information and functionality as the original page.

Hors, ce point permettant de vérifier que les informations et fonctionnalités sont bien présentes dans la page modifiée n'est pas présent dans le RGAA.

Ne devrions-nous pas ajouter un test à ce sujet ?

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modification de l’entrée de glossaire “Mécanisme qui permet d'afficher un rapport de contraste conforme” :
“Composant d’interface dont l’activation permet de modifier l’apparence du site ou de la page de manière à afficher les contenus avec un ratio de contraste suffisant. Le design de ce composant d’interface devra être conforme aux critères 3.2 et 3.3 sans avoir recours lui-même à un mécanisme permettant d’afficher un rapport de contraste conforme. Ce mécanisme doit conserver à l’identique les contenus et les fonctionnalités du site ou de la page qu’il modifie.”

**Comment by juliemoynat-tanaguru** [comment]
Bien pris en compte dans RGAA 4.1
