### ISSUE TITLE
Critère 8.2 : cas particulier sur les éléments obsolètes

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#73]
Dans le [critère 8.2](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-8-2), avec le RGAA 4, on n'invalide plus les éléments obsolètes donc je ne comprends pas le cas particulier du 8.2 qui dit :

>Pour accompagner la prise en charge progressive de HTML par les navigateurs, les APIs d’accessibilité et les technologies d’assistance, certains critères peuvent exiger la présence d’attributs ou de balises déclarés « obsolètes » en HTML. Par ailleurs, dans la mesure où des balises ou des attributs déclarés « obsolètes » sont utilisés, ils restent soumis aux autres critères du RGAA (exemple la balise `<marquee>` serait non conforme par rapport au critère 13.8) et leur support d’accessibilité doit être vérifié au regard de l’environnement de test (ou « base de référence ») retenu.

Si les éléments obsolètes ne sont plus invalidables au regard du RGAA, il n'y a donc aucun cas particulier associé à ce critère. Il s'agirait, à la limite, d'une note technique (et encore puisque cela concerne une ancienne version du RGAA).

La note de révision sur la suppression de l'ancien test 8.2.2 "Pour chaque déclaration de type de document, le code source de la page ne doit pas utiliser d'éléments obsolètes. Cette règle est-elle respectée (hors cas particuliers) ?" dit ceci, qui ne m'éclaire pas plus :

>En l’absence de techniques ou d’éléments dans les WCAG indiquant l’interdiction d’utiliser des éléments obsolètes, le test est supprimé. L’usage d’éléments ou attributs obsolètes sera encadré par le cas particulier du critère 8.2 demandant de vérifier si ces éléments en question sont toujours compatibles avec l’accessibilité sur la base de référence retenue.

Selon moi, le cas particulier devrait simplement être supprimé.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Suppression du cas particulier du critère 8.2.

**Comment by juliemoynat-tanaguru** [comment]
Pris en compte dans RGAA 4.1
