### ISSUE TITLE
Critère 11.5 : invalider des regroupements de champs non nécessaires mais présents

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#74]
Le [critère 11.5](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-11-5) demande à ce que les champs qui doivent être regroupés le soient.

En revanche, il n'est pas possible dans ce critère d'invalider un regroupement de champs de formulaire inapproprié.
Pour invalider un regroupement de champs inapproprié, on peut :

1. Soit, l'invalider au [critère 11.6](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-11-6) s'il n'a pas de légende ;
2. Soit, l'invalider au [critère 11.7](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-11-7) au motif que le regroupement n'étant pas approprié, la légende n'est pas pertinente.

La façon dont on peut invalider ce cas n'est pas dite dans le RGAA. On doit le deviner. Or, cela n'est pas forcément évident quand on débute dans le domaine.

Pourrait-on soit ajouter un test dédié, soit ajouter l'information dans une note technique ou dans le glossaire ? (Ma préférence va à l'ajout d'un test explicite.)

**Comment by alixraison** [comment]
Comment déterminer le caractère inapproprié d’un regroupement de champs de même nature ? 

- Soit le regroupement contient moins de champ que prévu : dans ce cas tous les champs de même nature ne sont pas regroupés ensemble et le critère 11.5 s’applique alors (le champ manquant devra être ajouté au groupement, par exemple) ;
- Soit le regroupement contient plus de champs que prévu : dans ce cas les champs de même nature ne font pas l’objet d’un regroupement spécifique, et le critère 11.5 s’applique de nouveau (un autre regroupement devra être créé au sein du premier regroupement, par exemple).

Dans les deux cas, le critère 11.5 et son test 11.5.1 suffisent.

Aucune modification n’est envisagée.

**Comment by juliemoynat-tanaguru** [comment]
Bonjour @alixraison,

On peut avoir un regroupement inapproprié, par exemple, si on a un regroupement d'un unique champ texte. C'est un regroupement qui n'a pas lieu d'être et doit être supprimé. Sauf erreur de ma part, cela ne correspond à aucune des conditions évoquées.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** (_alias alixraison_) y donne une réponse et n'envisage pas de modification.

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
