### ISSUE TITLE
Critère 13.7 : les vidéos devraient aussi être incluses dans le critère

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#75]
Dans le [critère 13.7](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-13-7) sur les changements brusques de luminosité ou les effets de flash, les vidéos ont été oubliées dans les tests alors qu'elles sont également concernées.

Le [critère WCAG](https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold.html) parle bien de vidéos.

>For example, the content could contain a video clip or animated image of a series of strobe flashes, or close-ups of rapid-fire explosions.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Le cas rapporté est pertinent et la référence à un élément multimédia doit être ajoutée aux tests du critère 13.7.

Modification du test 13.7.1 :
“Test 13.7.1 : Dans chaque page web, chaque image ou élément multimédia (balise <video>, balise <img>, balise <svg>,  balise <canvas>, balise <embed> ou balise <object>) qui provoque un changement brusque de luminosité ou un effet de flash vérifie-t-elle une de ces conditions ?

- La fréquence de l'effet est inférieure à 3 par seconde.
- La surface totale cumulée des effets est inférieure ou égale à 21 824 pixels.”

**Comment by juliemoynat-tanaguru** [comment]
Corrigé en RGAA v4.1
