### ISSUE TITLE
Critère 1.8 : la note technique n'est pas totalement juste

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#76]
Dans le [critère 1.8](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-1-8), la note technique indique :

>Le texte dans les images vectorielles étant du texte réel, il n'est pas concerné par ce critère.

Cependant, dans les images vectorielles, le texte n'est pas forcément du texte réel. Celui-ci peut être vectorisé à l'image de ce SVG : https://voxusagers.numerique.gouv.fr/static/bouton-blanc.svg

En lisant le critère WCAG "[images of text](https://www.w3.org/WAI/WCAG21/Understanding/images-of-text.html)", je me demande si, en fait, ce n'est pas pour le fait que ce soit du texte réel mais plutôt parce que l'image texte peut être personnalisée par l'utilisateur que les `<svg>` n'entre pas en compte dans ce critère. Je cite le critère WCAG :

>Success Criterion 1.4.5 Images of Text (Level AA): If the technologies being used can achieve the visual presentation, text is used to convey information rather than images of text except for the following:
>
>- Customizable: The image of text can be visually customized to the user's requirements;
>- Essential: A particular presentation of text is essential to the information being conveyed.

La définition de "visually customized" est : 

>the font, size, color, and background can be set

Pour un SVG "inline", effectivement, on peut personnaliser tout ça. En revanche, ce ne sera pas le cas pour un SVG intégré en source via l'élément `<img>`.

Aussi, je pense que la note technique devrait plutôt dire quelque chose comme ça :

>Les images vectorielles ne sont pas concernées par ce critère (hors implémentation via `<img>`) car elles peuvent être visuellement personnalisées (police, taille, couleur, fond).

**Comment by innoticFR** [comment]
Bonjour,

C'est exact, cette exception générique, sans réserves, dans le RGAA sur le format SVG ne prend pas en cause plusieurs facteurs:
- les textes ne sont pas forcément écrits avec la balise `<text>`
- les couleurs ne sont pas forcément héritées des balises parentes.

Il suffit d'activer le mode "contraste élevé" sous Windows pour voir que les textes, même avec la balise `<text>`, ne sont plus lisibles dans certains SVG. 

L'emploi de la valeur `currentColor` (**que le SVG soit inline ou non, d'ailleurs**) avec un fond transparent permet une meilleure accessibilité puisque cela permet effectivement de personnaliser sans grand effort, ni connaissance approfondie, le fond, la couleur, et la taille (avec le zoom du navigateur).

Différents tickets ont été soumis sur le Github du WCAG
https://github.com/w3c/wcag/issues/124
https://github.com/w3c/wcag/issues/773

**Comment by alixraison** [comment]
Merci pour votre signalement.

Ajout du test 1.8.6 :
Test 1.8.6 : Chaque image texte SVG (balise <svg>) porteuse d'information et dont le texte n’est pas complétement structuré au moyen d’éléments <text>, en l'absence d'un mécanisme de remplacement, doit si possible être remplacée par du texte stylé. Cette règle est-elle respectée (hors cas particuliers) ?

Dans le cas de fichiers SVG chargés en tant qu’image, c’est le test 1.8.1 qui s’applique.

**Comment by juliemoynat-tanaguru** [comment]
La modification du RGAA 4.1 semble bien répondre à ma demande initiale.
