### ISSUE TITLE
Cas particuliers critères 4.1, 4.2, 4.3, 4.5 sur l'exemption d'obligation d'accessibilité

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [DISIC/RGAA#77]
Le cas particulier du [critère 4.1](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-4-1) indique :

>Pour les services de l’État, les collectivités territoriales et leurs établissement : si le média temporel a été publié entre le 23 septembre 2019 et le 23 septembre 2020 sur un site internet, intranet ou extranet créé depuis le 23 septembre 2018, il est exempté de l’obligation d’accessibilité;
>
>Pour les personnes de droit privé mentionnées aux 2° à 4° du I de l’article 47 de la loi du 11 février 2005 : si le média temporel a été publié avant le 23 septembre 2020, il est exempté de l’obligation d’accessibilité.

Si la phrase pour les personnes de droit privé est très claire, celle pour le public l'est bien moins.
Quand je la lis, je comprends que :

* Si un site a été créé avant le 23 septembre 2018, il n'est pas exempté.
* Si un site a été créé à partir du 23 septembre 2018 et que la vidéo est publiée entre le 23 septembre 2018 et le 23 septembre 2019, elle n'est pas exemptée.

Pourtant, dans la page "Obligations d'accessibilité", on peut lire cette phrase, sans distinction public / privé :

>Les contenus audio et vidéo préenregistrés, y compris ceux comprenant des composants interactifs, publiés avant le 23 septembre 2020 ;

Cette phrase correspond bien à ce qui est dans le [décret n°2019-768](https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=096FEF4746E1680CCFF40D9A9222F29E.tplgfr29s_2?cidTexte=LEGITEXT000038956828&dateTexte=20190725&categorieLien=cid#LEGITEXT000038956828), article 3.

L'article 10 du même décret a beau dire ce qui suit, je ne pense pas que cela ait une incidence sur la date de l'exemption pour les contenus audio / vidéo préenregistrés :

>I. - Les dispositions du présent décret s'appliquent aux personnes mentionnées aux 1° à 3° du I de l'article 47 de la loi du 11 février 2005 susvisée :
>1° A compter du 23 septembre 2019 pour les sites internet, intranet et extranet créés depuis le 23 septembre 2018 ;
>2° A compter du 23 septembre 2020 pour les sites internet, intranet et extranet créés avant le 23 septembre 2018 ;

Il semble que tous les contenus audio et vidéo préenregistrés publiés avant le 23 septembre 2020 soient exemptés peu importe le type d'organisme (public ou privé).

**Comment by innoticFR** [comment]
Ce n'est pas tout à fait incompatible...

Le fait que le décret (qui reprend [la directive européenne](https://eur-lex.europa.eu/legal-content/FR/TXT/PDF/?uri=CELEX:32016L2102)) ne s'applique pas à ces dates n'exonère pas d'une obligation d'accessibilité. Il est ainsi précisé dans le RGAA :

> Toutefois jusqu’à l’entrée en vigueur du décret n° 2019-768 du 24 juillet 2019 dans les conditions définies à son article 10, l’État, les collectivités territoriales et les établissements publics qui en dépendent restent soumis aux obligations d’accessibilité prévues par le décret n° 2009-546 du 14 mai 2009.

C'est à dire : tant que le décret 2019/768 ne vous est pas applicable, vous êtes obligés d'avoir des vidéos accessibles puisque l'ancien ne prévoyait pas d'exemptions.

Donc pour le secteur public, il n'y a donc que dans le cas indiqué où il est effectivement en droit d'être exempté:
> Pour les services de l’État, les collectivités territoriales et leurs établissement : si le média temporel a été publié entre le 23 septembre 2019 et le 23 septembre 2020 sur un site internet, intranet ou extranet créé depuis le 23 septembre 2018, il est exempté de l’obligation d’accessibilité;

**Comment by juliemoynat-tanaguru** [comment]
Merci ; avec cette explication et à la lumière de [l'article 10 du décret](https://www.legifrance.gouv.fr/affichTexteArticle.do;jsessionid=4463ECA0A48F015D820CA940E214EB1C.tplgfr29s_2?idArticle=LEGIARTI000038956862&cidTexte=LEGITEXT000038956828&dateTexte=20200303), c'est vachement plus clair. La formulation dans le cas particulier me fait des nœuds au cerveau.

Et, finalement, je ne comprends pas pourquoi, au [critère 13.3](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-13-3), la formulation du cas particulier est différente :

>Pour les personnes de droit privé mentionnées aux 2° à 4° du I de l’article 47 de la loi du 11 février 2005 : si les fichiers bureautiques (ex : PDF, documents Microsoft ou libreOffice etc.) ont été publiés avant le 23 septembre 2018 (sauf si ce sont des documents nécessaires pour accomplir une démarche administrative relevant des tâches effectuées par l’organisme concerné), ils sont exemptés de l’obligation d’accessibilité ;

**Comment by innoticFR** [comment]
Cela reprend l'article premier de la [directive européenne 2016/2102 ](https://eur-lex.europa.eu/legal-content/FR/TXT/PDF/?uri=CELEX:32016L2102) qui spécifiait que la directive ne s'appliquait pas pour les fichiers créés avant cette date. Or dans le secteur public, pour les sites créés avant le 23 septembre 2018, la directive ne s'appliquera que le 23 septembre 2020.

A noter que la directive ne parle pas d'exemptions ni de dispenses. Le fait qu'elle ne s'applique pas ne signifie pas qu'une autre directive européenne (ou législation nationale) ne s'applique pas.

Par exemple, [la directive 2019/882](https://eur-lex.europa.eu/legal-content/FR/TXT/PDF/?uri=CELEX:32019L0882&from=FR) émet le même genre d'exceptions pour les fichiers bureautiques et les médias préenregistrés jusque 2025 : cela ne retardera pas pour autant l'obligation qui existe déjà pour le secteur public dans la directive 2016/2102

Ainsi, en France tout site internet public créé avant le 23 septembre 2018 ne pourra pas bénéficier des exemptions nouvelles introduites par le nouveau décret avant le 23 septembre 2020, date de l'application du nouveau décret pour ces sites.

Cela signifie curieusement qu'à partir de cette fatidique, certains contenus non accessibles deviendront exemptés de l'obligation d'accessibilité.

**Comment by alixraison** [comment]
Nous confirmons les échanges qui ont permis de lever l’incompréhension de départ.

Aucune modification n’est envisagée.

**Comment by juliemoynat-tanaguru** [comment]
Je viens de revenir sur le critère et je me suis à nouveau posée la même question. Les autres personnes avec moi comprenaient comme moi.

Par conséquent, la formulation au niveau du critère n'est pas claire. Si elle ne l'est pas pour moi et les 3 autres personnes avec qui j'étais, je pense qu'elle ne l'est pour personne. Par ailleurs, s'il faut revenir ici dans ce ticket ou consulter le décret et la directive européenne pour comprendre, ce n'est pas normal.

Il faut la revoir la formulation. Je ne comprends pas qu'aucune modification ne soit envisagée.

**Comment by innoticFR** [comment]
Bonjour, 

Pour ma part, je ne comprends pas la réponse qui a été faite par Alix Raison, dans la mesure où j'ai été le seul autre intervenant dans ce ticket et que je disais :

>Ainsi, en France tout site internet public créé avant le 23 septembre 2018 ne pourra pas bénéficier des exemptions nouvelles introduites par le nouveau décret avant le 23 septembre 2020, date de l'application du nouveau décret pour ces sites.
**Cela signifie curieusement qu'à partir de cette fatidique, certains contenus non accessibles deviendront exemptés de l'obligation d'accessibilité.**

Dans la mesure où nous avons dépassé cette date, la situation a évidemment changé depuis.

**Comment by acaodinsic** [comment]
Le ticket concerne la version RGAA 4.0.

**design-gouv** (_alias alixraison_) y donne une réponse et n'envisage pas de modification.

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une amélioration ultérieure.
