### ISSUE TITLE
Cas particulier - 10.11

### ISSUE THREAD

**Issue by llune** [DISIC/RGAA#78]
>Les tableaux de données (complexes).

Dans la liste des cas particuliers, il est précisé « complexes » pour les tableaux. Il me semble que cette précision n'apporte rien et peut induire en erreur les gens qui pourraient croire que les tableaux de données simples sont hors périmètre du cas particulier.

Proposition : supprimer la mention (complexes)

**Comment by innoticFR** [comment]
Cela se base sur le paragraphe suivant du [Understanding Success Criterion 1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)

> Complex data tables have a two-dimensional relationship between the headings and data cells. This relationship is essential to convey the content. This Success Criterion therefore does not apply to data tables.

Même, effectivement, la deuxième phrase, tout comme le reste du texte, semble que cette exception ne concerne pas uniquement les tableaux "complexes".

**Comment by llune** [comment]
Effectivement, d'où ma proposition.

**Comment by alixraison** [comment]
Merci pour votre signalement.

Modifier dans le critère 10.11 le cas particulier “Les tableaux de données (complexes)” par “Les tableaux de données”.

Pour information, l’"understanding" du critère 1.4.10 (https://www.w3.org/WAI/WCAG21/Understanding/reflow.html ) évoque aussi bien les "data tables" que les "complex data tables"; et comme le rappelle innoticFR on trouve dans la section "Content exceptions for reflow" le cas suivant :
"Complex data tables have a two-dimensional relationship between the headings and data cells. This relationship is essential to convey the content. This Success Criterion therefore does not apply to data tables". 

Reste à l'auditeur d'apprécier en situation s'il considère qu'un tableau est suffisamment complexe pour faire exception au critère.
