### ISSUE TITLE
Formulation : Obligations : Exemptions / Contenus de tiers

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#80]
Un nombre important de sites font apparaître dans leurs déclaration de conformité des *"composants tiers dérogés"*. Cette notion qui n’apparaît pas sous ce terme dans le RGAA est utilisée sans restriction pour déclarer conformes des sites qui ne le sont pas forcément en réalité.

Par exemple, on retrouve [grâce à Google sur plusieurs sites](https://www.google.com/search?q=%22composants+tiers+d%C3%A9rog%C3%A9s%22) des mentions de "composants tiers dérogés" comme :
- Lecteur vidéo Dailymotion
- Lecteur vidéo Youtube
- Contenus issus de Twitter
- Recaptcha
- Librairie JS Lightbox
- Librairie JS AddThis
- Vidéos issues de Allociné, INA
- Calendrier javascript
quand ce ne sont pas des motifs plus abstraits...

Le RGAA indique à la [liste des exemptions](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/obligations/):
> Les contenus de tiers qui ne sont ni financés ni développés par l’organisme concerné **et qui ne sont pas sous son contrôle**

Il faut pouvoir comprendre que les "tiers" dont il est question sont des personnes, et non pas des composants.

Cette définition provient de la [directive européenne](https://eur-lex.europa.eu/legal-content/FR/TXT/PDF/?uri=CELEX:32016L2102) à l'Article 1er, 4E.

Toutefois, cette directive donne plus de détails dans l'introduction qui permettent de mieux comprendre l'intention
> (30) Les contenus intégrés, tels que les images ou vidéos intégrées, devraient relever de la présente directive. Néanmoins sont parfois créés des sites internet et des applications mobiles sur lesquels des contenus supplémentaires peuvent être ultérieurement ajoutés, par exemple un programme de messagerie, un blog, un article qui permet aux utilisateurs d'ajouter des commentaires ou des applications pouvant gérer des contenus ajoutés par les utilisateurs. Un autre exemple serait une page, telle qu'un portail ou un site d'information, constituée de contenus recueillis auprès de multiples contributeurs, ou des sites qui intègrent automatiquement au fil du temps des contenus provenant d'autres sources, comme lorsque des publicités sont insérées de manière dynamique. Les contenus de tels tiers, à condition qu'ils ne soient ni financés ni mis au point par l'organisme du secteur public concerné, ni sous son contrôle, devraient être exclus du champ d'application de la présente directive. En principe,  de tels contenus ne devraient pas être utilisés s'ils entravent ou réduisent la fonctionnalité du service public offert sur le site internet ou l'application mobile concerné. Lorsque l'objectif du contenu de sites internet ou d'applications mobiles des organismes du secteur public est d'organiser des consultations ou des forums de discussion, ce contenu ne peut être assimilé au contenu de tiers et devrait donc être accessible, sauf dans le cas de contenus ajoutés par les utilisateurs qui ne sont pas sous le contrôle de l'organisme du secteur public concerné. 

La lecture de ce texte permet de rendre plus explicite le terme de  *"tiers"* et la mention *"qui ne sont pas sous son contrôle"* du RGAA qui signifie bien que ces contenus ne sont exemptés qu'à la condition qu'ils aient été insérés par des tiers, et non par le personnel de l'établissement ou ses prestataires.

De son côté, le WCAG traite le sujet des composants tiers dans le paragraphe "[Partial conformance claims due to third party content](https://www.w3.org/TR/UNDERSTANDING-WCAG20/conformance.html#uc-partial-third-head)"

Il y précise que l'emploi de ces composants tiers donne lieu à une déclaration de conformance partielle, c'est à dire de "non-conformance":
>  It is important to recognize that this is a statement of non-conformance and there are users who may not be able to access some of the content this page.

**En effet, lorsque le choix d'un lecteur vidéo, ou d'une librairie javascript relève de la responsabilité du créateur du site, il n'y a pas matière à obtenir d'exemption pour ce motif.**

Il faudrait donc que le RGAA soit plus explicite à ce niveau afin de limiter les incompréhensions.

Il reste possible pour certains organismes de passer par une dérogation pour charge disproportionnée, celle-ci s'accompagnant alors normalement d'une alternative accessible, ou d'autres exemptions (cartes géographiques, vidéos d'archives, etc.).

**Comment by innoticFR** [comment]
Voir également la question posée sur la liste RGAA du 22 mai 2020 qui fait écho à cette remarque : ["Contenus exemptés extensions WordPress"](https://framalistes.org/sympa/arc/rgaa/2020-05/msg00016.html)

**Comment by alixraison** [comment]
Cette demande ne concerne pas la méthode technique, les critères ou le glossaire du RGAA qui sont traités au niveau des issues sur Github.

**Comment by innoticFR** [comment]
C'est effectivement un élément qui est aujourd'hui absent de cette partie.

J'avoue que l'endroit où la précision sera insérée dans le RGAA m'importe peu, pourvu qu'elle vienne aider le plus grand nombre.

Même s'il est vrai que beaucoup d'exemptions figurent directement sous les critères dans les cas particuliers (ex. au critère 4.1 pour ce qui concerne la date de publication des vidéos), cela ne m’apparaît pas une solution très lisible pour ce types d'exemption qui pourrait s'appliquer à beaucoup de critères. 

Faudrait-il rajouter une page dans la méthode technique pour traiter des cas particuliers qui s'appliquent à plusieurs critères ?  A vous de voir...

**Comment by innoticFR** [comment]
Statut suite au passage au RGAA 4.1

Aucun ajout n'a été fait ni dans les techniques, ni les critères, ni le glossaire. Aucune réponse n'a donc été apportée à la problématique abordée ici

**Comment by stevenMouret** [comment]
Je suis d'accord avec Rémi, il serait intéressant dans la v4.1 du RGAA de préciser cela. Il y a peu de réponses aux demandes réalisées sur la liste de diffusion RGAA, et à priori les issues de Github ne sont pas non plus le bon canal. Sur quel canal ce genre de requêtes peuvent être fait ? Merci

**Comment by innoticFR** [comment]
On peut supposer qu'à présent que le dépôt contient toutes les pages, le Github semble être le bon canal ?

**Comment by acaodinsic** [comment]
Merci pour votre signalement.

Pour les obligations, le bon canal est la liste de **discussion** RGAA par l'envoi d'un courriel à **rgaa-request@framalistes.org** .

La DINUM n'est pas l'autorité compétente pour décider et valider des modifications au contenu du chapitre 1 du RGAA relatif aux obligations. Elle ne peut intervenir qu'au niveau d'erreurs de forme (orthographe, grammaire, conjugaison, ...).

Le ticket concerne la version RGAA 4.0.

**design-gouv** y donne une réponse et n'envisage pas de modification.

Je ferme donc ce ticket qui concerne la version RGAA 4.0

Néanmoins, si le point donne encore lieu à des questions dans la version RGAA 4.1, il conviendra d'ouvrir un nouveau ticket pour la version 4.1 avec éventuellement une référence liée à ce ticket, pour qu'elles puissent être analysées lors d'une évolution ultérieure.
