### ISSUE TITLE
Section 2. Cadre, liens vers le glossaire manquants

### ISSUE THREAD

**Issue by stevenMouret** [DISIC/RGAA#81]
Dans la [section 2. Cadre](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#topic2), les liens vers le glossaire sont manquants.

**Comment by juliemoynat-tanaguru** [comment]
Pour info, j'ai fait un ticket global avec les liens manquants vers le glossaire : https://github.com/DISIC/RGAA/issues/33

**Comment by stevenMouret** [comment]
Merci Julie, le pire c'est que je l'avais vu mais j'ai oublié entre temps.
