### ISSUE TITLE
Test 13.3.1 : alternative HTML

### ISSUE THREAD

**Issue by nmadeuf** [DISIC/RGAA#82]
Le test 13.3.1 traite des alternatives accessibles à fournir pour un document en téléchargement:

> Dans chaque page web, chaque fonctionnalité de téléchargement d'un document bureautique vérifie-t-elle une de ces conditions ?
> – Le document en téléchargement est compatible avec l'accessibilité.
> – Il existe une version alternative du document en téléchargement compatible avec l'accessibilité.
> – Il existe une version alternative du document en téléchargement au format HTML.

Le dernier point concernant l'alternative au format HTML ne précise pas qu'elle doit être accessible. 
Il faudrait changer la formulation pour: 

> – Le document en téléchargement est compatible avec l'accessibilité.
> – Il existe une version alternative du document en téléchargement compatible avec l'accessibilité.
> – Il existe une version alternative du document en téléchargement au format HTML compatible avec l'accessibilité.

ou

> – Le document en téléchargement est compatible avec l'accessibilité.
> – Il existe une version alternative du document en téléchargement (au format document ou HTML) compatible avec l'accessibilité.

**Comment by innoticFR** [comment]
Pour moi, l'alternative devrait être la suivante:
>– Le document en téléchargement est compatible avec l'accessibilité.
– Il existe une version alternative du document compatible avec l'accessibilité.

La définition de [Version accessible (pour un document en téléchargement)](https://numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#version-accessible-pour-un-document-en-telechargement) est ensuite suffisante à lister les précisions nécessaires

**Comment by design-gouv** [comment]
Merci de vos signalements.
La formulation des conditions du test sera clarifiée pour en faciliter la compréhension.
La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
