### ISSUE TITLE
Glossaire - Intitulé (ou nom accessible) de lien - Note 4 - Référence à un critère qui n'existe pas (plus)

### ISSUE THREAD

**Issue by sebastiendelorme** [DISIC/RGAA#83]
La note 4 de l'entrée "Intitulé (ou nom accessible) de lien" dans le glossaire précise : 

> Note 4 : lorsqu’un lien ne comporte aucun contenu (à l’exception des ancres), il sera non conforme au regard du critère 10.2 et du critère 6.4.

Le critère 6.4 n'existe plus dans le RGAA 4, il faut donc faire plutôt référence au critère 6.2.

**Comment by AlainVagner** [comment]
Ne faudrait-il pas faire ici plutôt référence au critère 6.1 comme mentionné dans les notes de révisions? 

> Le critère 6.4 est couvert par la nouvelle définition d’intitulé de lien dont la pertinence est vérifiée par le critère 6.1.

**Comment by sebastiendelorme** [comment]
Effectivement le lien pointait précédemment vers le critère 6.4 sur les liens identiques, et ce critère est désormais fondu dans le critère 6.1.  

Mais le critère 6.2 est le suivant : "Dans chaque page web, chaque lien, à l’exception des ancres, a-t-il un intitulé entre <a> et </a> ?"

Ainsi, lorsqu'un lien ne comporte aucun contenu, il invalide nécessairement le critère 6.2, puisque c'est l'objet même de critère. 

À moins que la note 4, soit là pour préciser qu'il faut invalider le 6.1 en supplément du 6.2 ?
Mais dans ce cas, c'est la présence complète du critère 6.2 qui est remise en question :)

**Comment by AlainVagner** [comment]
Si le 6,2 est aussi invalidé, ne pourrait-on pas ici mentionner les 3 critères?

Par exemple: "Note 4 : lorsqu’un lien ne comporte aucun contenu (à l’exception des ancres), il sera non conforme au regard des critères 6.1, 6.2 et 10.2"

**Comment by sebastiendelorme** [comment]
C'est une possibilité oui. 
Mais du coup, un lien sans intitulé invalide systématiquement deux critères de la thématique liens 6.1 et 6.2 ?

Sur le glossaire ça me semble cohérent, par contre, à terme je me pose clairement l'intérêt du critère 6.2 qui devient un cas particulier du 6.1.

**Comment by AlainVagner** [comment]
Pas de souci, je peux mettre à jour la PR avec les liens vers 6.1 et 6.2 dans le glossaire. 
Pour la pertinence du critère 6.2, il y a déjà d'autres issues qui discutent ce point: #54  et #63.

**Comment by juliemoynat-tanaguru** [comment]
L'ancienne référence au critère 6.4 a été corrigée en RGAA 4.1 : 
- Note de révision : https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/notes-revision-rgaa4.0-rgaa4.1/#intitul%C3%A9-ou-nom-accessible-de-lien
- Glossaire : https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#intitule-ou-nom-accessible-de-lien

**Comment by acaodinsic** [comment]
Point corrigé dans la version 4.1
