### ISSUE TITLE
Critère 10.1 : Différences entre la définition du glossaire et la méthodologie de tests

### ISSUE THREAD

**Issue by sbonaventure** [DISIC/RGAA#84]
Il y a une différence entre ce qui est indiqué dans la [méthodologie de test](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methodologie-test/#crit%C3%A8re-101-dans-le-site-web-des-feuilles-de-styles-sont-elles-utilis%C3%A9es-pour-contr%C3%B4ler-la-pr%C3%A9sentation-de-linformation) et le [glossire](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/glossaire/#presentation-de-l-information) pour les tests du critère 10.1

## Test 10.1.1

Dans la méthodologie de test, on par de la balise `<u>` alors que ce n'est pas mentionné dans la section du glossaire ou les cas particuliers du test.

### Section du glossaire 
> La présentation de l’information doit être réalisée via CSS. Les éléments (`basefont`, `blink`, `center`, `font`, `marquee`, `s`, `strike`, `tt` et `big`) [...] sont interdits.

### Section de la méthodologie de test
> * Vérifier l’absence des éléments de présentation `<basefont>`, `<blink>`, `<center>`, `<font>`, `<marquee>`, `<s>`, `<strike>`, `<tt> `;
> * Vérifier l’absence de l’élément `<u>` uniquement si le DOCTYPE du document ne correspond pas à HTML 5 ;
> * Si c’est le cas, le test est validé.

## Test 10.1.2
Les attributs sont présents dans le glossaire mais pas dans la méthodologie : `char`, `charoff`, `clear`, `compact`, `frameborder`, `hspace`, `marginheight`, `marginwidth`, `valign`, `vspace`, `size`
Les attributs sont présents dans la méthodologie mais pas dans le glossaire : `basefont`
Par ailleurs, `basefont `est cité dans les balises et les attributs.

### Section du glossaire 
> La présentation de l’information doit être réalisée via CSS. [...] Les attributs (`align`, `alink`, `background`, `bgcolor`, `border`, `cellpadding`, `cellspacing`, `char`, `charoff`, `clear`, `compact`, `color`, `frameborder`, `hspace`, `link`, `marginheight`, `marginwidth`, `text`, `valign`, `vlink`, `vspace`, `size`) sont interdits.
> Note : les attributs `width` et `height` utilisés sur d’autres éléments que les balises `<img>`, `<object>`, `<embed>`, `<canvas>` et `<svg>` sont également interdits.

### Section de la méthodologie de test
> Vérifier l’absence des attributs de présentation : `align`, `alink`, `background`, `basefont`, `bgcolor`, `border`, `color`, `link`, `text`, `vlink`, `cellpadding`, `cellspacing`, `width` (exception faite de l’élément `<img>`), `height` (exception faite de l’élément `<img>`) ;
> Si c’est le cas, le test est validé.

**Comment by stevenMouret** [comment]
Bonjour est ce possible d'avoir un retour sur cette issue ?

C'est la technique WCAG G140 qui s'applique. Elle ne précise pas nommément les balises et attributs concernés. Si je prends l'exemple de l'attribut `size`, il me semble que sur un select cet attribut à son utilité car il permet de personnaliser l'affichage des options dans la hauteur, ce que CSS ne permet pas de faire il me semble.

**Comment by design-gouv** [comment]
Merci de vos signalements.
Les corrections seront prises en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
