### ISSUE TITLE
relevé d'incohérences (ou coquilles) entre les notes de révision et le RGAA v4.0

### ISSUE THREAD

**Issue by hchuzeville** [DISIC/RGAA#90]
Bonjour,
 
Dans le cadre de la constitution de mon pense-bête RGAA v4 pour mes propres audits de sites, j’ai relevé quelques incohérences entre :
•	des critères (nouveaux) énoncés dans les notes de révision du RGAA v4.0 (https://www.numerique.gouv.fr/publications/rgaa-accessibilite/notes-revision/#contenu) 
•	et les critères et tests du RGAA v4.0 (https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#topic1),
pour les critères et tests (nouveaux) suivants :
 
1.	1.2.3 : « vérifie-t-elle ces conditions ? » dans les critères et tests du RGAA mais « vérifie-t-elle une de ces conditions ? » dans les notes de révision
2.	1.2.4 : idem
3.	1.2.5 : idem
4.	1.2.5 : il y a le « sous critère » suivant en trop dans les notes de révision ou manquant dans les critères et tests : « Les balises title et desc sont absentes ou vides »
5.	1.2.6 : « vérifie-t-elle ces conditions ? » dans les critères et tests du RGAA mais « vérifie-t-elle une de ces conditions ? » dans les notes de révision
6.	1.3.3 : « Pour chaque zone bouton » dans les notes de révision au lieu de « Pour chaque bouton » dans les critères et tests du RGAA
7.	1.4.4 : « (hors cas particuliers) » est en trop dans les notes de révision ou manquant dans les critères et tests
8.	1.4.5 : idem : « (hors cas particuliers) » est en trop dans les notes de révision ou manquant dans les critères et tests 
9.	1.4.6 : une coquille : il manque un « e » à « utilisé » dans le RGAA (mais il est bien présent dans les notes de révision)
10.	1.4.7 : « (hors cas particuliers) » est en trop dans les notes de révision ou manquant dans les critères et tests 
11.	1.6.10 : il y a le « sous critère » suivant manquant dans les notes de révision ou en trop dans les critères et tests : « Il existe un attribut WAI-ARIA aria-describedby associant un passage de texte faisant office de description détaillée »
12.	1.7.1 : « signalée dans l'attribut alt » dans les notes de révision au lieu de « signalée par l'alternative textuelle » dans le RGAA
13.	1.7.5 : « Chaque image embarquée (balise <svg>) » dans les notes de révision au lieu de « Chaque image vectorielle (balise <svg>) »
14.	1.7.6 : il y a le « sous critère » suivant manquant dans les notes de révision ou en trop dans les critères et tests : « La description détaillée contenue entre <canvas> et </canvas> est pertinente » 
15.	1.9.2 : « ayant une alternative textuelle, » est en trop dans les notes de révision ou manquant dans les critères et tests 
16.	1.9.3 : même chose : « ayant une alternative textuelle, » est en trop dans les notes de révision ou manquant dans les critères et tests 
17.	1.9.4 : idem : « ayant une alternative textuelle, » est en trop dans les notes de révision ou manquant dans les critères et tests
18.	1.9.5 : également : « ayant une alternative textuelle, » est en trop dans les notes de révision ou manquant dans les critères et tests
19.	2.2 : dans les notes de révision, il y a « Critère 2.2 Chaque cadre a-t-il un titre de cadre ? » au lieu de « Critère 2.2. Pour chaque cadre ayant un titre de cadre, ce titre de cadre est-il pertinent ? »
20.	5.7.4 : dans les notes de révision, il est indiqué « La cellule possède un attribut headers » alors que dans les critères et tests, il est indiqué « La balise possède un attribut headers »
21.	9.3.3 : j’ai un doute si « liste de description » est bien le terme voulu en remplacement du terme « listes de définitions » dans une version précédente du RGAA ?*
22.	10.11 : n’y a-t-il pas des mots manquants (« et à un défilement horizontal » ?) dans l’énoncé du critère qui semble bancal avec l’utilisation de « à la fois » ?
23.	11.2.4 : une coquille : il y a un « e » en trop à « associé » dans les critères et tests du RGAA (mais il est bien absent dans les notes de révision)
24.	11.5.1 : dans les critères et tests, dans le troisième sous critère, il apparaît un bouton radio à la place de « <input type="radio"> » qui apparait dans les notes de révision
25.	11.8 : une coquille : il y a un « e » en trop à « regroupés » dans les critères et tests du RGAA (mais il est bien absent dans les notes de révision)
26.	11.10.7 : 2 coquilles : des « s » à « une instruction » dans les critères et tests (alors que les coquilles ne sont pas présentes dans les notes de révision)
27.	12.2.1 : 2 coquilles : « de barres de navigation » au lieu de « les barres de navigation » dans les critères et tests et les pluriels ne sont pas accordés (alors que les coquilles ne sont pas présentes dans les notes de révision)
28.	12.6.1 : 2 coquilles : « précédent directement » au lieu de « précédant directement » dans les critères et tests (alors que les coquilles ne sont pas présentes dans les notes de révision)
29.	12.7.2 : une coquille : il y a un « ent » en trop à « vérifie-t-il » dans les critères et tests du RGAA (mais il est bien absent dans les notes de révision)
30.	13.7.2 : une coquille : il y a un « s » en trop à « un changements brusques » dans les critères et tests du RGAA (mais il est bien absent dans les notes de révision) à moins que ce soit un « les » ou « des » à mettre à la place de « un » ?
31.	13.7.2 : … car il y a une seconde incohérence entre les critères et tests : « les effets de flash » et le notes de révision : « un effet de flash ». Je ne sais pas le choix final retenu pour l’intitulé du test.
32.	13.7.3 : mêmes remarques que pour le test 13.7.2
33.	13.12 : dans les notes de révision, c’est le critère 13.10 qui est énoncé sous le titre « Nouveau critère 13.12 » à la place du critère 13.12
 
Je suppose que dans chacun des cas ci-dessus, c’est le RGAA qui est juste et les notes de révisions qui sont erronées. Mais pouvez-vous, svp, me le confirmer ? 
 
Je vous en remercie par avance.
 
J’ai rencontré également d’autres coquilles (notamment de copier-coller, particulièrement sur les numéros de critères et de tests) dans les notes de révision mais je ne les ai pas relevées au fur et à mesure.
 
Cependant, ces notes de révision sont un beau travail qui m’a été bien utile pour commencer d’assimiler les nouveautés du RGAA 4.0 et j’en remercie les auteurs / auteures !
 
Bien sincèrement,
 
Hervé CHUZEVILLE, responsable de domaine applicatif « Communication, sites Web, intranets et extranets »
Direction des Systèmes d’Information et des Usages Numériques (DSIUN) des agences de l’eau

**Comment by design-gouv** [comment]
Merci de vos signalements.
Les corrections seront prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
