### ISSUE TITLE
Critère 12.8 : La correspondance aux WCAG est incorrecte

### ISSUE THREAD

**Issue by stevenMouret** [DISIC/RGAA#91]
Dans les techniques suffisantes, je pense qu'il y a une coquille et que ce n'est pas la technique C7 mais la [C27](https://www.w3.org/TR/WCAG20-TECHS/C27.html) que vous avez souhaité ajouter.

L'objectif de cette technique est de permettre d'être certain que les contenus soient dans un ordre logique. Cette technique ne fait pas référence uniquement à l'ordre de tabulation mais à l'ordre des contenus. La technique C27 ne me semble pas pertinente pour ce critère. C'est bien la [H4](https://www.w3.org/TR/WCAG20-TECHS/H4.html) qui est pertinente sur la tabulation.

Le [critère 10.3](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode/criteres/#crit-10-3) du RGAA cherche à rendre logique l'ordre des contenus dans le code mais pas visuellement.

Il me semble donc qu'il n'existe pas de critère dans le RGAA qui permette de répondre à la technique C27.

**Comment by design-gouv** [comment]
Merci de votre signalement.
La correction sera prise en compte sur le nouveau site de publication du RGAA après la phase de vérification de la migration.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
