### ISSUE TITLE
Accessibilité des documents bureautiques

### ISSUE THREAD

**Issue by AlainVagner** [DISIC/RGAA#92]
Les critères 13.3 et 13.4 du RGAA 4 font référence à la version accessible d'un document en téléchargement qui est définie dans le glossaire. Cette définition fait référence à la "[liste des critères Documents Bureautiques en téléchargement](http://references.modernisation.gouv.fr/sites/default/files/liste-criteres-documents-bureautiques-telechargement-RGAA.odt)" qui est un document du RGAA 3 basé sur WCAG 2.0 et en particulier sur les techniques G et T.

Ce document ne devrait-il pas être mis à jour pour supporter les nouveaux critères de succès de WCAG 2.1 ainsi que les nouvelles techniques G et T?  Les critères AAA pourraient aussi être omis, comme c'est actuellement le cas dans le RGAA 4.

**Comment by cescarment** [comment]
J'ai l'impression que la liste des critères Documents Bureautiques en téléchargement a disparu avec la version RGAA 4.1. L'exigence d'une conformité à un référentiel à disparu, seul subsiste la notion de "doivent être rendus accessibles", sans défénir ce que celà veut dire.
[](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/glossaire/#version-accessible-pour-un-document-en-telechargement) 
La méthodologie de test fait toujours référence à ce document pour les formats .odt et EPUB/DAISY, mais le document n'existe plus.
[](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/methodologie-test/#contenu)

**Comment by AlainVagner** [comment]
Le document a été supprimé car obsolète. C'est ce qui est mentionné dans les [notes de révisions](https://www.numerique.gouv.fr/publications/rgaa-accessibilite/documentation-rgaa/notes-revision-rgaa4.0-rgaa4.1/#version-accessible-pour-un-document-en-t%C3%A9l%C3%A9chargement).
À mon avis, en l'absence d'un tel référentiel, c'est la [norme européenne](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf) qui s'applique, notamment son chapitre 10. Y sont référencés des critères de succès WCAG applicables aux documents bureautiques en téléchargement.
