### ISSUE TITLE
Coquilles Guide RGAA

### ISSUE THREAD

**Issue by innoticFR** [DISIC/RGAA#94]
Suite à la fermeture du ticket #5

> Il existe également des coquilles dans le guide : https://numerique.gouv.fr/publications/rgaa-accessibilite/obligations/#contenu (*ex: "tel que définit", "des éléments multimédia", "les évaluations (ou audits) de conformité prévus"*)

_Originally posted by @innoticFR in https://github.com/DISIC/RGAA/issues/5#issuecomment-576163145_

A noter que *"Cette demande ne concerne pas la méthode technique, les critères ou le glossaire du RGAA qui sont traités au niveau des issues sur Github."*

**Comment by design-gouv** [comment]
Merci de votre signalement.

Certaines des corrections ont d'ores et déjà été mises en œuvre.
Les corrections restantes seront prises en compte lors de la prochaine évolution ou après la validation de la migration du site.

**Comment by acaodinsic** [comment]
Merci de vos signalements : fermeture de cette issue.
****************************************
En raison de l’ouverture prochaine du nouveau site dédié à l’accessibilité numérique,
[Ce dépôt va être archivé prochainement](https://github.com/DISIC/RGAA/). 
****************************************
